//! Embedded ISF files shipped with volatility3 (`volatility3/framework/symbols/**` and
//! `volatility3/symbols/**`). GENERATED by listing `data/isf*`; regenerate when files change.

/// (relative path under the symbol root, top-level user dir?, contents)
pub static FILES: &[(&str, bool, &[u8])] = TABLE;

// ---- name lookup data, computed at compile time from TABLE ----
//
// The linker places each path literal next to its (large) contents, so reading the paths
// through `FILES` page-faults once per file (~100 us for all of them). Lookups by name use
// these compact tables instead: no runtime index construction, no allocation.

/// Number of embedded files.
pub const COUNT: usize = TABLE.len();

/// All relative paths back to back, in `FILES` order (path `i` is
/// `NAMES[NAME_OFFSETS[i]..NAME_OFFSETS[i + 1]]`).
pub static NAMES: [u8; names_len()] = {
    let mut out = [0u8; names_len()];
    let (mut i, mut k) = (0, 0);
    while i < COUNT {
        let b = TABLE[i].0.as_bytes();
        let mut j = 0;
        while j < b.len() {
            out[k] = b[j];
            k += 1;
            j += 1;
        }
        i += 1;
    }
    out
};

/// Start of each path in `NAMES`, plus the end.
pub static NAME_OFFSETS: [u32; COUNT + 1] = {
    let mut out = [0u32; COUNT + 1];
    let mut i = 0;
    while i < COUNT {
        out[i + 1] = out[i] + TABLE[i].0.len() as u32;
        i += 1;
    }
    out
};

/// File indices sorted by file name (last path component), ties in `FILES` order.
pub static BY_NAME: [u16; COUNT] = {
    let mut idx = [0u16; COUNT];
    let mut i = 0;
    while i < COUNT {
        idx[i] = i as u16;
        i += 1;
    }
    // stable insertion sort
    let mut i = 1;
    while i < COUNT {
        let mut j = i;
        while j > 0 && file_name_less(TABLE[idx[j] as usize].0.as_bytes(), TABLE[idx[j - 1] as usize].0.as_bytes()) {
            let t = idx[j];
            idx[j] = idx[j - 1];
            idx[j - 1] = t;
            j -= 1;
        }
        i += 1;
    }
    idx
};

const fn names_len() -> usize {
    let (mut i, mut n) = (0, 0);
    while i < COUNT {
        n += TABLE[i].0.len();
        i += 1;
    }
    n
}

/// Start of the last '/'-separated component of `p`.
pub const fn file_name_start(p: &[u8]) -> usize {
    let mut i = p.len();
    while i > 0 && p[i - 1] != b'/' {
        i -= 1;
    }
    i
}

/// Byte-wise `file_name(a) < file_name(b)`.
const fn file_name_less(a: &[u8], b: &[u8]) -> bool {
    let (mut i, mut j) = (file_name_start(a), file_name_start(b));
    while i < a.len() && j < b.len() {
        if a[i] != b[j] {
            return a[i] < b[j];
        }
        i += 1;
        j += 1;
    }
    a.len() - i < b.len() - j
}

const TABLE: &[(&str, bool, &[u8])] = &[
    ("generic/vmcs/haswell-architecture.json", true, include_bytes!("../../data/isf-top/generic/vmcs/haswell-architecture.json")),
    ("generic/vmcs/nehalem-architecture.json", true, include_bytes!("../../data/isf-top/generic/vmcs/nehalem-architecture.json")),
    ("generic/vmcs/sandybridge-architecture.json", true, include_bytes!("../../data/isf-top/generic/vmcs/sandybridge-architecture.json")),
    ("generic/vmcs/skylake-architecture.json", true, include_bytes!("../../data/isf-top/generic/vmcs/skylake-architecture.json")),
    ("generic/vmcs/westmere-architecture.json", true, include_bytes!("../../data/isf-top/generic/vmcs/westmere-architecture.json")),
    ("generic/qemu.json", false, include_bytes!("../../data/isf/generic/qemu.json")),
    ("linux/bash32.json", false, include_bytes!("../../data/isf/linux/bash32.json")),
    ("linux/bash64.json", false, include_bytes!("../../data/isf/linux/bash64.json")),
    ("linux/elf.json", false, include_bytes!("../../data/isf/linux/elf.json")),
    ("linux/xen.json", false, include_bytes!("../../data/isf/linux/xen.json")),
    ("windows/bigpools/bigpools-vista-x64.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-vista-x64.json")),
    ("windows/bigpools/bigpools-vista-x86.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-vista-x86.json")),
    ("windows/bigpools/bigpools-win10-x64.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-win10-x64.json")),
    ("windows/bigpools/bigpools-win10-x86.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-win10-x86.json")),
    ("windows/bigpools/bigpools-x64.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-x64.json")),
    ("windows/bigpools/bigpools-x86.json", false, include_bytes!("../../data/isf/windows/bigpools/bigpools-x86.json")),
    ("windows/callbacks-x64.json", false, include_bytes!("../../data/isf/windows/callbacks-x64.json")),
    ("windows/callbacks-x86.json", false, include_bytes!("../../data/isf/windows/callbacks-x86.json")),
    ("windows/consoles/consoles-win10-17763-3232-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-17763-3232-x64.json")),
    ("windows/consoles/consoles-win10-17763-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-17763-x64.json")),
    ("windows/consoles/consoles-win10-18362-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-18362-x64.json")),
    ("windows/consoles/consoles-win10-19041-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-19041-x64.json")),
    ("windows/consoles/consoles-win10-20348-1970-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-20348-1970-x64.json")),
    ("windows/consoles/consoles-win10-20348-2461-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-20348-2461-x64.json")),
    ("windows/consoles/consoles-win10-20348-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-20348-x64.json")),
    ("windows/consoles/consoles-win10-22000-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-22000-x64.json")),
    ("windows/consoles/consoles-win10-22621-3527-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-22621-3527-x64.json")),
    ("windows/consoles/consoles-win10-22621-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-22621-x64.json")),
    ("windows/consoles/consoles-win10-25398-x64.json", false, include_bytes!("../../data/isf/windows/consoles/consoles-win10-25398-x64.json")),
    ("windows/crash.json", false, include_bytes!("../../data/isf/windows/crash.json")),
    ("windows/crash64.json", false, include_bytes!("../../data/isf/windows/crash64.json")),
    ("windows/crash_common.json", false, include_bytes!("../../data/isf/windows/crash_common.json")),
    ("windows/gui/gui-win10-10586-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-10586-x64.json")),
    ("windows/gui/gui-win10-15063-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-15063-x64.json")),
    ("windows/gui/gui-win10-16299-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-16299-x64.json")),
    ("windows/gui/gui-win10-17134-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-17134-x64.json")),
    ("windows/gui/gui-win10-17735-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-17735-x64.json")),
    ("windows/gui/gui-win10-17763-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-17763-x64.json")),
    ("windows/gui/gui-win10-18362-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-18362-x64.json")),
    ("windows/gui/gui-win10-19041-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-19041-x64.json")),
    ("windows/gui/gui-win10-19577-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win10-19577-x64.json")),
    ("windows/gui/gui-win7sp0-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win7sp0-x64.json")),
    ("windows/gui/gui-win7sp1-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win7sp1-x64.json")),
    ("windows/gui/gui-win8-x64.json", false, include_bytes!("../../data/isf/windows/gui/gui-win8-x64.json")),
    ("windows/kdbg.json", false, include_bytes!("../../data/isf/windows/kdbg.json")),
    ("windows/kerb_ecrypt.json", false, include_bytes!("../../data/isf/windows/kerb_ecrypt.json")),
    ("windows/mbr.json", false, include_bytes!("../../data/isf/windows/mbr.json")),
    ("windows/mft.json", false, include_bytes!("../../data/isf/windows/mft.json")),
    ("windows/netscan/netscan-vista-sp12-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-vista-sp12-x64.json")),
    ("windows/netscan/netscan-vista-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-vista-x64.json")),
    ("windows/netscan/netscan-vista-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-vista-x86.json")),
    ("windows/netscan/netscan-win10-10240-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-10240-x86.json")),
    ("windows/netscan/netscan-win10-10586-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-10586-x86.json")),
    ("windows/netscan/netscan-win10-14393-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-14393-x86.json")),
    ("windows/netscan/netscan-win10-15063-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-15063-x64.json")),
    ("windows/netscan/netscan-win10-15063-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-15063-x86.json")),
    ("windows/netscan/netscan-win10-16299-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-16299-x64.json")),
    ("windows/netscan/netscan-win10-17134-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-17134-x64.json")),
    ("windows/netscan/netscan-win10-17134-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-17134-x86.json")),
    ("windows/netscan/netscan-win10-17763-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-17763-x64.json")),
    ("windows/netscan/netscan-win10-18362-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-18362-x64.json")),
    ("windows/netscan/netscan-win10-18363-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-18363-x64.json")),
    ("windows/netscan/netscan-win10-19041-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-19041-x64.json")),
    ("windows/netscan/netscan-win10-19041-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-19041-x86.json")),
    ("windows/netscan/netscan-win10-20348-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-20348-x64.json")),
    ("windows/netscan/netscan-win10-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win10-x64.json")),
    ("windows/netscan/netscan-win7-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win7-x64.json")),
    ("windows/netscan/netscan-win7-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win7-x86.json")),
    ("windows/netscan/netscan-win8-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win8-x64.json")),
    ("windows/netscan/netscan-win8-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win8-x86.json")),
    ("windows/netscan/netscan-win81-19935-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win81-19935-x64.json")),
    ("windows/netscan/netscan-win81-x64.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win81-x64.json")),
    ("windows/netscan/netscan-win81-x86.json", false, include_bytes!("../../data/isf/windows/netscan/netscan-win81-x86.json")),
    ("windows/pdb.json", false, include_bytes!("../../data/isf/windows/pdb.json")),
    ("windows/pe.json", false, include_bytes!("../../data/isf/windows/pe.json")),
    ("windows/poolheader-x64-win7.json", false, include_bytes!("../../data/isf/windows/poolheader-x64-win7.json")),
    ("windows/poolheader-x64.json", false, include_bytes!("../../data/isf/windows/poolheader-x64.json")),
    ("windows/poolheader-x86.json", false, include_bytes!("../../data/isf/windows/poolheader-x86.json")),
    ("windows/registry.json", false, include_bytes!("../../data/isf/windows/registry.json")),
    ("windows/services/services-vista-x64.json", false, include_bytes!("../../data/isf/windows/services/services-vista-x64.json")),
    ("windows/services/services-vista-x86.json", false, include_bytes!("../../data/isf/windows/services/services-vista-x86.json")),
    ("windows/services/services-win10-15063-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win10-15063-x64.json")),
    ("windows/services/services-win10-15063-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win10-15063-x86.json")),
    ("windows/services/services-win10-16299-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win10-16299-x64.json")),
    ("windows/services/services-win10-16299-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win10-16299-x86.json")),
    ("windows/services/services-win10-17763-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win10-17763-x86.json")),
    ("windows/services/services-win10-18362-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win10-18362-x64.json")),
    ("windows/services/services-win10-18362-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win10-18362-x86.json")),
    ("windows/services/services-win10-19041-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win10-19041-x64.json")),
    ("windows/services/services-win10-19041-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win10-19041-x86.json")),
    ("windows/services/services-win10-25398-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win10-25398-x64.json")),
    ("windows/services/services-win8-x64.json", false, include_bytes!("../../data/isf/windows/services/services-win8-x64.json")),
    ("windows/services/services-win8-x86.json", false, include_bytes!("../../data/isf/windows/services/services-win8-x86.json")),
    ("windows/services/services-xp-2003-x64.json", false, include_bytes!("../../data/isf/windows/services/services-xp-2003-x64.json")),
    ("windows/services/services-xp-x86.json", false, include_bytes!("../../data/isf/windows/services/services-xp-x86.json")),
    ("windows/shimcache/shimcache-2003-x64.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-2003-x64.json")),
    ("windows/shimcache/shimcache-2003-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-2003-x86.json")),
    ("windows/shimcache/shimcache-vista-x64.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-vista-x64.json")),
    ("windows/shimcache/shimcache-vista-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-vista-x86.json")),
    ("windows/shimcache/shimcache-win10-x64.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win10-x64.json")),
    ("windows/shimcache/shimcache-win10-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win10-x86.json")),
    ("windows/shimcache/shimcache-win7-x64.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win7-x64.json")),
    ("windows/shimcache/shimcache-win7-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win7-x86.json")),
    ("windows/shimcache/shimcache-win8-x64.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win8-x64.json")),
    ("windows/shimcache/shimcache-win8-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-win8-x86.json")),
    ("windows/shimcache/shimcache-xp-sp2-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-xp-sp2-x86.json")),
    ("windows/shimcache/shimcache-xp-sp3-x86.json", false, include_bytes!("../../data/isf/windows/shimcache/shimcache-xp-sp3-x86.json")),
    ("windows/unloadedmodules-x64.json", false, include_bytes!("../../data/isf/windows/unloadedmodules-x64.json")),
    ("windows/unloadedmodules-x86.json", false, include_bytes!("../../data/isf/windows/unloadedmodules-x86.json")),
    ("windows/wow64.json", false, include_bytes!("../../data/isf/windows/wow64.json")),
];
