//! linux plugins.

use crate::plugins::Plugin;

pub mod bash;
pub mod boottime;
pub mod capabilities;
pub mod ebpf;
pub mod elfs;
pub mod envars;
pub mod graphics;
pub mod iomem;
pub mod ip;
pub mod kallsyms;
pub mod kmsg;
pub mod kthreads;
pub mod library_list;
pub mod lsmod;
pub mod lsof;
pub mod malware;
pub mod module_extract;
pub mod mountinfo;
pub mod pagecache;
pub mod pidhashtable;
pub mod proc;
pub mod psaux;
pub mod pscallstack;
pub mod pslist;
pub mod psscan;
pub mod pstree;
pub mod ptrace;
pub mod sockscan;
pub mod sockstat;
pub mod tracing;
pub mod vmaregexscan;
pub mod vmayarascan;
pub mod vmcoreinfo;

pub fn register(v: &mut Vec<&'static dyn Plugin>) {
    v.push(&bash::Bash);
    v.push(&capabilities::Capabilities);
    v.push(&elfs::Elfs);
    v.push(&envars::Envars);
    v.push(&graphics::fbdev::Fbdev);
    v.push(&ip::Addr);
    v.push(&ip::Link);
    v.push(&library_list::LibraryList);
    v.push(&lsof::Lsof);
    v.push(&malware::malfind::Malfind);
    v.push(&mountinfo::MountInfo);
    v.push(&pagecache::Files);
    v.push(&pagecache::InodePages);
    v.push(&pagecache::RecoverFs);
    v.push(&malware::malfind::MalfindDeprecated);
    v.push(&malware::process_spoofing::ProcessSpoofing);
    v.push(&pidhashtable::PIDHashTable);
    v.push(&proc::Maps);
    v.push(&psaux::PsAux);
    v.push(&pslist::PsList);
    v.push(&psscan::PsScan);
    v.push(&pstree::PsTree);
    v.push(&ptrace::Ptrace);
    v.push(&sockscan::Sockscan);
    v.push(&sockstat::Sockstat);
    v.push(&vmaregexscan::VmaRegExScan);
    v.push(&vmayarascan::VmaYaraScan);
    v.push(&pscallstack::PsCallStack);
    v.push(&kthreads::Kthreads);
    // L2: kernel / rootkit-detection plugins
    v.push(&boottime::Boottime);
    v.push(&ebpf::Ebpf);
    v.push(&iomem::IOMem);
    v.push(&kallsyms::Kallsyms);
    v.push(&kmsg::Kmsg);
    v.push(&lsmod::Lsmod);
    v.push(&module_extract::ModuleExtract);
    v.push(&vmcoreinfo::VMCoreInfo);
    v.push(&malware::check_afinfo::CheckAfinfo);
    v.push(&malware::check_afinfo::CheckAfinfoDeprecated);
    v.push(&malware::check_creds::CheckCreds);
    v.push(&malware::check_creds::CheckCredsDeprecated);
    v.push(&malware::check_idt::CheckIdt);
    v.push(&malware::check_idt::CheckIdtDeprecated);
    v.push(&malware::check_modules::CheckModules);
    v.push(&malware::check_modules::CheckModulesDeprecated);
    v.push(&malware::check_syscall::CheckSyscall);
    v.push(&malware::check_syscall::CheckSyscallDeprecated);
    v.push(&malware::hidden_modules::HiddenModules);
    v.push(&malware::hidden_modules::HiddenModulesDeprecated);
    v.push(&malware::keyboard_notifiers::KeyboardNotifiers);
    v.push(&malware::keyboard_notifiers::KeyboardNotifiersDeprecated);
    v.push(&malware::modxview::Modxview);
    v.push(&malware::modxview::ModxviewDeprecated);
    v.push(&malware::netfilter::Netfilter);
    v.push(&malware::netfilter::NetfilterDeprecated);
    v.push(&malware::tty_check::TtyCheck);
    v.push(&malware::tty_check::TtyCheckDeprecated);
    v.push(&tracing::ftrace::CheckFtrace);
    v.push(&tracing::perf_events::PerfEvents);
    v.push(&tracing::tracepoints::CheckTracepoints);
}
