//! EVEX encoded instructions (AVX-512).
//! GENERATED by bench/scripts/gen_vex_spec.py from capstone 5 probing -- do not edit;
//! manual additions/overrides live in spec_sse.rs.

pub(crate) const SPEC: &str = r#"
e1 10 np w0 : vmovups r:X, m:X ; k nobm nobr novvvv z
e1 11 np w0 r : vmovups R:X, r:X ; k nobr novvvv z
e1 11 np w0 m : vmovups M:/X, r:X ; k nobm novvvv noz
e1 12 np w0 l0 r : vmovhlps r:x, v:x, R:x ; nobr nok noz
e1 12 np w0 l0 m : vmovlps r:x, v:x, M:/q ; nobm nok noz
e1 13 np w0 l0 m : vmovlps M:/q, r:x ; nobm nok novvvv noz
e1 14 np w0 : vunpcklps r:X, v:X, m:X ; bd k nobr z
e1 15 np w0 : vunpckhps r:X, v:X, m:X ; bd k nobr z
e1 16 np w0 l0 r : vmovlhps r:x, v:x, R:x ; nobr nok noz
e1 16 np w0 l0 m : vmovhps r:x, v:x, M:/q ; nobm nok noz
e1 17 np w0 l0 m : vmovhps M:/q, r:x ; nobm nok novvvv noz
e1 28 np w0 : vmovaps r:X, m:X ; k nobm nobr novvvv z
e1 29 np w0 r : vmovaps R:X, r:X ; k nobr novvvv z
e1 29 np w0 m : vmovaps M:/X, r:X ; k nobm novvvv noz
e1 2b np w0 m : vmovntps M:/X, r:X ; nobm nok novvvv noz
e1 2e np w0 : vucomiss r:x, m:x/d, rc ; nobm nok novvvv noz sae
e1 2f np w0 : vcomiss r:x, m:x/d, rc ; nobm nok novvvv noz sae
e1 51 np w0 : vsqrtps r:X, m:X, rc ; bd er k novvvv z
e1 54 np w0 : vandps r:X, v:X, m:X ; bd k nobr z
e1 55 np w0 : vandnps r:X, v:X, m:X ; bd k nobr z
e1 56 np w0 : vorps r:X, v:X, m:X ; bd k nobr z
e1 57 np w0 : vxorps r:X, v:X, m:X ; bd k nobr z
e1 58 np w0 : vaddps r:X, v:X, m:X, rc ; bd er k z
e1 59 np w0 : vmulps r:X, v:X, m:X, rc ; bd er k z
e1 5a np w0 : vcvtps2pd r:X, m:Xh, rc ; bd k novvvv sae z
e1 5b np w0 : vcvtdq2ps r:X, m:X, rc ; bd er k novvvv z
e1 5b np w1 : vcvtqq2ps r:Xh, m:X, rc ; bq er k novvvv z
e1 5c np w0 : vsubps r:X, v:X, m:X, rc ; bd er k z
e1 5d np w0 : vminps r:X, v:X, m:X, rc ; bd k sae z
e1 5e np w0 : vdivps r:X, v:X, m:X, rc ; bd er k z
e1 5f np w0 : vmaxps r:X, v:X, m:X, rc ; bd k sae z
e1 78 np w0 : vcvttps2udq r:X, m:X, rc ; bd k novvvv sae z
e1 78 np w1 : vcvttpd2udq r:Xh, m:X, rc ; bq k novvvv sae z
e1 79 np w0 : vcvtps2udq r:X, m:X, rc ; bd er k novvvv z
e1 79 np w1 : vcvtpd2udq r:Xh, m:X, rc ; bq er k novvvv z
e1 c2 np w0 : vcmpps r:k, v:X, m:X, rc, i:b ; bd k noz sae cmp32
e1 c6 np w0 : vshufps r:X, v:X, m:X, i:b ; bd k nobr z
e1 10 66 w1 : vmovupd r:X, m:X ; k nobm nobr novvvv z
e1 11 66 w1 r : vmovupd R:X, r:X ; k nobr novvvv z
e1 11 66 w1 m : vmovupd M:/X, r:X ; k nobm novvvv noz
e1 12 66 w1 l0 m : vmovlpd r:x, v:x, M:/q ; nobm nok noz
e1 13 66 w1 l0 m : vmovlpd M:/q, r:x ; nobm nok novvvv noz
e1 14 66 w1 : vunpcklpd r:X, v:X, m:X ; bq k nobr z
e1 15 66 w1 : vunpckhpd r:X, v:X, m:X ; bq k nobr z
e1 16 66 w1 l0 m : vmovhpd r:x, v:x, M:/q ; nobm nok noz
e1 17 66 w1 l0 m : vmovhpd M:/q, r:x ; nobm nok novvvv noz
e1 28 66 w1 : vmovapd r:X, m:X ; k nobm nobr novvvv z
e1 29 66 w1 r : vmovapd R:X, r:X ; k nobr novvvv z
e1 29 66 w1 m : vmovapd M:/X, r:X ; k nobm novvvv noz
e1 2b 66 w1 m : vmovntpd M:/X, r:X ; nobm nok novvvv noz
e1 2e 66 w1 : vucomisd r:x, m:x/q, rc ; nobm nok novvvv noz sae
e1 2f 66 w1 : vcomisd r:x, m:x/q, rc ; nobm nok novvvv noz sae
e1 51 66 w1 : vsqrtpd r:X, m:X, rc ; bq er k novvvv z
e1 54 66 w1 : vandpd r:X, v:X, m:X ; bq k nobr z
e1 55 66 w1 : vandnpd r:X, v:X, m:X ; bq k nobr z
e1 56 66 w1 : vorpd r:X, v:X, m:X ; bq k nobr z
e1 57 66 w1 : vxorpd r:X, v:X, m:X ; bq k nobr z
e1 58 66 w1 : vaddpd r:X, v:X, m:X, rc ; bq er k z
e1 59 66 w1 : vmulpd r:X, v:X, m:X, rc ; bq er k z
e1 5a 66 w1 : vcvtpd2ps r:Xh, m:X, rc ; bq er k novvvv z
e1 5b 66 w0 : vcvtps2dq r:X, m:X, rc ; bd er k novvvv z
e1 5c 66 w1 : vsubpd r:X, v:X, m:X, rc ; bq er k z
e1 5d 66 w1 : vminpd r:X, v:X, m:X, rc ; bq k sae z
e1 5e 66 w1 : vdivpd r:X, v:X, m:X, rc ; bq er k z
e1 5f 66 w1 : vmaxpd r:X, v:X, m:X, rc ; bq k sae z
e1 60 66 : vpunpcklbw r:X, v:X, m:X ; k nobm nobr z
e1 61 66 : vpunpcklwd r:X, v:X, m:X ; k nobm nobr z
e1 62 66 w0 : vpunpckldq r:X, v:X, m:X ; bd k nobr z
e1 63 66 : vpacksswb r:X, v:X, m:X ; k nobm nobr z
e1 64 66 : vpcmpgtb r:k, v:X, m:X ; k nobm nobr noz
e1 65 66 : vpcmpgtw r:k, v:X, m:X ; k nobm nobr noz
e1 66 66 w0 : vpcmpgtd r:k, v:X, m:X ; bd k nobr noz
e1 67 66 : vpackuswb r:X, v:X, m:X ; k nobm nobr z
e1 68 66 : vpunpckhbw r:X, v:X, m:X ; k nobm nobr z
e1 69 66 : vpunpckhwd r:X, v:X, m:X ; k nobm nobr z
e1 6a 66 w0 : vpunpckhdq r:X, v:X, m:X ; bd k nobr z
e1 6b 66 w0 : vpackssdw r:X, v:X, m:X ; bd k nobr z
e1 6c 66 w1 : vpunpcklqdq r:X, v:X, m:X ; bq k nobr z
e1 6d 66 w1 : vpunpckhqdq r:X, v:X, m:X ; bq k nobr z
e1 6e 66 mode32 l0 : vmovd r:x, m:d ; nobm nobr nok novvvv noz
e1 6f 66 mode32 : vmovdqa32 r:X, m:X ; k nobm nobr novvvv z
e1 70 66 w0 : vpshufd r:X, m:X, i:b ; bd k nobr novvvv z
e1 71 66 /2 : vpsrlw v:X, m:X, i:b ; k nobm nobr z
e1 71 66 /4 : vpsraw v:X, m:X, i:b ; k nobm nobr z
e1 71 66 /6 : vpsllw v:X, m:X, i:b ; k nobm nobr z
e1 72 66 w0 /0 : vprord v:X, m:X, i:b ; bd k nobr z
e1 72 66 w0 /1 : vprold v:X, m:X, i:b ; bd k nobr z
e1 72 66 w0 /2 : vpsrld v:X, m:X, i:b ; bd k nobr z
e1 72 66 w0 /4 : vpsrad v:X, m:X, i:b ; bd k nobr z
e1 72 66 w0 /6 : vpslld v:X, m:X, i:b ; bd k nobr z
e1 72 66 w1 /0 : vprorq v:X, m:X, i:b ; bq k nobr z
e1 72 66 w1 /1 : vprolq v:X, m:X, i:b ; bq k nobr z
e1 72 66 w1 /4 : vpsraq v:X, m:X, i:b ; bq k nobr z
e1 73 66 /3 : vpsrldq v:X, m:X, i:b ; nobm nobr nok noz
e1 73 66 /7 : vpslldq v:X, m:X, i:b ; nobm nobr nok noz
e1 73 66 w1 /2 : vpsrlq v:X, m:X, i:b ; bq k nobr z
e1 73 66 w1 /6 : vpsllq v:X, m:X, i:b ; bq k nobr z
e1 74 66 : vpcmpeqb r:k, v:X, m:X ; k nobm nobr noz
e1 75 66 : vpcmpeqw r:k, v:X, m:X ; k nobm nobr noz
e1 76 66 w0 : vpcmpeqd r:k, v:X, m:X ; bd k nobr noz
e1 78 66 w0 : vcvttps2uqq r:X, m:Xh, rc ; bd k novvvv sae z
e1 78 66 w1 : vcvttpd2uqq r:X, m:X, rc ; bq k novvvv sae z
e1 79 66 w0 : vcvtps2uqq r:X, m:Xh, rc ; bd er k novvvv z
e1 79 66 w1 : vcvtpd2uqq r:X, m:X, rc ; bq er k novvvv z
e1 7a 66 w0 : vcvttps2qq r:X, m:Xh, rc ; bd k novvvv sae z
e1 7a 66 w1 : vcvttpd2qq r:X, m:X, rc ; bq k novvvv sae z
e1 7b 66 w0 : vcvtps2qq r:X, m:Xh, rc ; bd er k novvvv z
e1 7b 66 w1 : vcvtpd2qq r:X, m:X, rc ; bq er k novvvv z
e1 7e 66 mode32 l0 : vmovd m:d, r:x ; nobm nobr nok novvvv noz
e1 7f 66 mode32 r : vmovdqa32 R:X, r:X ; k nobr novvvv z
e1 7f 66 mode32 m : vmovdqa32 M:/X, r:X ; k nobm novvvv noz
e1 c2 66 w1 : vcmppd r:k, v:X, m:X, rc, i:b ; bq k noz sae cmp32
e1 c4 66 l0 : vpinsrw r:x, v:x, m:d/w, i:b ; nobm nobr nok noz
e1 c5 66 l0 r : vpextrw r:d, R:x, i:b ; nobr nok novvvv noz
e1 c6 66 w1 : vshufpd r:X, v:X, m:X, i:b ; bq k nobr z
e1 d1 66 w0 : vpsrlw r:X, v:X, m:x ; k nobm nobr z
e1 d2 66 w0 : vpsrld r:X, v:X, m:x ; k nobm nobr z
e1 d3 66 w1 : vpsrlq r:X, v:X, m:x ; k nobm nobr z
e1 d4 66 w1 : vpaddq r:X, v:X, m:X ; bq k nobr z
e1 d5 66 : vpmullw r:X, v:X, m:X ; k nobm nobr z
e1 d6 66 w1 l0 : vmovq m:x/q, r:x ; nobm nobr nok novvvv noz
e1 d8 66 : vpsubusb r:X, v:X, m:X ; k nobm nobr z
e1 d9 66 : vpsubusw r:X, v:X, m:X ; k nobm nobr z
e1 da 66 : vpminub r:X, v:X, m:X ; k nobm nobr z
e1 db 66 w0 : vpandd r:X, v:X, m:X ; bd k nobr z
e1 db 66 w1 : vpandq r:X, v:X, m:X ; bq k nobr z
e1 dc 66 : vpaddusb r:X, v:X, m:X ; k nobm nobr z
e1 dd 66 : vpaddusw r:X, v:X, m:X ; k nobm nobr z
e1 de 66 : vpmaxub r:X, v:X, m:X ; k nobm nobr z
e1 df 66 w0 : vpandnd r:X, v:X, m:X ; bd k nobr z
e1 df 66 w1 : vpandnq r:X, v:X, m:X ; bq k nobr z
e1 e0 66 : vpavgb r:X, v:X, m:X ; k nobm nobr z
e1 e1 66 w0 : vpsraw r:X, v:X, m:x ; k nobm nobr z
e1 e2 66 w0 : vpsrad r:X, v:X, m:x ; k nobm nobr z
e1 e2 66 w1 : vpsraq r:X, v:X, m:x ; k nobm nobr z
e1 e3 66 : vpavgw r:X, v:X, m:X ; k nobm nobr z
e1 e4 66 : vpmulhuw r:X, v:X, m:X ; k nobm nobr z
e1 e5 66 : vpmulhw r:X, v:X, m:X ; k nobm nobr z
e1 e6 66 w1 : vcvttpd2dq r:Xh, m:X, rc ; bq k novvvv sae z
e1 e7 66 w0 m : vmovntdq M:/X, r:X ; nobm nok novvvv noz
e1 e8 66 : vpsubsb r:X, v:X, m:X ; k nobm nobr z
e1 e9 66 : vpsubsw r:X, v:X, m:X ; k nobm nobr z
e1 ea 66 : vpminsw r:X, v:X, m:X ; k nobm nobr z
e1 eb 66 w0 : vpord r:X, v:X, m:X ; bd k nobr z
e1 eb 66 w1 : vporq r:X, v:X, m:X ; bq k nobr z
e1 ec 66 : vpaddsb r:X, v:X, m:X ; k nobm nobr z
e1 ed 66 : vpaddsw r:X, v:X, m:X ; k nobm nobr z
e1 ee 66 : vpmaxsw r:X, v:X, m:X ; k nobm nobr z
e1 ef 66 w0 : vpxord r:X, v:X, m:X ; bd k nobr z
e1 ef 66 w1 : vpxorq r:X, v:X, m:X ; bq k nobr z
e1 f1 66 w0 : vpsllw r:X, v:X, m:x ; k nobm nobr z
e1 f2 66 w0 : vpslld r:X, v:X, m:x ; k nobm nobr z
e1 f3 66 w1 : vpsllq r:X, v:X, m:x ; k nobm nobr z
e1 f4 66 w1 : vpmuludq r:X, v:X, m:X ; bq k nobr z
e1 f5 66 : vpmaddwd r:X, v:X, m:X ; k nobm nobr z
e1 f6 66 : vpsadbw r:X, v:X, m:X ; nobm nobr nok noz
e1 f8 66 : vpsubb r:X, v:X, m:X ; k nobm nobr z
e1 f9 66 : vpsubw r:X, v:X, m:X ; k nobm nobr z
e1 fa 66 w0 : vpsubd r:X, v:X, m:X ; bd k nobr z
e1 fb 66 w1 : vpsubq r:X, v:X, m:X ; bq k nobr z
e1 fc 66 : vpaddb r:X, v:X, m:X ; k nobm nobr z
e1 fd 66 : vpaddw r:X, v:X, m:X ; k nobm nobr z
e1 fe 66 w0 : vpaddd r:X, v:X, m:X ; bd k nobr z
e1 10 f3 w0 r : vmovss r:x, v:x, R:x ; k nobr z
e1 10 f3 w0 m : vmovss r:x, M:/d ; k nobm novvvv z
e1 11 f3 w0 r : vmovss R:x, v:x, r:x ; k nobr z
e1 11 f3 w0 m : vmovss M:/d, r:x ; k nobm novvvv noz
e1 12 f3 w0 : vmovsldup r:X, m:X ; k nobm nobr novvvv z
e1 16 f3 w0 : vmovshdup r:X, m:X ; k nobm nobr novvvv z
e1 2a f3 mode32 : vcvtsi2ss r:x, v:x, rc, m:d ; er nobm nok noz
e1 2c f3 mode32 : vcvttss2si r:d, m:x/d, rc ; nobm nok novvvv noz sae
e1 2d f3 mode32 : vcvtss2si r:d, m:x/d, rc ; er nobm nok novvvv noz
e1 51 f3 w0 : vsqrtss r:x, v:x, m:x/d, rc ; er k nobm z
e1 58 f3 w0 : vaddss r:x, v:x, m:x/d, rc ; er k nobm z
e1 59 f3 w0 : vmulss r:x, v:x, m:x/d, rc ; er k nobm z
e1 5a f3 w0 : vcvtss2sd r:x, v:x, m:x/d, rc ; k nobm sae z
e1 5b f3 w0 : vcvttps2dq r:X, m:X, rc ; bd k novvvv sae z
e1 5c f3 w0 : vsubss r:x, v:x, m:x/d, rc ; er k nobm z
e1 5d f3 w0 : vminss r:x, v:x, m:x/d, rc ; k nobm sae z
e1 5e f3 w0 : vdivss r:x, v:x, m:x/d, rc ; er k nobm z
e1 5f f3 w0 : vmaxss r:x, v:x, m:x/d, rc ; k nobm sae z
e1 6f f3 mode32 : vmovdqu32 r:X, m:X ; k nobm nobr novvvv z
e1 70 f3 : vpshufhw r:X, m:X, i:b ; k nobm nobr novvvv z
e1 78 f3 mode32 : vcvttss2usi r:d, m:x/d, rc ; nobm nok novvvv noz sae
e1 79 f3 mode32 : vcvtss2usi r:d, m:x/d, rc ; er nobm nok novvvv noz
e1 7a f3 w0 : vcvtudq2pd r:X, m:Xh ; bd k nobr novvvv z
e1 7a f3 w1 : vcvtuqq2pd r:X, m:X, rc ; bq er k novvvv z
e1 7b f3 mode32 : vcvtusi2ss r:x, v:x, rc, m:d ; er nobm nok noz
e1 7e f3 w1 l0 : vmovq r:x, m:x/q ; nobm nobr nok novvvv noz
e1 7f f3 mode32 r : vmovdqu32 R:X, r:X ; k nobr novvvv z
e1 7f f3 mode32 m : vmovdqu32 M:/X, r:X ; k nobm novvvv noz
e1 c2 f3 w0 l0 : vcmpss r:k, v:x, m:x/d, rc, i:b ; k nobm noz sae cmp32
e1 e6 f3 w0 : vcvtdq2pd r:X, m:Xh ; bd k nobr novvvv z
e1 e6 f3 w1 : vcvtqq2pd r:X, m:X, rc ; bq er k novvvv z
e1 10 f2 w1 r : vmovsd r:x, v:x, R:x ; k nobr z
e1 10 f2 w1 m : vmovsd r:x, M:/q ; k nobm novvvv z
e1 11 f2 w1 r : vmovsd R:x, v:x, r:x ; k nobr z
e1 11 f2 w1 m : vmovsd M:/q, r:x ; k nobm novvvv noz
e1 12 f2 w1 l1 : vmovddup r:ymm, m:ymm ; k nobm nobr novvvv z
e1 12 f2 w1 l2|l3 : vmovddup r:zmm, m:zmm ; k nobm nobr novvvv z
e1 12 f2 w1 l0 : vmovddup r:x, m:x/q ; k nobm nobr novvvv z
e1 2a f2 mode32 : vcvtsi2sd r:x, v:x, rc, m:d ; er nobm nok noz
e1 2c f2 mode32 : vcvttsd2si r:d, m:x/q, rc ; nobm nok novvvv noz sae
e1 2d f2 mode32 : vcvtsd2si r:d, m:x/q, rc ; er nobm nok novvvv noz
e1 51 f2 w1 : vsqrtsd r:x, v:x, m:x/q, rc ; er k nobm z
e1 58 f2 w1 : vaddsd r:x, v:x, m:x/q, rc ; er k nobm z
e1 59 f2 w1 : vmulsd r:x, v:x, m:x/q, rc ; er k nobm z
e1 5a f2 w1 : vcvtsd2ss r:x, v:x, m:x/q, rc ; er k nobm z
e1 5c f2 w1 : vsubsd r:x, v:x, m:x/q, rc ; er k nobm z
e1 5d f2 w1 : vminsd r:x, v:x, m:x/q, rc ; k nobm sae z
e1 5e f2 w1 : vdivsd r:x, v:x, m:x/q, rc ; er k nobm z
e1 5f f2 w1 : vmaxsd r:x, v:x, m:x/q, rc ; k nobm sae z
e1 6f f2 w0 : vmovdqu8 r:X, m:X ; k nobm nobr novvvv z
e1 6f f2 w1 : vmovdqu16 r:X, m:X ; k nobm nobr novvvv z
e1 70 f2 : vpshuflw r:X, m:X, i:b ; k nobm nobr novvvv z
e1 78 f2 mode32 : vcvttsd2usi r:d, m:x/q, rc ; nobm nok novvvv noz sae
e1 79 f2 mode32 : vcvtsd2usi r:d, m:x/q, rc ; er nobm nok novvvv noz
e1 7a f2 w0 : vcvtudq2ps r:X, m:X, rc ; bd er k novvvv z
e1 7a f2 w1 : vcvtuqq2ps r:Xh, m:X, rc ; bq er k novvvv z
e1 7b f2 mode32 : vcvtusi2sd r:x, v:x, m:d ; nobm nobr nok noz
e1 7f f2 w0 r : vmovdqu8 R:X, r:X ; k nobr novvvv z
e1 7f f2 w0 m : vmovdqu8 M:/X, r:X ; k nobm novvvv noz
e1 7f f2 w1 r : vmovdqu16 R:X, r:X ; k nobr novvvv z
e1 7f f2 w1 m : vmovdqu16 M:/X, r:X ; k nobm novvvv noz
e1 c2 f2 w1 l0 : vcmpsd r:k, v:x, m:x/q, rc, i:b ; k nobm noz sae cmp32
e1 e6 f2 w1 : vcvtpd2dq r:Xh, m:X, rc ; bq er k novvvv z
e2 00 66 : vpshufb r:X, v:X, m:X ; k nobm nobr z
e2 04 66 : vpmaddubsw r:X, v:X, m:X ; k nobm nobr z
e2 0b 66 : vpmulhrsw r:X, v:X, m:X ; k nobm nobr z
e2 0c 66 w0 : vpermilps r:X, v:X, m:X ; bd k nobr z
e2 0d 66 w1 : vpermilpd r:X, v:X, m:X ; bq k nobr z
e2 10 66 w1 : vpsrlvw r:X, v:X, m:X ; k nobm nobr z
e2 11 66 w1 : vpsravw r:X, v:X, m:X ; k nobm nobr z
e2 12 66 w1 : vpsllvw r:X, v:X, m:X ; k nobm nobr z
e2 13 66 w0 : vcvtph2ps r:X, m:Xh, rc ; k nobm novvvv sae z
e2 14 66 w0 : vprorvd r:X, v:X, m:X ; bd k nobr z
e2 14 66 w1 : vprorvq r:X, v:X, m:X ; bq k nobr z
e2 15 66 w0 : vprolvd r:X, v:X, m:X ; bd k nobr z
e2 15 66 w1 : vprolvq r:X, v:X, m:X ; bq k nobr z
e2 16 66 w0 l1 : vpermps r:ymm, v:ymm, m:ymm ; bd k nobr z
e2 16 66 w0 l2|l3 : vpermps r:zmm, v:zmm, m:zmm ; bd k nobr z
e2 16 66 w1 l1 : vpermpd r:ymm, v:ymm, m:ymm ; bq k nobr z
e2 16 66 w1 l2|l3 : vpermpd r:zmm, v:zmm, m:zmm ; bq k nobr z
e2 18 66 w0 : vbroadcastss r:X, m:x/d ; k nobm nobr novvvv z
e2 19 66 w0 l1 : vbroadcastf32x2 r:ymm, m:x/q ; k nobm nobr novvvv z
e2 19 66 w0 l2|l3 : vbroadcastf32x2 r:zmm, m:x/q ; k nobm nobr novvvv z
e2 19 66 w1 l1 : vbroadcastsd r:ymm, m:x/q ; k nobm nobr novvvv z
e2 19 66 w1 l2|l3 : vbroadcastsd r:zmm, m:x/q ; k nobm nobr novvvv z
e2 1a 66 mode32 l1 m : vbroadcastf32x4 r:ymm, M:/x ; k nobm novvvv z
e2 1a 66 mode32 l2|l3 m : vbroadcastf32x4 r:zmm, M:/x ; k nobm novvvv z
e2 1b 66 mode32 l2|l3 m : vbroadcastf32x8 r:zmm, M:/ymm ; k nobm novvvv z
e2 1c 66 : vpabsb r:X, m:X ; k nobm nobr novvvv z
e2 1d 66 : vpabsw r:X, m:X ; k nobm nobr novvvv z
e2 1e 66 w0 : vpabsd r:X, m:X ; bd k nobr novvvv z
e2 1f 66 w1 : vpabsq r:X, m:X ; bq k nobr novvvv z
e2 20 66 : vpmovsxbw r:X, m:Xh ; k nobm nobr novvvv z
e2 21 66 : vpmovsxbd r:X, m:x/Xq ; k nobm nobr novvvv z
e2 22 66 : vpmovsxbq r:X, m:x/Xe ; k nobm nobr novvvv z
e2 23 66 : vpmovsxwd r:X, m:Xh ; k nobm nobr novvvv z
e2 24 66 : vpmovsxwq r:X, m:x/Xq ; k nobm nobr novvvv z
e2 25 66 w0 : vpmovsxdq r:X, m:Xh ; k nobm nobr novvvv z
e2 26 66 w0 : vptestmb r:k, v:X, m:X ; k nobm nobr noz
e2 26 66 w1 : vptestmw r:k, v:X, m:X ; k nobm nobr noz
e2 27 66 w0 : vptestmd r:k, v:X, m:X ; bd k nobr noz
e2 27 66 w1 : vptestmq r:k, v:X, m:X ; bq k nobr noz
e2 28 66 w1 : vpmuldq r:X, v:X, m:X ; bq k nobr z
e2 29 66 w1 : vpcmpeqq r:k, v:X, m:X ; bq k nobr noz
e2 2a 66 w0 m : vmovntdqa r:X, M:/X ; nobm nok novvvv noz
e2 2b 66 w0 : vpackusdw r:X, v:X, m:X ; bd k nobr z
e2 2c 66 w0 : vscalefps r:X, v:X, m:X, rc ; bd er k z
e2 2c 66 w1 : vscalefpd r:X, v:X, m:X, rc ; bq er k z
e2 2d 66 w1 l0 : vscalefsd r:x, v:x, m:x/q, rc ; er k nobm z
e2 2d 66 w0 l0 : vscalefss r:x, v:x, m:x/d, rc ; er k nobm z
e2 30 66 : vpmovzxbw r:X, m:Xh ; k nobm nobr novvvv z
e2 31 66 : vpmovzxbd r:X, m:x/Xq ; k nobm nobr novvvv z
e2 32 66 : vpmovzxbq r:X, m:x/Xe ; k nobm nobr novvvv z
e2 33 66 : vpmovzxwd r:X, m:Xh ; k nobm nobr novvvv z
e2 34 66 : vpmovzxwq r:X, m:x/Xq ; k nobm nobr novvvv z
e2 35 66 w0 : vpmovzxdq r:X, m:Xh ; k nobm nobr novvvv z
e2 36 66 w0 l1 : vpermd r:ymm, v:ymm, m:ymm ; bd k nobr z
e2 36 66 w0 l2|l3 : vpermd r:zmm, v:zmm, m:zmm ; bd k nobr z
e2 36 66 w1 l1 : vpermq r:ymm, v:ymm, m:ymm ; bq k nobr z
e2 36 66 w1 l2|l3 : vpermq r:zmm, v:zmm, m:zmm ; bq k nobr z
e2 37 66 w1 : vpcmpgtq r:k, v:X, m:X ; bq k nobr noz
e2 38 66 : vpminsb r:X, v:X, m:X ; k nobm nobr z
e2 39 66 w0 : vpminsd r:X, v:X, m:X ; bd k nobr z
e2 39 66 w1 : vpminsq r:X, v:X, m:X ; bq k nobr z
e2 3a 66 : vpminuw r:X, v:X, m:X ; k nobm nobr z
e2 3b 66 w0 : vpminud r:X, v:X, m:X ; bd k nobr z
e2 3b 66 w1 : vpminuq r:X, v:X, m:X ; bq k nobr z
e2 3c 66 : vpmaxsb r:X, v:X, m:X ; k nobm nobr z
e2 3d 66 w0 : vpmaxsd r:X, v:X, m:X ; bd k nobr z
e2 3d 66 w1 : vpmaxsq r:X, v:X, m:X ; bq k nobr z
e2 3e 66 : vpmaxuw r:X, v:X, m:X ; k nobm nobr z
e2 3f 66 w0 : vpmaxud r:X, v:X, m:X ; bd k nobr z
e2 3f 66 w1 : vpmaxuq r:X, v:X, m:X ; bq k nobr z
e2 40 66 w0 : vpmulld r:X, v:X, m:X ; bd k nobr z
e2 40 66 w1 : vpmullq r:X, v:X, m:X ; bq k nobr z
e2 42 66 w0 : vgetexpps r:X, m:X, rc ; bd k novvvv sae z
e2 42 66 w1 : vgetexppd r:X, m:X, rc ; bq k novvvv sae z
e2 43 66 w0 l0 : vgetexpss r:x, v:x, m:x/d, rc ; k nobm sae z
e2 43 66 w1 l0 : vgetexpsd r:x, v:x, m:x/q, rc ; k nobm sae z
e2 44 66 w0 : vplzcntd r:X, m:X ; bd k nobr novvvv z
e2 44 66 w1 : vplzcntq r:X, m:X ; bq k nobr novvvv z
e2 45 66 w0 : vpsrlvd r:X, v:X, m:X ; bd k nobr z
e2 45 66 w1 : vpsrlvq r:X, v:X, m:X ; bq k nobr z
e2 46 66 w0 : vpsravd r:X, v:X, m:X ; bd k nobr z
e2 46 66 w1 : vpsravq r:X, v:X, m:X ; bq k nobr z
e2 47 66 w0 : vpsllvd r:X, v:X, m:X ; bd k nobr z
e2 47 66 w1 : vpsllvq r:X, v:X, m:X ; bq k nobr z
e2 4c 66 w0 : vrcp14ps r:X, m:X ; bd k nobr novvvv z
e2 4c 66 w1 : vrcp14pd r:X, m:X ; bq k nobr novvvv z
e2 4d 66 w0 l0 : vrcp14ss r:x, v:x, m:x/d ; k nobm nobr z
e2 4d 66 w1 l0 : vrcp14sd r:x, v:x, m:x/q ; k nobm nobr z
e2 4e 66 w0 : vrsqrt14ps r:X, m:X ; bd k nobr novvvv z
e2 4e 66 w1 : vrsqrt14pd r:X, m:X ; bq k nobr novvvv z
e2 4f 66 w0 l0 : vrsqrt14ss r:x, v:x, m:x/d ; k nobm nobr z
e2 4f 66 w1 l0 : vrsqrt14sd r:x, v:x, m:x/q ; k nobm nobr z
e2 50 66 w0 : vpdpbusd r:X, v:X, m:X ; bd k nobr z
e2 51 66 w0 : vpdpbusds r:X, v:X, m:X ; bd k nobr z
e2 52 66 w0 : vpdpwssd r:X, v:X, m:X ; bd k nobr z
e2 53 66 w0 : vpdpwssds r:X, v:X, m:X ; bd k nobr z
e2 54 66 w0 : vpopcntb r:X, m:X ; k nobm nobr novvvv z
e2 54 66 w1 : vpopcntw r:X, m:X ; k nobm nobr novvvv z
e2 55 66 w0 : vpopcntd r:X, m:X ; bd k nobr novvvv z
e2 55 66 w1 : vpopcntq r:X, m:X ; bq k nobr novvvv z
e2 58 66 w0 : vpbroadcastd r:X, m:x/d ; k nobm nobr novvvv z
e2 59 66 w0 : vbroadcasti32x2 r:X, m:x/q ; k nobm nobr novvvv z
e2 59 66 w1 : vpbroadcastq r:X, m:x/q ; k nobm nobr novvvv z
e2 5a 66 mode32 l2|l3 m : vbroadcasti32x4 r:zmm, M:/x ; k nobm novvvv z
e2 5a 66 mode32 l1 m : vbroadcasti32x4 r:ymm, M:/x ; k nobm novvvv z
e2 5b 66 mode32 l2|l3 m : vbroadcasti32x8 r:zmm, M:/ymm ; k nobm novvvv z
e2 62 66 w0 r : vpexpandb r:X, R:X ; k nobr novvvv z
e2 62 66 w0 m : vpexpandb r:X, M:/X ; k n1 nobm novvvv z
e2 62 66 w1 r : vpexpandw r:X, R:X ; k nobr novvvv z
e2 62 66 w1 m : vpexpandw r:X, M:/X ; k n2 nobm novvvv z
e2 63 66 w0 r : vpcompressb R:X, r:X ; k nobr novvvv z
e2 63 66 w0 m : vpcompressb M:/X, r:X ; k n1 nobm novvvv noz
e2 63 66 w1 r : vpcompressw R:X, r:X ; k nobr novvvv z
e2 63 66 w1 m : vpcompressw M:/X, r:X ; k n2 nobm novvvv noz
e2 64 66 w0 : vpblendmd r:X, v:X, m:X ; bd k nobr z
e2 64 66 w1 : vpblendmq r:X, v:X, m:X ; bq k nobr z
e2 65 66 w0 : vblendmps r:X, v:X, m:X ; bd k nobr z
e2 65 66 w1 : vblendmpd r:X, v:X, m:X ; bq k nobr z
e2 66 66 w0 : vpblendmb r:X, v:X, m:X ; k nobm nobr z
e2 66 66 w1 : vpblendmw r:X, v:X, m:X ; k nobm nobr z
e2 70 66 w1 : vpshldvw r:X, v:X, m:X ; k nobm nobr z
e2 71 66 w0 : vpshldvd r:X, v:X, m:X ; bd k nobr z
e2 71 66 w1 : vpshldvq r:X, v:X, m:X ; bq k nobr z
e2 72 66 w1 : vpshrdvw r:X, v:X, m:X ; k nobm nobr z
e2 73 66 w0 : vpshrdvd r:X, v:X, m:X ; bd k nobr z
e2 73 66 w1 : vpshrdvq r:X, v:X, m:X ; bq k nobr z
e2 75 66 w0 : vpermi2b r:X, v:X, m:X ; k nobm nobr z
e2 75 66 w1 : vpermi2w r:X, v:X, m:X ; k nobm nobr z
e2 76 66 w0 : vpermi2d r:X, v:X, m:X ; bd k nobr z
e2 76 66 w1 : vpermi2q r:X, v:X, m:X ; bq k nobr z
e2 77 66 w0 : vpermi2ps r:X, v:X, m:X ; bd k nobr z
e2 77 66 w1 : vpermi2pd r:X, v:X, m:X ; bq k nobr z
e2 78 66 w0 : vpbroadcastb r:X, m:x/b ; k nobm nobr novvvv z
e2 79 66 w0 : vpbroadcastw r:X, m:x/w ; k nobm nobr novvvv z
e2 7a 66 w0 r : vpbroadcastb r:X, R:d ; k nobr novvvv z
e2 7b 66 w0 r : vpbroadcastw r:X, R:d ; k nobr novvvv z
e2 7c 66 w0 r : vpbroadcastd r:X, R:d ; k nobr novvvv z
e2 7c 66 w1 r : vpbroadcastq r:X, R:q ; k nobr novvvv z
e2 7d 66 w0 : vpermt2b r:X, v:X, m:X ; k nobm nobr z
e2 7d 66 w1 : vpermt2w r:X, v:X, m:X ; k nobm nobr z
e2 7e 66 w0 : vpermt2d r:X, v:X, m:X ; bd k nobr z
e2 7e 66 w1 : vpermt2q r:X, v:X, m:X ; bq k nobr z
e2 7f 66 w0 : vpermt2ps r:X, v:X, m:X ; bd k nobr z
e2 7f 66 w1 : vpermt2pd r:X, v:X, m:X ; bq k nobr z
e2 83 66 w1 : vpmultishiftqb r:X, v:X, m:X ; bq k nobr z
e2 88 66 w0 r : vexpandps r:X, R:X ; k nobr novvvv z
e2 88 66 w0 m : vexpandps r:X, M:/X ; k n4 nobm novvvv z
e2 88 66 w1 r : vexpandpd r:X, R:X ; k nobr novvvv z
e2 88 66 w1 m : vexpandpd r:X, M:/X ; k n8 nobm novvvv z
e2 89 66 w0 r : vpexpandd r:X, R:X ; k nobr novvvv z
e2 89 66 w0 m : vpexpandd r:X, M:/X ; k n4 nobm novvvv z
e2 89 66 w1 r : vpexpandq r:X, R:X ; k nobr novvvv z
e2 89 66 w1 m : vpexpandq r:X, M:/X ; k n8 nobm novvvv z
e2 8a 66 w0 r : vcompressps R:X, r:X ; k nobr novvvv z
e2 8a 66 w0 m : vcompressps M:/X, r:X ; k n4 nobm novvvv noz
e2 8a 66 w1 r : vcompresspd R:X, r:X ; k nobr novvvv z
e2 8a 66 w1 m : vcompresspd M:/X, r:X ; k n8 nobm novvvv noz
e2 8b 66 w0 r : vpcompressd R:X, r:X ; k nobr novvvv z
e2 8b 66 w0 m : vpcompressd M:/X, r:X ; k n4 nobm novvvv noz
e2 8b 66 w1 r : vpcompressq R:X, r:X ; k nobr novvvv z
e2 8b 66 w1 m : vpcompressq M:/X, r:X ; k n8 nobm novvvv noz
e2 8d 66 w0 : vpermb r:X, v:X, m:X ; k nobm nobr z
e2 8d 66 w1 : vpermw r:X, v:X, m:X ; k nobm nobr z
e2 8f 66 w0 : vpshufbitqmb r:k, v:X, m:X ; k nobm nobr noz
e2 90 66 w0 m : vpgatherdd r:X, Vs:X/X ; k knz n4 novvvv noz
e2 90 66 w1 m : vpgatherdq r:X, Vs:Xh/X ; k knz n8 novvvv noz
e2 91 66 w0 m : vpgatherqd r:Xh, Vs:X/Xh ; k knz n4 novvvv noz
e2 91 66 w1 m : vpgatherqq r:X, Vs:X/X ; k knz n8 novvvv noz
e2 92 66 w0 m : vgatherdps r:X, Vs:X/X ; k knz n4 novvvv noz
e2 92 66 w1 m : vgatherdpd r:X, Vs:Xh/X ; k knz n8 novvvv noz
e2 93 66 w0 m : vgatherqps r:Xh, Vs:X/Xh ; k knz n4 novvvv noz
e2 93 66 w1 m : vgatherqpd r:X, Vs:X/X ; k knz n8 novvvv noz
e2 96 66 w0 : vfmaddsub132ps r:X, v:X, m:X, rc ; bd er k z
e2 96 66 w1 : vfmaddsub132pd r:X, v:X, m:X, rc ; bq er k z
e2 97 66 w0 : vfmsubadd132ps r:X, v:X, m:X, rc ; bd er k z
e2 97 66 w1 : vfmsubadd132pd r:X, v:X, m:X, rc ; bq er k z
e2 98 66 w0 : vfmadd132ps r:X, v:X, m:X, rc ; bd er k z
e2 98 66 w1 : vfmadd132pd r:X, v:X, m:X, rc ; bq er k z
e2 99 66 w0 : vfmadd132ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 99 66 w1 : vfmadd132sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 9a 66 w0 : vfmsub132ps r:X, v:X, m:X, rc ; bd er k z
e2 9a 66 w1 : vfmsub132pd r:X, v:X, m:X, rc ; bq er k z
e2 9b 66 w0 : vfmsub132ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 9b 66 w1 : vfmsub132sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 9c 66 w0 : vfnmadd132ps r:X, v:X, m:X, rc ; bd er k z
e2 9c 66 w1 : vfnmadd132pd r:X, v:X, m:X, rc ; bq er k z
e2 9d 66 w0 : vfnmadd132ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 9d 66 w1 : vfnmadd132sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 9e 66 w0 : vfnmsub132ps r:X, v:X, m:X, rc ; bd er k z
e2 9e 66 w1 : vfnmsub132pd r:X, v:X, m:X, rc ; bq er k z
e2 9f 66 w0 : vfnmsub132ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 9f 66 w1 : vfnmsub132sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 a0 66 w0 m : vpscatterdd Vs:X/X, r:X ; k knz n4 novvvv noz
e2 a0 66 w1 m : vpscatterdq Vs:Xh/X, r:X ; k knz n8 novvvv noz
e2 a1 66 w0 m : vpscatterqd Vs:X/Xh, r:Xh ; k knz n4 novvvv noz
e2 a1 66 w1 m : vpscatterqq Vs:X/X, r:X ; k knz n8 novvvv noz
e2 a2 66 w0 m : vscatterdps Vs:X/X, r:X ; k knz n4 novvvv noz
e2 a2 66 w1 m : vscatterdpd Vs:Xh/X, r:X ; k knz n8 novvvv noz
e2 a3 66 w0 m : vscatterqps Vs:X/Xh, r:Xh ; k knz n4 novvvv noz
e2 a3 66 w1 m : vscatterqpd Vs:X/X, r:X ; k knz n8 novvvv noz
e2 a6 66 w0 : vfmaddsub213ps r:X, v:X, m:X, rc ; bd er k z
e2 a6 66 w1 : vfmaddsub213pd r:X, v:X, m:X, rc ; bq er k z
e2 a7 66 w0 : vfmsubadd213ps r:X, v:X, m:X, rc ; bd er k z
e2 a7 66 w1 : vfmsubadd213pd r:X, v:X, m:X, rc ; bq er k z
e2 a8 66 w0 : vfmadd213ps r:X, v:X, m:X, rc ; bd er k z
e2 a8 66 w1 : vfmadd213pd r:X, v:X, m:X, rc ; bq er k z
e2 a9 66 w0 : vfmadd213ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 a9 66 w1 : vfmadd213sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 aa 66 w0 : vfmsub213ps r:X, v:X, m:X, rc ; bd er k z
e2 aa 66 w1 : vfmsub213pd r:X, v:X, m:X, rc ; bq er k z
e2 ab 66 w0 : vfmsub213ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 ab 66 w1 : vfmsub213sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 ac 66 w0 : vfnmadd213ps r:X, v:X, m:X, rc ; bd er k z
e2 ac 66 w1 : vfnmadd213pd r:X, v:X, m:X, rc ; bq er k z
e2 ad 66 w0 : vfnmadd213ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 ad 66 w1 : vfnmadd213sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 ae 66 w0 : vfnmsub213ps r:X, v:X, m:X, rc ; bd er k z
e2 ae 66 w1 : vfnmsub213pd r:X, v:X, m:X, rc ; bq er k z
e2 af 66 w0 : vfnmsub213ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 af 66 w1 : vfnmsub213sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 b4 66 w1 : vpmadd52luq r:X, v:X, m:X ; bq k nobr z
e2 b5 66 w1 : vpmadd52huq r:X, v:X, m:X ; bq k nobr z
e2 b6 66 w0 : vfmaddsub231ps r:X, v:X, m:X, rc ; bd er k z
e2 b6 66 w1 : vfmaddsub231pd r:X, v:X, m:X, rc ; bq er k z
e2 b7 66 w0 : vfmsubadd231ps r:X, v:X, m:X, rc ; bd er k z
e2 b7 66 w1 : vfmsubadd231pd r:X, v:X, m:X, rc ; bq er k z
e2 b8 66 w0 : vfmadd231ps r:X, v:X, m:X, rc ; bd er k z
e2 b8 66 w1 : vfmadd231pd r:X, v:X, m:X, rc ; bq er k z
e2 b9 66 w0 : vfmadd231ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 b9 66 w1 : vfmadd231sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 ba 66 w0 : vfmsub231ps r:X, v:X, m:X, rc ; bd er k z
e2 ba 66 w1 : vfmsub231pd r:X, v:X, m:X, rc ; bq er k z
e2 bb 66 w0 : vfmsub231ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 bb 66 w1 : vfmsub231sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 bc 66 w0 : vfnmadd231ps r:X, v:X, m:X, rc ; bd er k z
e2 bc 66 w1 : vfnmadd231pd r:X, v:X, m:X, rc ; bq er k z
e2 bd 66 w0 : vfnmadd231ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 bd 66 w1 : vfnmadd231sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 be 66 w0 : vfnmsub231ps r:X, v:X, m:X, rc ; bd er k z
e2 be 66 w1 : vfnmsub231pd r:X, v:X, m:X, rc ; bq er k z
e2 bf 66 w0 : vfnmsub231ss r:x, v:x, m:x/d, rc ; er k nobm z
e2 bf 66 w1 : vfnmsub231sd r:x, v:x, m:x/q, rc ; er k nobm z
e2 c4 66 w0 : vpconflictd r:X, m:X ; bd k nobr novvvv z
e2 c4 66 w1 : vpconflictq r:X, m:X ; bq k nobr novvvv z
e2 c6 66 w0 l2|l3 /1 m : vgatherpf0dps kmask, Vs:zmm/zmm ; k knz n4 novvvv noz
e2 c6 66 w0 l2|l3 /2 m : vgatherpf1dps kmask, Vs:zmm/zmm ; k knz n4 novvvv noz
e2 c6 66 w0 l2|l3 /5 m : vscatterpf0dps kmask, Vs:zmm/zmm ; k knz n4 novvvv noz
e2 c6 66 w0 l2|l3 /6 m : vscatterpf1dps kmask, Vs:zmm/zmm ; k knz n4 novvvv noz
e2 c6 66 w1 l2|l3 /1 m : vgatherpf0dpd kmask, Vs:ymm/zmm ; k knz n4 novvvv noz
e2 c6 66 w1 l2|l3 /2 m : vgatherpf1dpd kmask, Vs:ymm/zmm ; k knz n4 novvvv noz
e2 c6 66 w1 l2|l3 /5 m : vscatterpf0dpd kmask, Vs:ymm/zmm ; k knz n4 novvvv noz
e2 c6 66 w1 l2|l3 /6 m : vscatterpf1dpd kmask, Vs:ymm/zmm ; k knz n4 novvvv noz
e2 c7 66 w0 l2|l3 /1 m : vgatherpf0qps kmask, Vs:zmm/ymm ; k knz n8 novvvv noz
e2 c7 66 w0 l2|l3 /2 m : vgatherpf1qps kmask, Vs:zmm/ymm ; k knz n8 novvvv noz
e2 c7 66 w0 l2|l3 /5 m : vscatterpf0qps kmask, Vs:zmm/ymm ; k knz n8 novvvv noz
e2 c7 66 w0 l2|l3 /6 m : vscatterpf1qps kmask, Vs:zmm/ymm ; k knz n8 novvvv noz
e2 c7 66 w1 l2|l3 /1 m : vgatherpf0qpd kmask, Vs:zmm/zmm ; k knz n8 novvvv noz
e2 c7 66 w1 l2|l3 /2 m : vgatherpf1qpd kmask, Vs:zmm/zmm ; k knz n8 novvvv noz
e2 c7 66 w1 l2|l3 /5 m : vscatterpf0qpd kmask, Vs:zmm/zmm ; k knz n8 novvvv noz
e2 c7 66 w1 l2|l3 /6 m : vscatterpf1qpd kmask, Vs:zmm/zmm ; k knz n8 novvvv noz
e2 c8 66 w0 l2|l3 : vexp2ps r:zmm, m:zmm, rc ; bd k novvvv sae z
e2 c8 66 w1 l2|l3 : vexp2pd r:zmm, m:zmm, rc ; bq k novvvv sae z
e2 ca 66 w0 l2|l3 : vrcp28ps r:zmm, m:zmm, rc ; bd k novvvv sae z
e2 ca 66 w1 l2|l3 : vrcp28pd r:zmm, m:zmm, rc ; bq k novvvv sae z
e2 cb 66 w0 l0 : vrcp28ss r:x, v:x, m:x/d, rc ; k nobm sae z
e2 cb 66 w1 l0 : vrcp28sd r:x, v:x, m:x/q, rc ; k nobm sae z
e2 cc 66 w0 l2|l3 : vrsqrt28ps r:zmm, m:zmm, rc ; bd k novvvv sae z
e2 cc 66 w1 l2|l3 : vrsqrt28pd r:zmm, m:zmm, rc ; bq k novvvv sae z
e2 cd 66 w0 l0 : vrsqrt28ss r:x, v:x, m:x/d, rc ; k nobm sae z
e2 cd 66 w1 l0 : vrsqrt28sd r:x, v:x, m:x/q, rc ; k nobm sae z
e2 cf 66 w0 : vgf2p8mulb r:X, v:X, m:X ; k nobm nobr z
e2 dc 66 : vaesenc r:X, v:X, m:X ; nobm nobr nok noz
e2 dd 66 : vaesenclast r:X, v:X, m:X ; nobm nobr nok noz
e2 de 66 : vaesdec r:X, v:X, m:X ; nobm nobr nok noz
e2 df 66 : vaesdeclast r:X, v:X, m:X ; nobm nobr nok noz
e2 10 f3 w0 r : vpmovuswb R:Xh, r:X ; k nobr novvvv z
e2 10 f3 w0 m : vpmovuswb M:/Xh, r:X ; k nobm novvvv noz
e2 11 f3 w0 r : vpmovusdb R:x, r:X ; k nobr novvvv z
e2 11 f3 w0 m : vpmovusdb M:/Xq, r:X ; k nobm novvvv noz
e2 12 f3 w0 r : vpmovusqb R:x, r:X ; k nobr novvvv z
e2 12 f3 w0 m : vpmovusqb M:/Xe, r:X ; k nobm novvvv noz
e2 13 f3 w0 r : vpmovusdw R:Xh, r:X ; k nobr novvvv z
e2 13 f3 w0 m : vpmovusdw M:/Xh, r:X ; k nobm novvvv noz
e2 14 f3 w0 r : vpmovusqw R:x, r:X ; k nobr novvvv z
e2 14 f3 w0 m : vpmovusqw M:/Xq, r:X ; k nobm novvvv noz
e2 15 f3 w0 r : vpmovusqd R:Xh, r:X ; k nobr novvvv z
e2 15 f3 w0 m : vpmovusqd M:/Xh, r:X ; k nobm novvvv noz
e2 20 f3 w0 r : vpmovswb R:Xh, r:X ; k nobr novvvv z
e2 20 f3 w0 m : vpmovswb M:/Xh, r:X ; k nobm novvvv noz
e2 21 f3 w0 r : vpmovsdb R:x, r:X ; k nobr novvvv z
e2 21 f3 w0 m : vpmovsdb M:/Xq, r:X ; k nobm novvvv noz
e2 22 f3 w0 r : vpmovsqb R:x, r:X ; k nobr novvvv z
e2 22 f3 w0 m : vpmovsqb M:/Xe, r:X ; k nobm novvvv noz
e2 23 f3 w0 r : vpmovsdw R:Xh, r:X ; k nobr novvvv z
e2 23 f3 w0 m : vpmovsdw M:/Xh, r:X ; k nobm novvvv noz
e2 24 f3 w0 r : vpmovsqw R:x, r:X ; k nobr novvvv z
e2 24 f3 w0 m : vpmovsqw M:/Xq, r:X ; k nobm novvvv noz
e2 25 f3 w0 r : vpmovsqd R:Xh, r:X ; k nobr novvvv z
e2 25 f3 w0 m : vpmovsqd M:/Xh, r:X ; k nobm novvvv noz
e2 26 f3 w0 : vptestnmb r:k, v:X, m:X ; k nobm nobr noz
e2 26 f3 w1 : vptestnmw r:k, v:X, m:X ; k nobm nobr noz
e2 27 f3 w0 : vptestnmd r:k, v:X, m:X ; bd k nobr noz
e2 27 f3 w1 : vptestnmq r:k, v:X, m:X ; bq k nobr noz
e2 28 f3 w0 r : vpmovm2b r:X, R:k ; nobr nok novvvv noz
e2 28 f3 w1 r : vpmovm2w r:X, R:k ; nobr nok novvvv noz
e2 29 f3 w0 r : vpmovb2m r:k, R:X ; nobr nok novvvv noz
e2 29 f3 w1 r : vpmovw2m r:k, R:X ; nobr nok novvvv noz
e2 2a f3 w1 r : vpbroadcastmb2q r:X, R:k ; nobr nok novvvv noz
e2 30 f3 w0 r : vpmovwb R:Xh, r:X ; k nobr novvvv z
e2 30 f3 w0 m : vpmovwb M:/Xh, r:X ; k nobm novvvv noz
e2 31 f3 w0 r : vpmovdb R:x, r:X ; k nobr novvvv z
e2 31 f3 w0 m : vpmovdb M:/Xq, r:X ; k nobm novvvv noz
e2 32 f3 w0 r : vpmovqb R:x, r:X ; k nobr novvvv z
e2 32 f3 w0 m : vpmovqb M:/Xe, r:X ; k nobm novvvv noz
e2 33 f3 w0 r : vpmovdw R:Xh, r:X ; k nobr novvvv z
e2 33 f3 w0 m : vpmovdw M:/Xh, r:X ; k nobm novvvv noz
e2 34 f3 w0 r : vpmovqw R:x, r:X ; k nobr novvvv z
e2 34 f3 w0 m : vpmovqw M:/Xq, r:X ; k nobm novvvv noz
e2 35 f3 w0 r : vpmovqd R:Xh, r:X ; k nobr novvvv z
e2 35 f3 w0 m : vpmovqd M:/Xh, r:X ; k nobm novvvv noz
e2 38 f3 w0 r : vpmovm2d r:X, R:k ; nobr nok novvvv noz
e2 38 f3 w1 r : vpmovm2q r:X, R:k ; nobr nok novvvv noz
e2 39 f3 w0 r : vpmovd2m r:k, R:X ; nobr nok novvvv noz
e2 39 f3 w1 r : vpmovq2m r:k, R:X ; nobr nok novvvv noz
e2 3a f3 w0 r : vpbroadcastmw2d r:X, R:k ; nobr nok novvvv noz
e2 52 f2 w0 l2|l3 m : vp4dpwssd r:zmm, v:zmm, M:/x ; k nobm z
e2 53 f2 w0 l2|l3 m : vp4dpwssds r:zmm, v:zmm, M:/x ; k nobm z
e2 9a f2 w0 l2|l3 m : v4fmaddps r:zmm, v:zmm, M:/x ; k nobm z
e2 9b f2 w0 l0 m : v4fmaddss r:x, v:x, M:/x ; k nobm z
e2 aa f2 w0 l2|l3 m : v4fnmaddps r:zmm, v:zmm, M:/x ; k nobm z
e2 ab f2 w0 l0 m : v4fnmaddss r:x, v:x, M:/x ; k nobm z
e3 00 66 w1 l2|l3 : vpermq r:zmm, m:zmm, i:b ; bq k nobr novvvv z
e3 00 66 w1 l1 : vpermq r:ymm, m:ymm, i:b ; bq k nobr novvvv z
e3 01 66 w1 l2|l3 : vpermpd r:zmm, m:zmm, i:b ; bq k nobr novvvv z
e3 01 66 w1 l1 : vpermpd r:ymm, m:ymm, i:b ; bq k nobr novvvv z
e3 03 66 w0 : valignd r:X, v:X, m:X, i:b ; bd k nobr z
e3 03 66 w1 : valignq r:X, v:X, m:X, i:b ; bq k nobr z
e3 04 66 w0 : vpermilps r:X, m:X, i:b ; bd k nobr novvvv z
e3 05 66 w1 : vpermilpd r:X, m:X, i:b ; bq k nobr novvvv z
e3 08 66 w0 : vrndscaleps r:X, m:X, rc, i:b ; bd k novvvv sae z
e3 09 66 w1 : vrndscalepd r:X, m:X, rc, i:b ; bq k novvvv sae z
e3 0a 66 w0 l0 : vrndscaless r:x, v:x, m:x/d, rc, i:b ; k nobm sae z
e3 0b 66 w1 l0 : vrndscalesd r:x, v:x, m:x/q, rc, i:b ; k nobm sae z
e3 0f 66 w0 : vpalignr r:X, v:X, m:X, i:b ; k nobm nobr z
e3 14 66 l0 : vpextrb m:d/b, r:x, i:b ; nobm nobr nok novvvv noz
e3 15 66 l0 : vpextrw m:d/w, r:x, i:b ; nobm nobr nok novvvv noz
e3 16 66 w0 l0 : vpextrd m:d, r:x, i:b ; nobm nobr nok novvvv noz
e3 16 66 w1 l0 : vpextrq m:q, r:x, i:b ; nobm nobr nok novvvv noz
e3 17 66 l0 : vextractps m:d, r:x, i:b ; nobm nobr nok novvvv noz
e3 18 66 mode32 l1 : vinsertf32x4 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 18 66 mode32 l2|l3 : vinsertf32x4 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 19 66 mode32 l1 r : vextractf32x4 R:x, r:ymm, i:b ; k nobr novvvv z
e3 19 66 mode32 l1 m : vextractf32x4 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 19 66 mode32 l2|l3 r : vextractf32x4 R:x, r:zmm, i:b ; k nobr novvvv z
e3 19 66 mode32 l2|l3 m : vextractf32x4 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 1a 66 mode32 l2|l3 : vinsertf32x8 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 1b 66 mode32 l2|l3 r : vextractf32x8 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 1b 66 mode32 l2|l3 m : vextractf32x8 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 1d 66 w0 r : vcvtps2ph R:Xh, r:X, rc, i:b ; k novvvv sae z
e3 1d 66 w0 m : vcvtps2ph M:/Xh, r:X, i:b ; k nobm novvvv noz
e3 1e 66 w0 : vpcmpud r:k, v:X, m:X, i:b ; bd k nobr noz
e3 1e 66 w1 : vpcmpuq r:k, v:X, m:X, i:b ; bq k nobr noz
e3 1f 66 w0 : vpcmpd r:k, v:X, m:X, i:b ; bd k nobr noz
e3 1f 66 w1 : vpcmpq r:k, v:X, m:X, i:b ; bq k nobr noz
e3 20 66 l0 : vpinsrb r:x, v:x, m:d/b, i:b ; nobm nobr nok noz
e3 21 66 w0 l0 : vinsertps r:x, v:x, m:x/d, i:b ; nobm nobr nok noz
e3 22 66 w0 l0 : vpinsrd r:x, v:x, m:d, i:b ; nobm nobr nok noz
e3 22 66 w1 l0 : vpinsrq r:x, v:x, m:q, i:b ; nobm nobr nok noz
e3 23 66 mode32 l1 : vshuff32x4 r:ymm, v:ymm, m:ymm, i:b ; bd k nobr z
e3 23 66 mode32 l2|l3 : vshuff32x4 r:zmm, v:zmm, m:zmm, i:b ; bd k nobr z
e3 25 66 w0 : vpternlogd r:X, v:X, m:X, i:b ; bd k nobr z
e3 25 66 w1 : vpternlogq r:X, v:X, m:X, i:b ; bq k nobr z
e3 26 66 w0 : vgetmantps r:X, m:X, rc, i:b ; bd k novvvv sae z
e3 26 66 w1 : vgetmantpd r:X, m:X, rc, i:b ; bq k novvvv sae z
e3 27 66 w0 : vgetmantss r:x, v:x, m:x/d, rc, i:b ; k nobm sae z
e3 27 66 w1 : vgetmantsd r:x, v:x, m:x/q, rc, i:b ; k nobm sae z
e3 38 66 mode32 l1 : vinserti32x4 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 38 66 mode32 l2|l3 : vinserti32x4 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 39 66 mode32 l1 r : vextracti32x4 R:x, r:ymm, i:b ; k nobr novvvv z
e3 39 66 mode32 l1 m : vextracti32x4 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 39 66 mode32 l2|l3 r : vextracti32x4 R:x, r:zmm, i:b ; k nobr novvvv z
e3 39 66 mode32 l2|l3 m : vextracti32x4 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 3a 66 mode32 l2|l3 : vinserti32x8 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 3b 66 mode32 l2|l3 r : vextracti32x8 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 3b 66 mode32 l2|l3 m : vextracti32x8 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 3e 66 w0 : vpcmpub r:k, v:X, m:X, i:b ; k nobm nobr noz
e3 3e 66 w1 : vpcmpuw r:k, v:X, m:X, i:b ; k nobm nobr noz
e3 3f 66 w0 : vpcmpb r:k, v:X, m:X, i:b ; k nobm nobr noz
e3 3f 66 w1 : vpcmpw r:k, v:X, m:X, i:b ; k nobm nobr noz
e3 42 66 w0 : vdbpsadbw r:X, v:X, m:X, i:b ; k nobm nobr z
e3 43 66 mode32 l1 : vshufi32x4 r:ymm, v:ymm, m:ymm, i:b ; bd k nobr z
e3 43 66 mode32 l2|l3 : vshufi32x4 r:zmm, v:zmm, m:zmm, i:b ; bd k nobr z
e3 44 66 : vpclmulqdq r:X, v:X, m:X, i:b ; nobm nobr nok noz
e3 50 66 w0 : vrangeps r:X, v:X, m:X, rc, i:b ; bd k sae z
e3 50 66 w1 : vrangepd r:X, v:X, m:X, rc, i:b ; bq k sae z
e3 51 66 w0 : vrangess r:x, v:x, m:x/d, rc, i:b ; k nobm sae z
e3 51 66 w1 : vrangesd r:x, v:x, m:x/q, rc, i:b ; k nobm sae z
e3 54 66 w0 : vfixupimmps r:X, v:X, m:X, rc, i:b ; bd k sae z
e3 54 66 w1 : vfixupimmpd r:X, v:X, m:X, rc, i:b ; bq k sae z
e3 55 66 w0 : vfixupimmss r:x, v:x, m:x/d, rc, i:b ; k nobm sae z
e3 55 66 w1 : vfixupimmsd r:x, v:x, m:x/q, rc, i:b ; k nobm sae z
e3 56 66 w0 : vreduceps r:X, m:X, rc, i:b ; bd k novvvv sae z
e3 56 66 w1 : vreducepd r:X, m:X, rc, i:b ; bq k novvvv sae z
e3 57 66 w0 : vreducess r:x, v:x, m:x/d, rc, i:b ; k nobm sae z
e3 57 66 w1 : vreducesd r:x, v:x, m:x/q, rc, i:b ; k nobm sae z
e3 66 66 w0 : vfpclassps r:k, m:X, i:b ; bd k nobr novvvv noz
e3 66 66 w1 : vfpclasspd r:k, m:X, i:b ; bq k nobr novvvv noz
e3 67 66 w0 l0 : vfpclassss r:k, m:x/d, i:b ; k nobm nobr novvvv noz
e3 67 66 w1 l0 : vfpclasssd r:k, m:x/q, i:b ; k nobm nobr novvvv noz
e3 70 66 w1 : vpshldw r:X, v:X, m:X, i:b ; k nobm nobr z
e3 71 66 w0 : vpshldd r:X, v:X, m:X, i:b ; bd k nobr z
e3 71 66 w1 : vpshldq r:X, v:X, m:X, i:b ; bq k nobr z
e3 72 66 w1 : vpshrdw r:X, v:X, m:X, i:b ; k nobm nobr z
e3 73 66 w0 : vpshrdd r:X, v:X, m:X, i:b ; bd k nobr z
e3 73 66 w1 : vpshrdq r:X, v:X, m:X, i:b ; bq k nobr z
e3 ce 66 w1 r : vgf2p8affineqb r:X, v:X, R:X, i:b ; k nobr z
e3 ce 66 w1 m : vgf2p8affineqb r:X, v:X, M:/X, i:b ; bqb k z
e3 cf 66 w1 r : vgf2p8affineinvqb r:X, v:X, R:X, i:b ; k nobr z
e3 cf 66 w1 m : vgf2p8affineinvqb r:X, v:X, M:/X, i:b ; bqb k z
e1 6e 66 mode64 w0 l0 : vmovd r:x, m:d ; nobm nobr nok novvvv noz
e1 6e 66 mode64 w1 l0 : vmovq r:x, m:q ; nobm nobr nok novvvv noz
e1 6f 66 mode64 w0 : vmovdqa32 r:X, m:X ; k nobm nobr novvvv z
e1 6f 66 mode64 w1 : vmovdqa64 r:X, m:X ; k nobm nobr novvvv z
e1 7e 66 mode64 w0 l0 : vmovd m:d, r:x ; nobm nobr nok novvvv noz
e1 7e 66 mode64 w1 l0 r : vmovq R:q, r:x ; nobr nok novvvv noz
e1 7e 66 mode64 w1 l0 m : vmovq M:/q, r:x ; n16 nobm nok novvvv noz
e1 7f 66 mode64 w0 r : vmovdqa32 R:X, r:X ; k nobr novvvv z
e1 7f 66 mode64 w0 m : vmovdqa32 M:/X, r:X ; k nobm novvvv noz
e1 7f 66 mode64 w1 r : vmovdqa64 R:X, r:X ; k nobr novvvv z
e1 7f 66 mode64 w1 m : vmovdqa64 M:/X, r:X ; k nobm novvvv noz
e1 2a f3 mode64 w0 : vcvtsi2ss r:x, v:x, rc, m:d ; er nobm nok noz
e1 2a f3 mode64 w1 : vcvtsi2ss r:x, v:x, rc, m:q ; er nobm nok noz
e1 2c f3 mode64 w0 : vcvttss2si r:d, m:x/d, rc ; nobm nok novvvv noz sae
e1 2c f3 mode64 w1 : vcvttss2si r:q, m:x/d, rc ; nobm nok novvvv noz sae
e1 2d f3 mode64 w0 : vcvtss2si r:d, m:x/d, rc ; er nobm nok novvvv noz
e1 2d f3 mode64 w1 : vcvtss2si r:q, m:x/d, rc ; er nobm nok novvvv noz
e1 6f f3 mode64 w0 : vmovdqu32 r:X, m:X ; k nobm nobr novvvv z
e1 6f f3 mode64 w1 : vmovdqu64 r:X, m:X ; k nobm nobr novvvv z
e1 78 f3 mode64 w0 : vcvttss2usi r:d, m:x/d, rc ; nobm nok novvvv noz sae
e1 78 f3 mode64 w1 : vcvttss2usi r:q, m:x/d, rc ; nobm nok novvvv noz sae
e1 79 f3 mode64 w0 : vcvtss2usi r:d, m:x/d, rc ; er nobm nok novvvv noz
e1 79 f3 mode64 w1 : vcvtss2usi r:q, m:x/d, rc ; er nobm nok novvvv noz
e1 7b f3 mode64 w0 : vcvtusi2ss r:x, v:x, rc, m:d ; er nobm nok noz
e1 7b f3 mode64 w1 : vcvtusi2ss r:x, v:x, rc, m:q ; er nobm nok noz
e1 7f f3 mode64 w0 r : vmovdqu32 R:X, r:X ; k nobr novvvv z
e1 7f f3 mode64 w0 m : vmovdqu32 M:/X, r:X ; k nobm novvvv noz
e1 7f f3 mode64 w1 r : vmovdqu64 R:X, r:X ; k nobr novvvv z
e1 7f f3 mode64 w1 m : vmovdqu64 M:/X, r:X ; k nobm novvvv noz
e1 2a f2 mode64 w0 : vcvtsi2sd r:x, v:x, rc, m:d ; er nobm nok noz
e1 2a f2 mode64 w1 : vcvtsi2sd r:x, v:x, rc, m:q ; er nobm nok noz
e1 2c f2 mode64 w0 : vcvttsd2si r:d, m:x/q, rc ; nobm nok novvvv noz sae
e1 2c f2 mode64 w1 : vcvttsd2si r:q, m:x/q, rc ; nobm nok novvvv noz sae
e1 2d f2 mode64 w0 : vcvtsd2si r:d, m:x/q, rc ; er nobm nok novvvv noz
e1 2d f2 mode64 w1 : vcvtsd2si r:q, m:x/q, rc ; er nobm nok novvvv noz
e1 78 f2 mode64 w0 : vcvttsd2usi r:d, m:x/q, rc ; nobm nok novvvv noz sae
e1 78 f2 mode64 w1 : vcvttsd2usi r:q, m:x/q, rc ; nobm nok novvvv noz sae
e1 79 f2 mode64 w0 : vcvtsd2usi r:d, m:x/q, rc ; er nobm nok novvvv noz
e1 79 f2 mode64 w1 : vcvtsd2usi r:q, m:x/q, rc ; er nobm nok novvvv noz
e1 7b f2 mode64 w0 : vcvtusi2sd r:x, v:x, m:d ; nobm nobr nok noz
e1 7b f2 mode64 w1 : vcvtusi2sd r:x, v:x, rc, m:q ; er nobm nok noz
e2 1a 66 mode64 w0 l1 m : vbroadcastf32x4 r:ymm, M:/x ; k nobm novvvv z
e2 1a 66 mode64 w1 l2|l3 m : vbroadcastf64x2 r:zmm, M:/x ; k nobm novvvv z
e2 1a 66 mode64 w0 l2|l3 m : vbroadcastf32x4 r:zmm, M:/x ; k nobm novvvv z
e2 1a 66 mode64 w1 l1 m : vbroadcastf64x2 r:ymm, M:/x ; k nobm novvvv z
e2 1b 66 mode64 w1 l2|l3 m : vbroadcastf64x4 r:zmm, M:/ymm ; k nobm novvvv z
e2 1b 66 mode64 w0 l2|l3 m : vbroadcastf32x8 r:zmm, M:/ymm ; k nobm novvvv z
e2 5a 66 mode64 w0 l1 m : vbroadcasti32x4 r:ymm, M:/x ; k nobm novvvv z
e2 5a 66 mode64 w0 l2|l3 m : vbroadcasti32x4 r:zmm, M:/x ; k nobm novvvv z
e2 5a 66 mode64 w1 l1 m : vbroadcasti64x2 r:ymm, M:/x ; k nobm novvvv z
e2 5a 66 mode64 w1 l2|l3 m : vbroadcasti64x2 r:zmm, M:/x ; k nobm novvvv z
e2 5b 66 mode64 w0 l2|l3 m : vbroadcasti32x8 r:zmm, M:/ymm ; k nobm novvvv z
e2 5b 66 mode64 w1 l2|l3 m : vbroadcasti64x4 r:zmm, M:/ymm ; k nobm novvvv z
e3 18 66 mode64 w0 l1 : vinsertf32x4 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 18 66 mode64 w0 l2|l3 : vinsertf32x4 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 18 66 mode64 w1 l1 : vinsertf64x2 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 18 66 mode64 w1 l2|l3 : vinsertf64x2 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 19 66 mode64 w0 l1 r : vextractf32x4 R:x, r:ymm, i:b ; k nobr novvvv z
e3 19 66 mode64 w0 l1 m : vextractf32x4 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 19 66 mode64 w0 l2|l3 r : vextractf32x4 R:x, r:zmm, i:b ; k nobr novvvv z
e3 19 66 mode64 w0 l2|l3 m : vextractf32x4 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 19 66 mode64 w1 l1 r : vextractf64x2 R:x, r:ymm, i:b ; k nobr novvvv z
e3 19 66 mode64 w1 l1 m : vextractf64x2 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 19 66 mode64 w1 l2|l3 r : vextractf64x2 R:x, r:zmm, i:b ; k nobr novvvv z
e3 19 66 mode64 w1 l2|l3 m : vextractf64x2 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 1a 66 mode64 w0 l2|l3 : vinsertf32x8 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 1a 66 mode64 w1 l2|l3 : vinsertf64x4 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 1b 66 mode64 w0 l2|l3 r : vextractf32x8 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 1b 66 mode64 w0 l2|l3 m : vextractf32x8 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 1b 66 mode64 w1 l2|l3 r : vextractf64x4 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 1b 66 mode64 w1 l2|l3 m : vextractf64x4 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 23 66 mode64 w0 l1 : vshuff32x4 r:ymm, v:ymm, m:ymm, i:b ; bd k nobr z
e3 23 66 mode64 w0 l2|l3 : vshuff32x4 r:zmm, v:zmm, m:zmm, i:b ; bd k nobr z
e3 23 66 mode64 w1 l1 : vshuff64x2 r:ymm, v:ymm, m:ymm, i:b ; bq k nobr z
e3 23 66 mode64 w1 l2|l3 : vshuff64x2 r:zmm, v:zmm, m:zmm, i:b ; bq k nobr z
e3 38 66 mode64 w0 l1 : vinserti32x4 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 38 66 mode64 w0 l2|l3 : vinserti32x4 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 38 66 mode64 w1 l1 : vinserti64x2 r:ymm, v:ymm, m:x, i:b ; k nobm nobr z
e3 38 66 mode64 w1 l2|l3 : vinserti64x2 r:zmm, v:zmm, m:x, i:b ; k nobm nobr z
e3 39 66 mode64 w0 l1 r : vextracti32x4 R:x, r:ymm, i:b ; k nobr novvvv z
e3 39 66 mode64 w0 l1 m : vextracti32x4 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 39 66 mode64 w0 l2|l3 r : vextracti32x4 R:x, r:zmm, i:b ; k nobr novvvv z
e3 39 66 mode64 w0 l2|l3 m : vextracti32x4 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 39 66 mode64 w1 l1 r : vextracti64x2 R:x, r:ymm, i:b ; k nobr novvvv z
e3 39 66 mode64 w1 l1 m : vextracti64x2 M:/x, r:ymm, i:b ; k nobm novvvv noz
e3 39 66 mode64 w1 l2|l3 r : vextracti64x2 R:x, r:zmm, i:b ; k nobr novvvv z
e3 39 66 mode64 w1 l2|l3 m : vextracti64x2 M:/x, r:zmm, i:b ; k nobm novvvv noz
e3 3a 66 mode64 w0 l2|l3 : vinserti32x8 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 3a 66 mode64 w1 l2|l3 : vinserti64x4 r:zmm, v:zmm, m:ymm, i:b ; k nobm nobr z
e3 3b 66 mode64 w0 l2|l3 r : vextracti32x8 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 3b 66 mode64 w0 l2|l3 m : vextracti32x8 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 3b 66 mode64 w1 l2|l3 r : vextracti64x4 R:ymm, r:zmm, i:b ; k nobr novvvv z
e3 3b 66 mode64 w1 l2|l3 m : vextracti64x4 M:/ymm, r:zmm, i:b ; k nobm novvvv noz
e3 43 66 mode64 w0 l2|l3 : vshufi32x4 r:zmm, v:zmm, m:zmm, i:b ; bd k nobr z
e3 43 66 mode64 w0 l1 : vshufi32x4 r:ymm, v:ymm, m:ymm, i:b ; bd k nobr z
e3 43 66 mode64 w1 l2|l3 : vshufi64x2 r:zmm, v:zmm, m:zmm, i:b ; bq k nobr z
e3 43 66 mode64 w1 l1 : vshufi64x2 r:ymm, v:ymm, m:ymm, i:b ; bq k nobr z
"#;
