//! VEX-encoded instructions (AVX, AVX2, FMA, BMI, F16C, ...).
//! GENERATED by bench/scripts/gen_vex_spec.py (capstone 5 probing); hand edits below the
//! marker line are preserved by the generator's caller only manually.

pub(crate) const SPEC: &str = r#"
v1 10 np l0 : vmovups r:x, m:x ; novvvv
v1 10 np l1 : vmovups r:ymm, m:ymm ; novvvv
v1 11 np l0 : vmovups m:x, r:x ; novvvv
v1 11 np l1 : vmovups m:ymm, r:ymm ; novvvv
v1 12 np l0 r : vmovhlps r:x, v:x, R:x
v1 12 np l0 m : vmovlps r:x, v:x, M:/q
v1 13 np l0 m : vmovlps M:/q, r:x ; novvvv
v1 14 np l0 : vunpcklps r:x, v:x, m:x
v1 14 np l1 : vunpcklps r:ymm, v:ymm, m:ymm
v1 15 np l0 : vunpckhps r:x, v:x, m:x
v1 15 np l1 : vunpckhps r:ymm, v:ymm, m:ymm
v1 16 np l0 r : vmovlhps r:x, v:x, R:x
v1 16 np l0 m : vmovhps r:x, v:x, M:/q
v1 17 np l0 m : vmovhps M:/q, r:x ; novvvv
v1 28 np l0 : vmovaps r:x, m:x ; novvvv
v1 28 np l1 : vmovaps r:ymm, m:ymm ; novvvv
v1 29 np l0 : vmovaps m:x, r:x ; novvvv
v1 29 np l1 : vmovaps m:ymm, r:ymm ; novvvv
v1 2b np l0 m : vmovntps M:/x, r:x ; novvvv
v1 2b np l1 m : vmovntps M:/ymm, r:ymm ; novvvv
v1 2e np : vucomiss r:x, m:x/d ; novvvv
v1 2f np : vcomiss r:x, m:x/d ; novvvv
v1 41 np w0 l1 r : kandw r:k, v:k, R:k
v1 41 np w1 l1 r : kandq r:k, v:k, R:k
v1 42 np w0 l1 r : kandnw r:k, v:k, R:k
v1 42 np w1 l1 r : kandnq r:k, v:k, R:k
v1 44 np w0 l0 r : knotw r:k, R:k ; novvvv
v1 44 np w1 l0 r : knotq r:k, R:k ; novvvv
v1 45 np w0 l1 r : korw r:k, v:k, R:k
v1 45 np w1 l1 r : korq r:k, v:k, R:k
v1 46 np w0 l1 r : kxnorw r:k, v:k, R:k
v1 46 np w1 l1 r : kxnorq r:k, v:k, R:k
v1 47 np w0 l1 r : kxorw r:k, v:k, R:k
v1 47 np w1 l1 r : kxorq r:k, v:k, R:k
v1 4a np w0 l1 r : kaddw r:k, v:k, R:k
v1 4a np w1 l1 r : kaddq r:k, v:k, R:k
v1 4b np w0 l1 r : kunpckwd r:k, v:k, R:k
v1 4b np w1 l1 r : kunpckdq r:k, v:k, R:k
v1 50 np l0 r : vmovmskps r:d, R:x ; novvvv
v1 50 np l1 r : vmovmskps r:d, R:ymm ; novvvv
v1 51 np l0 : vsqrtps r:x, m:x ; novvvv
v1 51 np l1 : vsqrtps r:ymm, m:ymm ; novvvv
v1 52 np l0 : vrsqrtps r:x, m:x ; novvvv
v1 52 np l1 : vrsqrtps r:ymm, m:ymm ; novvvv
v1 53 np l0 : vrcpps r:x, m:x ; novvvv
v1 53 np l1 : vrcpps r:ymm, m:ymm ; novvvv
v1 54 np l0 : vandps r:x, v:x, m:x
v1 54 np l1 : vandps r:ymm, v:ymm, m:ymm
v1 55 np l0 : vandnps r:x, v:x, m:x
v1 55 np l1 : vandnps r:ymm, v:ymm, m:ymm
v1 56 np l0 : vorps r:x, v:x, m:x
v1 56 np l1 : vorps r:ymm, v:ymm, m:ymm
v1 57 np l0 : vxorps r:x, v:x, m:x
v1 57 np l1 : vxorps r:ymm, v:ymm, m:ymm
v1 58 np l0 : vaddps r:x, v:x, m:x
v1 58 np l1 : vaddps r:ymm, v:ymm, m:ymm
v1 59 np l0 : vmulps r:x, v:x, m:x
v1 59 np l1 : vmulps r:ymm, v:ymm, m:ymm
v1 5a np l0 : vcvtps2pd r:x, m:x/q ; novvvv
v1 5a np l1 : vcvtps2pd r:ymm, m:x ; novvvv
v1 5b np l0 : vcvtdq2ps r:x, m:x ; novvvv
v1 5b np l1 : vcvtdq2ps r:ymm, m:ymm ; novvvv
v1 5c np l0 : vsubps r:x, v:x, m:x
v1 5c np l1 : vsubps r:ymm, v:ymm, m:ymm
v1 5d np l0 : vminps r:x, v:x, m:x
v1 5d np l1 : vminps r:ymm, v:ymm, m:ymm
v1 5e np l0 : vdivps r:x, v:x, m:x
v1 5e np l1 : vdivps r:ymm, v:ymm, m:ymm
v1 5f np l0 : vmaxps r:x, v:x, m:x
v1 5f np l1 : vmaxps r:ymm, v:ymm, m:ymm
v1 77 np l0 : vzeroupper ; novvvv
v1 77 np l1 : vzeroall ; novvvv
v1 90 np w0 l0 : kmovw r:k, m:k/w ; novvvv
v1 90 np w1 l0 : kmovq r:k, m:k/q ; novvvv
v1 91 np w0 l0 m : kmovw M:/w, r:k ; novvvv
v1 91 np w1 l0 m : kmovq M:/q, r:k ; novvvv
v1 92 np w0 l0 r : kmovw r:k, R:d ; novvvv
v1 93 np w0 l0 r : kmovw r:d, R:k ; novvvv
v1 98 np w0 l0 r : kortestw r:k, R:k ; novvvv
v1 98 np w1 l0 r : kortestq r:k, R:k ; novvvv
v1 99 np w0 l0 r : ktestw r:k, R:k ; novvvv
v1 99 np w1 l0 r : ktestq r:k, R:k ; novvvv
v1 ae np l0 /2 m : vldmxcsr M:/d ; novvvv
v1 ae np l0 /3 m : vstmxcsr M:/d ; novvvv
v1 c2 np l0 : vcmpps r:x, v:x, m:x, i:b ; cmp32
v1 c2 np l1 : vcmpps r:ymm, v:ymm, m:ymm, i:b ; cmp32
v1 c6 np l0 : vshufps r:x, v:x, m:x, i:b
v1 c6 np l1 : vshufps r:ymm, v:ymm, m:ymm, i:b
v1 10 66 l0 : vmovupd r:x, m:x ; novvvv
v1 10 66 l1 : vmovupd r:ymm, m:ymm ; novvvv
v1 11 66 l0 : vmovupd m:x, r:x ; novvvv
v1 11 66 l1 : vmovupd m:ymm, r:ymm ; novvvv
v1 12 66 l0 m : vmovlpd r:x, v:x, M:/q
v1 13 66 l0 m : vmovlpd M:/q, r:x ; novvvv
v1 14 66 l0 : vunpcklpd r:x, v:x, m:x
v1 14 66 l1 : vunpcklpd r:ymm, v:ymm, m:ymm
v1 15 66 l0 : vunpckhpd r:x, v:x, m:x
v1 15 66 l1 : vunpckhpd r:ymm, v:ymm, m:ymm
v1 16 66 l0 m : vmovhpd r:x, v:x, M:/q
v1 17 66 l0 m : vmovhpd M:/q, r:x ; novvvv
v1 28 66 l0 : vmovapd r:x, m:x ; novvvv
v1 28 66 l1 : vmovapd r:ymm, m:ymm ; novvvv
v1 29 66 l0 : vmovapd m:x, r:x ; novvvv
v1 29 66 l1 : vmovapd m:ymm, r:ymm ; novvvv
v1 2b 66 l0 m : vmovntpd M:/x, r:x ; novvvv
v1 2b 66 l1 m : vmovntpd M:/ymm, r:ymm ; novvvv
v1 2e 66 : vucomisd r:x, m:x/q ; novvvv
v1 2f 66 : vcomisd r:x, m:x/q ; novvvv
v1 41 66 w0 l1 r : kandb r:k, v:k, R:k
v1 41 66 w1 l1 r : kandd r:k, v:k, R:k
v1 42 66 w0 l1 r : kandnb r:k, v:k, R:k
v1 42 66 w1 l1 r : kandnd r:k, v:k, R:k
v1 44 66 w0 l0 r : knotb r:k, R:k ; novvvv
v1 44 66 w1 l0 r : knotd r:k, R:k ; novvvv
v1 45 66 w0 l1 r : korb r:k, v:k, R:k
v1 45 66 w1 l1 r : kord r:k, v:k, R:k
v1 46 66 w0 l1 r : kxnorb r:k, v:k, R:k
v1 46 66 w1 l1 r : kxnord r:k, v:k, R:k
v1 47 66 w0 l1 r : kxorb r:k, v:k, R:k
v1 47 66 w1 l1 r : kxord r:k, v:k, R:k
v1 4a 66 w0 l1 r : kaddb r:k, v:k, R:k
v1 4a 66 w1 l1 r : kaddd r:k, v:k, R:k
v1 4b 66 w0 l1 r : kunpckbw r:k, v:k, R:k
v1 50 66 l0 r : vmovmskpd r:d, R:x ; novvvv
v1 50 66 l1 r : vmovmskpd r:d, R:ymm ; novvvv
v1 51 66 l0 : vsqrtpd r:x, m:x ; novvvv
v1 51 66 l1 : vsqrtpd r:ymm, m:ymm ; novvvv
v1 54 66 l0 : vandpd r:x, v:x, m:x
v1 54 66 l1 : vandpd r:ymm, v:ymm, m:ymm
v1 55 66 l0 : vandnpd r:x, v:x, m:x
v1 55 66 l1 : vandnpd r:ymm, v:ymm, m:ymm
v1 56 66 l0 : vorpd r:x, v:x, m:x
v1 56 66 l1 : vorpd r:ymm, v:ymm, m:ymm
v1 57 66 l0 : vxorpd r:x, v:x, m:x
v1 57 66 l1 : vxorpd r:ymm, v:ymm, m:ymm
v1 58 66 l0 : vaddpd r:x, v:x, m:x
v1 58 66 l1 : vaddpd r:ymm, v:ymm, m:ymm
v1 59 66 l0 : vmulpd r:x, v:x, m:x
v1 59 66 l1 : vmulpd r:ymm, v:ymm, m:ymm
v1 5a 66 l0 : vcvtpd2ps r:x, m:x ; novvvv
v1 5a 66 l1 : vcvtpd2ps r:x, m:ymm ; novvvv
v1 5b 66 l0 : vcvtps2dq r:x, m:x ; novvvv
v1 5b 66 l1 : vcvtps2dq r:ymm, m:ymm ; novvvv
v1 5c 66 l0 : vsubpd r:x, v:x, m:x
v1 5c 66 l1 : vsubpd r:ymm, v:ymm, m:ymm
v1 5d 66 l0 : vminpd r:x, v:x, m:x
v1 5d 66 l1 : vminpd r:ymm, v:ymm, m:ymm
v1 5e 66 l0 : vdivpd r:x, v:x, m:x
v1 5e 66 l1 : vdivpd r:ymm, v:ymm, m:ymm
v1 5f 66 l0 : vmaxpd r:x, v:x, m:x
v1 5f 66 l1 : vmaxpd r:ymm, v:ymm, m:ymm
v1 60 66 l0 : vpunpcklbw r:x, v:x, m:x
v1 60 66 l1 : vpunpcklbw r:ymm, v:ymm, m:ymm
v1 61 66 l0 : vpunpcklwd r:x, v:x, m:x
v1 61 66 l1 : vpunpcklwd r:ymm, v:ymm, m:ymm
v1 62 66 l0 : vpunpckldq r:x, v:x, m:x
v1 62 66 l1 : vpunpckldq r:ymm, v:ymm, m:ymm
v1 63 66 l0 : vpacksswb r:x, v:x, m:x
v1 63 66 l1 : vpacksswb r:ymm, v:ymm, m:ymm
v1 64 66 l0 : vpcmpgtb r:x, v:x, m:x
v1 64 66 l1 : vpcmpgtb r:ymm, v:ymm, m:ymm
v1 65 66 l0 : vpcmpgtw r:x, v:x, m:x
v1 65 66 l1 : vpcmpgtw r:ymm, v:ymm, m:ymm
v1 66 66 l0 : vpcmpgtd r:x, v:x, m:x
v1 66 66 l1 : vpcmpgtd r:ymm, v:ymm, m:ymm
v1 67 66 l0 : vpackuswb r:x, v:x, m:x
v1 67 66 l1 : vpackuswb r:ymm, v:ymm, m:ymm
v1 68 66 l0 : vpunpckhbw r:x, v:x, m:x
v1 68 66 l1 : vpunpckhbw r:ymm, v:ymm, m:ymm
v1 69 66 l0 : vpunpckhwd r:x, v:x, m:x
v1 69 66 l1 : vpunpckhwd r:ymm, v:ymm, m:ymm
v1 6a 66 l0 : vpunpckhdq r:x, v:x, m:x
v1 6a 66 l1 : vpunpckhdq r:ymm, v:ymm, m:ymm
v1 6b 66 l0 : vpackssdw r:x, v:x, m:x
v1 6b 66 l1 : vpackssdw r:ymm, v:ymm, m:ymm
v1 6c 66 l0 : vpunpcklqdq r:x, v:x, m:x
v1 6c 66 l1 : vpunpcklqdq r:ymm, v:ymm, m:ymm
v1 6d 66 l0 : vpunpckhqdq r:x, v:x, m:x
v1 6d 66 l1 : vpunpckhqdq r:ymm, v:ymm, m:ymm
v1 6e 66 mode32 l0 : vmovd r:x, m:d ; novvvv
v1 6e 66 mode64 w0 l0 : vmovd r:x, m:d ; novvvv
v1 6e 66 mode64 w1 l0 : vmovq r:x, m:q ; novvvv
v1 6f 66 l0 : vmovdqa r:x, m:x ; novvvv
v1 6f 66 l1 : vmovdqa r:ymm, m:ymm ; novvvv
v1 70 66 l0 : vpshufd r:x, m:x, i:b ; novvvv
v1 70 66 l1 : vpshufd r:ymm, m:ymm, i:b ; novvvv
v1 71 66 l0 /2 r : vpsrlw v:x, R:x, i:b
v1 71 66 l0 /4 r : vpsraw v:x, R:x, i:b
v1 71 66 l0 /6 r : vpsllw v:x, R:x, i:b
v1 71 66 l1 /2 r : vpsrlw v:ymm, R:ymm, i:b
v1 71 66 l1 /4 r : vpsraw v:ymm, R:ymm, i:b
v1 71 66 l1 /6 r : vpsllw v:ymm, R:ymm, i:b
v1 72 66 l0 /2 r : vpsrld v:x, R:x, i:b
v1 72 66 l0 /4 r : vpsrad v:x, R:x, i:b
v1 72 66 l0 /6 r : vpslld v:x, R:x, i:b
v1 72 66 l1 /2 r : vpsrld v:ymm, R:ymm, i:b
v1 72 66 l1 /4 r : vpsrad v:ymm, R:ymm, i:b
v1 72 66 l1 /6 r : vpslld v:ymm, R:ymm, i:b
v1 73 66 l0 /2 r : vpsrlq v:x, R:x, i:b
v1 73 66 l0 /3 r : vpsrldq v:x, R:x, i:b
v1 73 66 l0 /6 r : vpsllq v:x, R:x, i:b
v1 73 66 l0 /7 r : vpslldq v:x, R:x, i:b
v1 73 66 l1 /2 r : vpsrlq v:ymm, R:ymm, i:b
v1 73 66 l1 /3 r : vpsrldq v:ymm, R:ymm, i:b
v1 73 66 l1 /6 r : vpsllq v:ymm, R:ymm, i:b
v1 73 66 l1 /7 r : vpslldq v:ymm, R:ymm, i:b
v1 74 66 l0 : vpcmpeqb r:x, v:x, m:x
v1 74 66 l1 : vpcmpeqb r:ymm, v:ymm, m:ymm
v1 75 66 l0 : vpcmpeqw r:x, v:x, m:x
v1 75 66 l1 : vpcmpeqw r:ymm, v:ymm, m:ymm
v1 76 66 l0 : vpcmpeqd r:x, v:x, m:x
v1 76 66 l1 : vpcmpeqd r:ymm, v:ymm, m:ymm
v1 7c 66 l0 : vhaddpd r:x, v:x, m:x
v1 7c 66 l1 : vhaddpd r:ymm, v:ymm, m:ymm
v1 7d 66 l0 : vhsubpd r:x, v:x, m:x
v1 7d 66 l1 : vhsubpd r:ymm, v:ymm, m:ymm
v1 7e 66 mode32 l0 : vmovd m:d, r:x ; novvvv
v1 7e 66 mode64 w0 l0 : vmovd m:d, r:x ; novvvv
v1 7e 66 mode64 w1 l0 : vmovq m:q, r:x ; novvvv
v1 7f 66 l0 : vmovdqa m:x, r:x ; novvvv
v1 7f 66 l1 : vmovdqa m:ymm, r:ymm ; novvvv
v1 90 66 w0 l0 : kmovb r:k, m:k/b ; novvvv
v1 90 66 w1 l0 : kmovd r:k, m:k/d ; novvvv
v1 91 66 w0 l0 m : kmovb M:/b, r:k ; novvvv
v1 91 66 w1 l0 m : kmovd M:/d, r:k ; novvvv
v1 92 66 w0 l0 r : kmovb r:k, R:d ; novvvv
v1 93 66 w0 l0 r : kmovb r:d, R:k ; novvvv
v1 98 66 w0 l0 r : kortestb r:k, R:k ; novvvv
v1 98 66 w1 l0 r : kortestd r:k, R:k ; novvvv
v1 99 66 w0 l0 r : ktestb r:k, R:k ; novvvv
v1 99 66 w1 l0 r : ktestd r:k, R:k ; novvvv
v1 c2 66 l0 : vcmppd r:x, v:x, m:x, i:b ; cmp32
v1 c2 66 l1 : vcmppd r:ymm, v:ymm, m:ymm, i:b ; cmp32
v1 c4 66 w0 l0 : vpinsrw r:x, v:x, m:d/w, i:b
v1 c5 66 w0 l0 r : vpextrw r:d, R:x, i:b ; novvvv
v1 c6 66 l0 : vshufpd r:x, v:x, m:x, i:b
v1 c6 66 l1 : vshufpd r:ymm, v:ymm, m:ymm, i:b
v1 d0 66 l0 : vaddsubpd r:x, v:x, m:x
v1 d0 66 l1 : vaddsubpd r:ymm, v:ymm, m:ymm
v1 d1 66 l0 : vpsrlw r:x, v:x, m:x
v1 d1 66 l1 : vpsrlw r:ymm, v:ymm, m:x
v1 d2 66 l0 : vpsrld r:x, v:x, m:x
v1 d2 66 l1 : vpsrld r:ymm, v:ymm, m:x
v1 d3 66 l0 : vpsrlq r:x, v:x, m:x
v1 d3 66 l1 : vpsrlq r:ymm, v:ymm, m:x
v1 d4 66 l0 : vpaddq r:x, v:x, m:x
v1 d4 66 l1 : vpaddq r:ymm, v:ymm, m:ymm
v1 d5 66 l0 : vpmullw r:x, v:x, m:x
v1 d5 66 l1 : vpmullw r:ymm, v:ymm, m:ymm
v1 d6 66 l0 : vmovq m:x/q, r:x ; novvvv
v1 d7 66 l0 r : vpmovmskb r:d, R:x ; novvvv
v1 d7 66 l1 r : vpmovmskb r:d, R:ymm ; novvvv
v1 d8 66 l0 : vpsubusb r:x, v:x, m:x
v1 d8 66 l1 : vpsubusb r:ymm, v:ymm, m:ymm
v1 d9 66 l0 : vpsubusw r:x, v:x, m:x
v1 d9 66 l1 : vpsubusw r:ymm, v:ymm, m:ymm
v1 da 66 l0 : vpminub r:x, v:x, m:x
v1 da 66 l1 : vpminub r:ymm, v:ymm, m:ymm
v1 db 66 l0 : vpand r:x, v:x, m:x
v1 db 66 l1 : vpand r:ymm, v:ymm, m:ymm
v1 dc 66 l0 : vpaddusb r:x, v:x, m:x
v1 dc 66 l1 : vpaddusb r:ymm, v:ymm, m:ymm
v1 dd 66 l0 : vpaddusw r:x, v:x, m:x
v1 dd 66 l1 : vpaddusw r:ymm, v:ymm, m:ymm
v1 de 66 l0 : vpmaxub r:x, v:x, m:x
v1 de 66 l1 : vpmaxub r:ymm, v:ymm, m:ymm
v1 df 66 l0 : vpandn r:x, v:x, m:x
v1 df 66 l1 : vpandn r:ymm, v:ymm, m:ymm
v1 e0 66 l0 : vpavgb r:x, v:x, m:x
v1 e0 66 l1 : vpavgb r:ymm, v:ymm, m:ymm
v1 e1 66 l0 : vpsraw r:x, v:x, m:x
v1 e1 66 l1 : vpsraw r:ymm, v:ymm, m:x
v1 e2 66 l0 : vpsrad r:x, v:x, m:x
v1 e2 66 l1 : vpsrad r:ymm, v:ymm, m:x
v1 e3 66 l0 : vpavgw r:x, v:x, m:x
v1 e3 66 l1 : vpavgw r:ymm, v:ymm, m:ymm
v1 e4 66 l0 : vpmulhuw r:x, v:x, m:x
v1 e4 66 l1 : vpmulhuw r:ymm, v:ymm, m:ymm
v1 e5 66 l0 : vpmulhw r:x, v:x, m:x
v1 e5 66 l1 : vpmulhw r:ymm, v:ymm, m:ymm
v1 e6 66 l0 : vcvttpd2dq r:x, m:x ; novvvv
v1 e6 66 l1 : vcvttpd2dq r:x, m:ymm ; novvvv
v1 e7 66 l0 m : vmovntdq M:/x, r:x ; novvvv
v1 e7 66 l1 m : vmovntdq M:/ymm, r:ymm ; novvvv
v1 e8 66 l0 : vpsubsb r:x, v:x, m:x
v1 e8 66 l1 : vpsubsb r:ymm, v:ymm, m:ymm
v1 e9 66 l0 : vpsubsw r:x, v:x, m:x
v1 e9 66 l1 : vpsubsw r:ymm, v:ymm, m:ymm
v1 ea 66 l0 : vpminsw r:x, v:x, m:x
v1 ea 66 l1 : vpminsw r:ymm, v:ymm, m:ymm
v1 eb 66 l0 : vpor r:x, v:x, m:x
v1 eb 66 l1 : vpor r:ymm, v:ymm, m:ymm
v1 ec 66 l0 : vpaddsb r:x, v:x, m:x
v1 ec 66 l1 : vpaddsb r:ymm, v:ymm, m:ymm
v1 ed 66 l0 : vpaddsw r:x, v:x, m:x
v1 ed 66 l1 : vpaddsw r:ymm, v:ymm, m:ymm
v1 ee 66 l0 : vpmaxsw r:x, v:x, m:x
v1 ee 66 l1 : vpmaxsw r:ymm, v:ymm, m:ymm
v1 ef 66 l0 : vpxor r:x, v:x, m:x
v1 ef 66 l1 : vpxor r:ymm, v:ymm, m:ymm
v1 f1 66 l0 : vpsllw r:x, v:x, m:x
v1 f1 66 l1 : vpsllw r:ymm, v:ymm, m:x
v1 f2 66 l0 : vpslld r:x, v:x, m:x
v1 f2 66 l1 : vpslld r:ymm, v:ymm, m:x
v1 f3 66 l0 : vpsllq r:x, v:x, m:x
v1 f3 66 l1 : vpsllq r:ymm, v:ymm, m:x
v1 f4 66 l0 : vpmuludq r:x, v:x, m:x
v1 f4 66 l1 : vpmuludq r:ymm, v:ymm, m:ymm
v1 f5 66 l0 : vpmaddwd r:x, v:x, m:x
v1 f5 66 l1 : vpmaddwd r:ymm, v:ymm, m:ymm
v1 f6 66 l0 : vpsadbw r:x, v:x, m:x
v1 f6 66 l1 : vpsadbw r:ymm, v:ymm, m:ymm
v1 f7 66 l0 r : vmaskmovdqu r:x, R:x ; novvvv
v1 f8 66 l0 : vpsubb r:x, v:x, m:x
v1 f8 66 l1 : vpsubb r:ymm, v:ymm, m:ymm
v1 f9 66 l0 : vpsubw r:x, v:x, m:x
v1 f9 66 l1 : vpsubw r:ymm, v:ymm, m:ymm
v1 fa 66 l0 : vpsubd r:x, v:x, m:x
v1 fa 66 l1 : vpsubd r:ymm, v:ymm, m:ymm
v1 fb 66 l0 : vpsubq r:x, v:x, m:x
v1 fb 66 l1 : vpsubq r:ymm, v:ymm, m:ymm
v1 fc 66 l0 : vpaddb r:x, v:x, m:x
v1 fc 66 l1 : vpaddb r:ymm, v:ymm, m:ymm
v1 fd 66 l0 : vpaddw r:x, v:x, m:x
v1 fd 66 l1 : vpaddw r:ymm, v:ymm, m:ymm
v1 fe 66 l0 : vpaddd r:x, v:x, m:x
v1 fe 66 l1 : vpaddd r:ymm, v:ymm, m:ymm
v1 10 f3 r : vmovss r:x, v:x, R:x
v1 10 f3 m : vmovss r:x, M:/d ; novvvv
v1 11 f3 r : vmovss R:x, v:x, r:x
v1 11 f3 m : vmovss M:/d, r:x ; novvvv
v1 12 f3 l0 : vmovsldup r:x, m:x ; novvvv
v1 12 f3 l1 : vmovsldup r:ymm, m:ymm ; novvvv
v1 16 f3 l0 : vmovshdup r:x, m:x ; novvvv
v1 16 f3 l1 : vmovshdup r:ymm, m:ymm ; novvvv
v1 2a f3 mode32 : vcvtsi2ss r:x, v:x, m:d
v1 2a f3 mode64 w0 : vcvtsi2ss r:x, v:x, m:d
v1 2a f3 mode64 w1 : vcvtsi2ss r:x, v:x, m:q
v1 2c f3 mode32 : vcvttss2si r:d, m:x/d ; novvvv
v1 2c f3 mode64 w0 : vcvttss2si r:d, m:x/d ; novvvv
v1 2c f3 mode64 w1 : vcvttss2si r:q, m:x/d ; novvvv
v1 2d f3 mode32 : vcvtss2si r:d, m:x/d ; novvvv
v1 2d f3 mode64 w0 : vcvtss2si r:d, m:x/d ; novvvv
v1 2d f3 mode64 w1 : vcvtss2si r:q, m:x/d ; novvvv
v1 51 f3 : vsqrtss r:x, v:x, m:x/d
v1 52 f3 : vrsqrtss r:x, v:x, m:x/d
v1 53 f3 : vrcpss r:x, v:x, m:x/d
v1 58 f3 : vaddss r:x, v:x, m:x/d
v1 59 f3 : vmulss r:x, v:x, m:x/d
v1 5a f3 : vcvtss2sd r:x, v:x, m:x/d
v1 5b f3 l0 : vcvttps2dq r:x, m:x ; novvvv
v1 5b f3 l1 : vcvttps2dq r:ymm, m:ymm ; novvvv
v1 5c f3 : vsubss r:x, v:x, m:x/d
v1 5d f3 : vminss r:x, v:x, m:x/d
v1 5e f3 : vdivss r:x, v:x, m:x/d
v1 5f f3 : vmaxss r:x, v:x, m:x/d
v1 6f f3 l0 : vmovdqu r:x, m:x ; novvvv
v1 6f f3 l1 : vmovdqu r:ymm, m:ymm ; novvvv
v1 70 f3 l0 : vpshufhw r:x, m:x, i:b ; novvvv
v1 70 f3 l1 : vpshufhw r:ymm, m:ymm, i:b ; novvvv
v1 7e f3 l0 : vmovq r:x, m:x/q ; novvvv
v1 7f f3 l0 : vmovdqu m:x, r:x ; novvvv
v1 7f f3 l1 : vmovdqu m:ymm, r:ymm ; novvvv
v1 c2 f3 : vcmpss r:x, v:x, m:x/d, i:b ; cmp32
v1 e6 f3 l0 : vcvtdq2pd r:x, m:x/q ; novvvv
v1 e6 f3 l1 : vcvtdq2pd r:ymm, m:x ; novvvv
v1 10 f2 r : vmovsd r:x, v:x, R:x
v1 10 f2 m : vmovsd r:x, M:/q ; novvvv
v1 11 f2 r : vmovsd R:x, v:x, r:x
v1 11 f2 m : vmovsd M:/q, r:x ; novvvv
v1 12 f2 l0 : vmovddup r:x, m:x/q ; novvvv
v1 12 f2 l1 : vmovddup r:ymm, m:ymm ; novvvv
v1 2a f2 mode32 : vcvtsi2sd r:x, v:x, m:d
v1 2a f2 mode64 w0 : vcvtsi2sd r:x, v:x, m:d
v1 2a f2 mode64 w1 : vcvtsi2sd r:x, v:x, m:q
v1 2c f2 mode32 : vcvttsd2si r:d, m:x/q ; novvvv
v1 2c f2 mode64 w0 : vcvttsd2si r:d, m:x/q ; novvvv
v1 2c f2 mode64 w1 : vcvttsd2si r:q, m:x/q ; novvvv
v1 2d f2 mode32 : vcvtsd2si r:d, m:x/q ; novvvv
v1 2d f2 mode64 w0 : vcvtsd2si r:d, m:x/q ; novvvv
v1 2d f2 mode64 w1 : vcvtsd2si r:q, m:x/q ; novvvv
v1 51 f2 : vsqrtsd r:x, v:x, m:x/q
v1 58 f2 : vaddsd r:x, v:x, m:x/q
v1 59 f2 : vmulsd r:x, v:x, m:x/q
v1 5a f2 : vcvtsd2ss r:x, v:x, m:x/q
v1 5c f2 : vsubsd r:x, v:x, m:x/q
v1 5d f2 : vminsd r:x, v:x, m:x/q
v1 5e f2 : vdivsd r:x, v:x, m:x/q
v1 5f f2 : vmaxsd r:x, v:x, m:x/q
v1 70 f2 l0 : vpshuflw r:x, m:x, i:b ; novvvv
v1 70 f2 l1 : vpshuflw r:ymm, m:ymm, i:b ; novvvv
v1 7c f2 l0 : vhaddps r:x, v:x, m:x
v1 7c f2 l1 : vhaddps r:ymm, v:ymm, m:ymm
v1 7d f2 l0 : vhsubps r:x, v:x, m:x
v1 7d f2 l1 : vhsubps r:ymm, v:ymm, m:ymm
v1 92 f2 w0 l0 r : kmovd r:k, R:d ; novvvv
v1 92 f2 w1 l0 r : kmovq r:k, R:q ; novvvv
v1 93 f2 w0 l0 r : kmovd r:d, R:k ; novvvv
v1 93 f2 w1 l0 r : kmovq r:q, R:k ; novvvv
v1 c2 f2 : vcmpsd r:x, v:x, m:x/q, i:b ; cmp32
v1 d0 f2 l0 : vaddsubps r:x, v:x, m:x
v1 d0 f2 l1 : vaddsubps r:ymm, v:ymm, m:ymm
v1 e6 f2 l0 : vcvtpd2dq r:x, m:x ; novvvv
v1 e6 f2 l1 : vcvtpd2dq r:x, m:ymm ; novvvv
v1 f0 f2 l0 m : vlddqu r:x, M:/x ; novvvv
v1 f0 f2 l1 m : vlddqu r:ymm, M:/ymm ; novvvv
v2 f2 np mode32 l0 : andn r:d, v:d, m:d
v2 f2 np mode64 w0 l0 : andn r:d, v:d, m:d
v2 f2 np mode64 w1 l0 : andn r:q, v:q, m:q
v2 f3 np mode32 l0 /1 : blsr v:d, m:d
v2 f3 np mode64 w0 l0 /1 : blsr v:d, m:d
v2 f3 np mode32 l0 /2 : blsmsk v:d, m:d
v2 f3 np mode64 w0 l0 /2 : blsmsk v:d, m:d
v2 f3 np mode32 l0 /3 : blsi v:d, m:d
v2 f3 np mode64 w0 l0 /3 : blsi v:d, m:d
v2 f3 np mode64 w1 l0 /1 : blsr v:q, m:q
v2 f3 np mode64 w1 l0 /2 : blsmsk v:q, m:q
v2 f3 np mode64 w1 l0 /3 : blsi v:q, m:q
v2 f5 np mode32 l0 : bzhi r:d, m:d, v:d
v2 f5 np mode64 w0 l0 : bzhi r:d, m:d, v:d
v2 f5 np mode64 w1 l0 : bzhi r:q, m:q, v:q
v2 f7 np mode32 l0 : bextr r:d, m:d, v:d
v2 f7 np mode64 w0 l0 : bextr r:d, m:d, v:d
v2 f7 np mode64 w1 l0 : bextr r:q, m:q, v:q
v2 00 66 l0 : vpshufb r:x, v:x, m:x
v2 00 66 l1 : vpshufb r:ymm, v:ymm, m:ymm
v2 01 66 l0 : vphaddw r:x, v:x, m:x
v2 01 66 l1 : vphaddw r:ymm, v:ymm, m:ymm
v2 02 66 l0 : vphaddd r:x, v:x, m:x
v2 02 66 l1 : vphaddd r:ymm, v:ymm, m:ymm
v2 03 66 l0 : vphaddsw r:x, v:x, m:x
v2 03 66 l1 : vphaddsw r:ymm, v:ymm, m:ymm
v2 04 66 l0 : vpmaddubsw r:x, v:x, m:x
v2 04 66 l1 : vpmaddubsw r:ymm, v:ymm, m:ymm
v2 05 66 l0 : vphsubw r:x, v:x, m:x
v2 05 66 l1 : vphsubw r:ymm, v:ymm, m:ymm
v2 06 66 w0 l0 : vphsubd r:x, v:x, m:x
v2 06 66 w0 l1 : vphsubd r:ymm, v:ymm, m:ymm
v2 07 66 l0 : vphsubsw r:x, v:x, m:x
v2 07 66 l1 : vphsubsw r:ymm, v:ymm, m:ymm
v2 08 66 l0 : vpsignb r:x, v:x, m:x
v2 08 66 l1 : vpsignb r:ymm, v:ymm, m:ymm
v2 09 66 l0 : vpsignw r:x, v:x, m:x
v2 09 66 l1 : vpsignw r:ymm, v:ymm, m:ymm
v2 0a 66 l0 : vpsignd r:x, v:x, m:x
v2 0a 66 l1 : vpsignd r:ymm, v:ymm, m:ymm
v2 0b 66 l0 : vpmulhrsw r:x, v:x, m:x
v2 0b 66 l1 : vpmulhrsw r:ymm, v:ymm, m:ymm
v2 0c 66 w0 l0 : vpermilps r:x, v:x, m:x
v2 0c 66 w0 l1 : vpermilps r:ymm, v:ymm, m:ymm
v2 0d 66 w0 l0 : vpermilpd r:x, v:x, m:x
v2 0d 66 w0 l1 : vpermilpd r:ymm, v:ymm, m:ymm
v2 0e 66 w0 l0 : vtestps r:x, m:x ; novvvv
v2 0e 66 w0 l1 : vtestps r:ymm, m:ymm ; novvvv
v2 0f 66 w0 l0 : vtestpd r:x, m:x ; novvvv
v2 0f 66 w0 l1 : vtestpd r:ymm, m:ymm ; novvvv
v2 13 66 w0 l0 : vcvtph2ps r:x, m:x/q ; novvvv
v2 13 66 w0 l1 : vcvtph2ps r:ymm, m:x ; novvvv
v2 16 66 w0 l1 : vpermps r:ymm, v:ymm, m:ymm
v2 17 66 l0 : vptest r:x, m:x ; novvvv
v2 17 66 l1 : vptest r:ymm, m:ymm ; novvvv
v2 18 66 w0 l0 : vbroadcastss r:x, m:x/d ; novvvv
v2 18 66 w0 l1 : vbroadcastss r:ymm, m:x/d ; novvvv
v2 19 66 w0 l1 : vbroadcastsd r:ymm, m:x/q ; novvvv
v2 1a 66 w0 l1 m : vbroadcastf128 r:ymm, M:/x ; novvvv
v2 1c 66 l0 : vpabsb r:x, m:x ; novvvv
v2 1c 66 l1 : vpabsb r:ymm, m:ymm ; novvvv
v2 1d 66 l0 : vpabsw r:x, m:x ; novvvv
v2 1d 66 l1 : vpabsw r:ymm, m:ymm ; novvvv
v2 1e 66 l0 : vpabsd r:x, m:x ; novvvv
v2 1e 66 l1 : vpabsd r:ymm, m:ymm ; novvvv
v2 20 66 l0 : vpmovsxbw r:x, m:x/q ; novvvv
v2 20 66 l1 : vpmovsxbw r:ymm, m:x ; novvvv
v2 21 66 l0 : vpmovsxbd r:x, m:x/d ; novvvv
v2 21 66 l1 : vpmovsxbd r:ymm, m:x/q ; novvvv
v2 22 66 l0 : vpmovsxbq r:x, m:x/w ; novvvv
v2 22 66 l1 : vpmovsxbq r:ymm, m:x/d ; novvvv
v2 23 66 l0 : vpmovsxwd r:x, m:x/q ; novvvv
v2 23 66 l1 : vpmovsxwd r:ymm, m:x ; novvvv
v2 24 66 l0 : vpmovsxwq r:x, m:x/d ; novvvv
v2 24 66 l1 : vpmovsxwq r:ymm, m:x/q ; novvvv
v2 25 66 l0 : vpmovsxdq r:x, m:x/q ; novvvv
v2 25 66 l1 : vpmovsxdq r:ymm, m:x ; novvvv
v2 28 66 l0 : vpmuldq r:x, v:x, m:x
v2 28 66 l1 : vpmuldq r:ymm, v:ymm, m:ymm
v2 29 66 l0 : vpcmpeqq r:x, v:x, m:x
v2 29 66 l1 : vpcmpeqq r:ymm, v:ymm, m:ymm
v2 2a 66 l0 m : vmovntdqa r:x, M:/x ; novvvv
v2 2a 66 l1 m : vmovntdqa r:ymm, M:/ymm ; novvvv
v2 2b 66 w0 l0 : vpackusdw r:x, v:x, m:x
v2 2b 66 w0 l1 : vpackusdw r:ymm, v:ymm, m:ymm
v2 2c 66 w0 l0 m : vmaskmovps r:x, v:x, M:/x
v2 2c 66 w0 l1 m : vmaskmovps r:ymm, v:ymm, M:/ymm
v2 2d 66 w0 l0 m : vmaskmovpd r:x, v:x, M:/x
v2 2d 66 w0 l1 m : vmaskmovpd r:ymm, v:ymm, M:/ymm
v2 2e 66 w0 l0 m : vmaskmovps M:/x, v:x, r:x
v2 2e 66 w0 l1 m : vmaskmovps M:/ymm, v:ymm, r:ymm
v2 2f 66 w0 l0 m : vmaskmovpd M:/x, v:x, r:x
v2 2f 66 w0 l1 m : vmaskmovpd M:/ymm, v:ymm, r:ymm
v2 30 66 l0 : vpmovzxbw r:x, m:x/q ; novvvv
v2 30 66 l1 : vpmovzxbw r:ymm, m:x ; novvvv
v2 31 66 l0 : vpmovzxbd r:x, m:x/d ; novvvv
v2 31 66 l1 : vpmovzxbd r:ymm, m:x/q ; novvvv
v2 32 66 l0 : vpmovzxbq r:x, m:x/w ; novvvv
v2 32 66 l1 : vpmovzxbq r:ymm, m:x/d ; novvvv
v2 33 66 l0 : vpmovzxwd r:x, m:x/q ; novvvv
v2 33 66 l1 : vpmovzxwd r:ymm, m:x ; novvvv
v2 34 66 l0 : vpmovzxwq r:x, m:x/d ; novvvv
v2 34 66 l1 : vpmovzxwq r:ymm, m:x/q ; novvvv
v2 35 66 l0 : vpmovzxdq r:x, m:x/q ; novvvv
v2 35 66 l1 : vpmovzxdq r:ymm, m:x ; novvvv
v2 36 66 w0 l1 : vpermd r:ymm, v:ymm, m:ymm
v2 37 66 l0 : vpcmpgtq r:x, v:x, m:x
v2 37 66 l1 : vpcmpgtq r:ymm, v:ymm, m:ymm
v2 38 66 l0 : vpminsb r:x, v:x, m:x
v2 38 66 l1 : vpminsb r:ymm, v:ymm, m:ymm
v2 39 66 l0 : vpminsd r:x, v:x, m:x
v2 39 66 l1 : vpminsd r:ymm, v:ymm, m:ymm
v2 3a 66 l0 : vpminuw r:x, v:x, m:x
v2 3a 66 l1 : vpminuw r:ymm, v:ymm, m:ymm
v2 3b 66 l0 : vpminud r:x, v:x, m:x
v2 3b 66 l1 : vpminud r:ymm, v:ymm, m:ymm
v2 3c 66 l0 : vpmaxsb r:x, v:x, m:x
v2 3c 66 l1 : vpmaxsb r:ymm, v:ymm, m:ymm
v2 3d 66 l0 : vpmaxsd r:x, v:x, m:x
v2 3d 66 l1 : vpmaxsd r:ymm, v:ymm, m:ymm
v2 3e 66 l0 : vpmaxuw r:x, v:x, m:x
v2 3e 66 l1 : vpmaxuw r:ymm, v:ymm, m:ymm
v2 3f 66 l0 : vpmaxud r:x, v:x, m:x
v2 3f 66 l1 : vpmaxud r:ymm, v:ymm, m:ymm
v2 40 66 l0 : vpmulld r:x, v:x, m:x
v2 40 66 l1 : vpmulld r:ymm, v:ymm, m:ymm
v2 41 66 l0 : vphminposuw r:x, m:x ; novvvv
v2 45 66 w0 l0 : vpsrlvd r:x, v:x, m:x
v2 45 66 w0 l1 : vpsrlvd r:ymm, v:ymm, m:ymm
v2 45 66 w1 l0 : vpsrlvq r:x, v:x, m:x
v2 45 66 w1 l1 : vpsrlvq r:ymm, v:ymm, m:ymm
v2 46 66 w0 l0 : vpsravd r:x, v:x, m:x
v2 46 66 w0 l1 : vpsravd r:ymm, v:ymm, m:ymm
v2 47 66 w0 l0 : vpsllvd r:x, v:x, m:x
v2 47 66 w0 l1 : vpsllvd r:ymm, v:ymm, m:ymm
v2 47 66 w1 l0 : vpsllvq r:x, v:x, m:x
v2 47 66 w1 l1 : vpsllvq r:ymm, v:ymm, m:ymm
v2 58 66 w0 l0 : vpbroadcastd r:x, m:x/d ; novvvv
v2 58 66 w0 l1 : vpbroadcastd r:ymm, m:x/d ; novvvv
v2 59 66 w0 l0 : vpbroadcastq r:x, m:x/q ; novvvv
v2 59 66 w0 l1 : vpbroadcastq r:ymm, m:x/q ; novvvv
v2 5a 66 w0 l1 m : vbroadcasti128 r:ymm, M:/x ; novvvv
v2 78 66 w0 l0 : vpbroadcastb r:x, m:x/b ; novvvv
v2 78 66 w0 l1 : vpbroadcastb r:ymm, m:x/b ; novvvv
v2 79 66 w0 l0 : vpbroadcastw r:x, m:x/w ; novvvv
v2 79 66 w0 l1 : vpbroadcastw r:ymm, m:x/w ; novvvv
v2 8c 66 w0 l0 m : vpmaskmovd r:x, v:x, M:/x
v2 8c 66 w0 l1 m : vpmaskmovd r:ymm, v:ymm, M:/ymm
v2 8c 66 w1 l0 m : vpmaskmovq r:x, v:x, M:/x
v2 8c 66 w1 l1 m : vpmaskmovq r:ymm, v:ymm, M:/ymm
v2 8e 66 w0 l0 m : vpmaskmovd M:/x, v:x, r:x
v2 8e 66 w0 l1 m : vpmaskmovd M:/ymm, v:ymm, r:ymm
v2 8e 66 w1 l0 m : vpmaskmovq M:/x, v:x, r:x
v2 8e 66 w1 l1 m : vpmaskmovq M:/ymm, v:ymm, r:ymm
v2 96 66 w0 l0 : vfmaddsub132ps r:x, v:x, m:x
v2 96 66 w0 l1 : vfmaddsub132ps r:ymm, v:ymm, m:ymm
v2 96 66 w1 l0 : vfmaddsub132pd r:x, v:x, m:x
v2 96 66 w1 l1 : vfmaddsub132pd r:ymm, v:ymm, m:ymm
v2 97 66 w0 l0 : vfmsubadd132ps r:x, v:x, m:x
v2 97 66 w0 l1 : vfmsubadd132ps r:ymm, v:ymm, m:ymm
v2 97 66 w1 l0 : vfmsubadd132pd r:x, v:x, m:x
v2 97 66 w1 l1 : vfmsubadd132pd r:ymm, v:ymm, m:ymm
v2 98 66 w0 l0 : vfmadd132ps r:x, v:x, m:x
v2 98 66 w0 l1 : vfmadd132ps r:ymm, v:ymm, m:ymm
v2 98 66 w1 l0 : vfmadd132pd r:x, v:x, m:x
v2 98 66 w1 l1 : vfmadd132pd r:ymm, v:ymm, m:ymm
v2 99 66 w0 : vfmadd132ss r:x, v:x, m:x/d
v2 99 66 w1 : vfmadd132sd r:x, v:x, m:x/q
v2 9a 66 w0 l0 : vfmsub132ps r:x, v:x, m:x
v2 9a 66 w0 l1 : vfmsub132ps r:ymm, v:ymm, m:ymm
v2 9a 66 w1 l0 : vfmsub132pd r:x, v:x, m:x
v2 9a 66 w1 l1 : vfmsub132pd r:ymm, v:ymm, m:ymm
v2 9b 66 w0 : vfmsub132ss r:x, v:x, m:x/d
v2 9b 66 w1 : vfmsub132sd r:x, v:x, m:x/q
v2 9c 66 w0 l0 : vfnmadd132ps r:x, v:x, m:x
v2 9c 66 w0 l1 : vfnmadd132ps r:ymm, v:ymm, m:ymm
v2 9c 66 w1 l0 : vfnmadd132pd r:x, v:x, m:x
v2 9c 66 w1 l1 : vfnmadd132pd r:ymm, v:ymm, m:ymm
v2 9d 66 w0 : vfnmadd132ss r:x, v:x, m:x/d
v2 9d 66 w1 : vfnmadd132sd r:x, v:x, m:x/q
v2 9e 66 w0 l0 : vfnmsub132ps r:x, v:x, m:x
v2 9e 66 w0 l1 : vfnmsub132ps r:ymm, v:ymm, m:ymm
v2 9e 66 w1 l0 : vfnmsub132pd r:x, v:x, m:x
v2 9e 66 w1 l1 : vfnmsub132pd r:ymm, v:ymm, m:ymm
v2 9f 66 w0 : vfnmsub132ss r:x, v:x, m:x/d
v2 9f 66 w1 : vfnmsub132sd r:x, v:x, m:x/q
v2 a6 66 w0 l0 : vfmaddsub213ps r:x, v:x, m:x
v2 a6 66 w0 l1 : vfmaddsub213ps r:ymm, v:ymm, m:ymm
v2 a6 66 w1 l0 : vfmaddsub213pd r:x, v:x, m:x
v2 a6 66 w1 l1 : vfmaddsub213pd r:ymm, v:ymm, m:ymm
v2 a7 66 w0 l0 : vfmsubadd213ps r:x, v:x, m:x
v2 a7 66 w0 l1 : vfmsubadd213ps r:ymm, v:ymm, m:ymm
v2 a7 66 w1 l0 : vfmsubadd213pd r:x, v:x, m:x
v2 a7 66 w1 l1 : vfmsubadd213pd r:ymm, v:ymm, m:ymm
v2 a8 66 w0 l0 : vfmadd213ps r:x, v:x, m:x
v2 a8 66 w0 l1 : vfmadd213ps r:ymm, v:ymm, m:ymm
v2 a8 66 w1 l0 : vfmadd213pd r:x, v:x, m:x
v2 a8 66 w1 l1 : vfmadd213pd r:ymm, v:ymm, m:ymm
v2 a9 66 w0 : vfmadd213ss r:x, v:x, m:x/d
v2 a9 66 w1 : vfmadd213sd r:x, v:x, m:x/q
v2 aa 66 w0 l0 : vfmsub213ps r:x, v:x, m:x
v2 aa 66 w0 l1 : vfmsub213ps r:ymm, v:ymm, m:ymm
v2 aa 66 w1 l0 : vfmsub213pd r:x, v:x, m:x
v2 aa 66 w1 l1 : vfmsub213pd r:ymm, v:ymm, m:ymm
v2 ab 66 w0 : vfmsub213ss r:x, v:x, m:x/d
v2 ab 66 w1 : vfmsub213sd r:x, v:x, m:x/q
v2 ac 66 w0 l0 : vfnmadd213ps r:x, v:x, m:x
v2 ac 66 w0 l1 : vfnmadd213ps r:ymm, v:ymm, m:ymm
v2 ac 66 w1 l0 : vfnmadd213pd r:x, v:x, m:x
v2 ac 66 w1 l1 : vfnmadd213pd r:ymm, v:ymm, m:ymm
v2 ad 66 w0 : vfnmadd213ss r:x, v:x, m:x/d
v2 ad 66 w1 : vfnmadd213sd r:x, v:x, m:x/q
v2 ae 66 w0 l0 : vfnmsub213ps r:x, v:x, m:x
v2 ae 66 w0 l1 : vfnmsub213ps r:ymm, v:ymm, m:ymm
v2 ae 66 w1 l0 : vfnmsub213pd r:x, v:x, m:x
v2 ae 66 w1 l1 : vfnmsub213pd r:ymm, v:ymm, m:ymm
v2 af 66 w0 : vfnmsub213ss r:x, v:x, m:x/d
v2 af 66 w1 : vfnmsub213sd r:x, v:x, m:x/q
v2 b6 66 w0 l0 : vfmaddsub231ps r:x, v:x, m:x
v2 b6 66 w0 l1 : vfmaddsub231ps r:ymm, v:ymm, m:ymm
v2 b6 66 w1 l0 : vfmaddsub231pd r:x, v:x, m:x
v2 b6 66 w1 l1 : vfmaddsub231pd r:ymm, v:ymm, m:ymm
v2 b7 66 w0 l0 : vfmsubadd231ps r:x, v:x, m:x
v2 b7 66 w0 l1 : vfmsubadd231ps r:ymm, v:ymm, m:ymm
v2 b7 66 w1 l0 : vfmsubadd231pd r:x, v:x, m:x
v2 b7 66 w1 l1 : vfmsubadd231pd r:ymm, v:ymm, m:ymm
v2 b8 66 w0 l0 : vfmadd231ps r:x, v:x, m:x
v2 b8 66 w0 l1 : vfmadd231ps r:ymm, v:ymm, m:ymm
v2 b8 66 w1 l0 : vfmadd231pd r:x, v:x, m:x
v2 b8 66 w1 l1 : vfmadd231pd r:ymm, v:ymm, m:ymm
v2 b9 66 w0 : vfmadd231ss r:x, v:x, m:x/d
v2 b9 66 w1 : vfmadd231sd r:x, v:x, m:x/q
v2 ba 66 w0 l0 : vfmsub231ps r:x, v:x, m:x
v2 ba 66 w0 l1 : vfmsub231ps r:ymm, v:ymm, m:ymm
v2 ba 66 w1 l0 : vfmsub231pd r:x, v:x, m:x
v2 ba 66 w1 l1 : vfmsub231pd r:ymm, v:ymm, m:ymm
v2 bb 66 w0 : vfmsub231ss r:x, v:x, m:x/d
v2 bb 66 w1 : vfmsub231sd r:x, v:x, m:x/q
v2 bc 66 w0 l0 : vfnmadd231ps r:x, v:x, m:x
v2 bc 66 w0 l1 : vfnmadd231ps r:ymm, v:ymm, m:ymm
v2 bc 66 w1 l0 : vfnmadd231pd r:x, v:x, m:x
v2 bc 66 w1 l1 : vfnmadd231pd r:ymm, v:ymm, m:ymm
v2 bd 66 w0 : vfnmadd231ss r:x, v:x, m:x/d
v2 bd 66 w1 : vfnmadd231sd r:x, v:x, m:x/q
v2 be 66 w0 l0 : vfnmsub231ps r:x, v:x, m:x
v2 be 66 w0 l1 : vfnmsub231ps r:ymm, v:ymm, m:ymm
v2 be 66 w1 l0 : vfnmsub231pd r:x, v:x, m:x
v2 be 66 w1 l1 : vfnmsub231pd r:ymm, v:ymm, m:ymm
v2 bf 66 w0 : vfnmsub231ss r:x, v:x, m:x/d
v2 bf 66 w1 : vfnmsub231sd r:x, v:x, m:x/q
v2 cf 66 w0 l0 : vgf2p8mulb r:x, v:x, m:x
v2 cf 66 w0 l1 : vgf2p8mulb r:ymm, v:ymm, m:ymm
v2 db 66 l0 : vaesimc r:x, m:x ; novvvv
v2 dc 66 l0 : vaesenc r:x, v:x, m:x
v2 dc 66 l1 : vaesenc r:ymm, v:ymm, m:ymm
v2 dd 66 l0 : vaesenclast r:x, v:x, m:x
v2 dd 66 l1 : vaesenclast r:ymm, v:ymm, m:ymm
v2 de 66 l0 : vaesdec r:x, v:x, m:x
v2 de 66 l1 : vaesdec r:ymm, v:ymm, m:ymm
v2 df 66 l0 : vaesdeclast r:x, v:x, m:x
v2 df 66 l1 : vaesdeclast r:ymm, v:ymm, m:ymm
v2 f7 66 mode32 l0 : shlx r:d, m:d, v:d
v2 f7 66 mode64 w0 l0 : shlx r:d, m:d, v:d
v2 f7 66 mode64 w1 l0 : shlx r:q, m:q, v:q
v2 f5 f3 mode32 l0 : pext r:d, v:d, m:d
v2 f5 f3 mode64 w0 l0 : pext r:d, v:d, m:d
v2 f5 f3 mode64 w1 l0 : pext r:q, v:q, m:q
v2 f7 f3 mode32 l0 : sarx r:d, m:d, v:d
v2 f7 f3 mode64 w0 l0 : sarx r:d, m:d, v:d
v2 f7 f3 mode64 w1 l0 : sarx r:q, m:q, v:q
v2 f5 f2 mode32 l0 : pdep r:d, v:d, m:d
v2 f5 f2 mode64 w0 l0 : pdep r:d, v:d, m:d
v2 f5 f2 mode64 w1 l0 : pdep r:q, v:q, m:q
v2 f6 f2 mode32 l0 : mulx r:d, v:d, m:d
v2 f6 f2 mode64 w0 l0 : mulx r:d, v:d, m:d
v2 f6 f2 mode64 w1 l0 : mulx r:q, v:q, m:q
v2 f7 f2 mode32 l0 : shrx r:d, m:d, v:d
v2 f7 f2 mode64 w0 l0 : shrx r:d, m:d, v:d
v2 f7 f2 mode64 w1 l0 : shrx r:q, m:q, v:q
v3 00 66 w1 l1 : vpermq r:ymm, m:ymm, i:b ; novvvv
v3 01 66 w1 l1 : vpermpd r:ymm, m:ymm, i:b ; novvvv
v3 02 66 w0 l0 : vpblendd r:x, v:x, m:x, i:b
v3 02 66 w0 l1 : vpblendd r:ymm, v:ymm, m:ymm, i:b
v3 04 66 w0 l0 : vpermilps r:x, m:x, i:b ; novvvv
v3 04 66 w0 l1 : vpermilps r:ymm, m:ymm, i:b ; novvvv
v3 05 66 w0 l0 : vpermilpd r:x, m:x, i:b ; novvvv
v3 05 66 w0 l1 : vpermilpd r:ymm, m:ymm, i:b ; novvvv
v3 06 66 w0 l1 : vperm2f128 r:ymm, v:ymm, m:ymm, i:b
v3 08 66 l0 : vroundps r:x, m:x, i:b ; novvvv
v3 08 66 l1 : vroundps r:ymm, m:ymm, i:b ; novvvv
v3 09 66 l0 : vroundpd r:x, m:x, i:b ; novvvv
v3 09 66 l1 : vroundpd r:ymm, m:ymm, i:b ; novvvv
v3 0a 66 : vroundss r:x, v:x, m:x/d, i:b
v3 0b 66 : vroundsd r:x, v:x, m:x/q, i:b
v3 0c 66 l0 : vblendps r:x, v:x, m:x, i:b
v3 0c 66 l1 : vblendps r:ymm, v:ymm, m:ymm, i:b
v3 0d 66 l0 : vblendpd r:x, v:x, m:x, i:b
v3 0d 66 l1 : vblendpd r:ymm, v:ymm, m:ymm, i:b
v3 0e 66 l0 : vpblendw r:x, v:x, m:x, i:b
v3 0e 66 l1 : vpblendw r:ymm, v:ymm, m:ymm, i:b
v3 0f 66 l0 : vpalignr r:x, v:x, m:x, i:b
v3 0f 66 l1 : vpalignr r:ymm, v:ymm, m:ymm, i:b
v3 14 66 w0 l0 : vpextrb m:d/b, r:x, i:b ; novvvv
v3 15 66 w0 l0 : vpextrw m:d/w, r:x, i:b ; novvvv
v3 16 66 w0 l0 : vpextrd m:d, r:x, i:b ; novvvv
v3 16 66 w1 l0 : vpextrq m:q, r:x, i:b ; novvvv
v3 17 66 l0 : vextractps m:d, r:x, i:b ; novvvv
v3 18 66 w0 l1 : vinsertf128 r:ymm, v:ymm, m:x, i:b
v3 19 66 w0 l1 : vextractf128 m:x, r:ymm, i:b ; novvvv
v3 1d 66 w0 l0 : vcvtps2ph m:x/q, r:x, i:b ; novvvv
v3 1d 66 w0 l1 : vcvtps2ph m:x, r:ymm, i:b ; novvvv
v3 20 66 w0 l0 : vpinsrb r:x, v:x, m:d/b, i:b
v3 21 66 l0 : vinsertps r:x, v:x, m:x/d, i:b
v3 22 66 w0 l0 : vpinsrd r:x, v:x, m:d, i:b
v3 22 66 w1 l0 : vpinsrq r:x, v:x, m:q, i:b
v3 30 66 w0 l0 r : kshiftrb r:k, R:k, i:b ; novvvv
v3 30 66 w1 l0 r : kshiftrw r:k, R:k, i:b ; novvvv
v3 31 66 w0 l0 r : kshiftrd r:k, R:k, i:b ; novvvv
v3 31 66 w1 l0 r : kshiftrq r:k, R:k, i:b ; novvvv
v3 32 66 w0 l0 r : kshiftlb r:k, R:k, i:b ; novvvv
v3 32 66 w1 l0 r : kshiftlw r:k, R:k, i:b ; novvvv
v3 33 66 w0 l0 r : kshiftld r:k, R:k, i:b ; novvvv
v3 33 66 w1 l0 r : kshiftlq r:k, R:k, i:b ; novvvv
v3 38 66 w0 l1 : vinserti128 r:ymm, v:ymm, m:x, i:b
v3 39 66 w0 l1 : vextracti128 m:x, r:ymm, i:b ; novvvv
v3 40 66 l0 : vdpps r:x, v:x, m:x, i:b
v3 40 66 l1 : vdpps r:ymm, v:ymm, m:ymm, i:b
v3 41 66 l0 : vdppd r:x, v:x, m:x, i:b
v3 42 66 l0 : vmpsadbw r:x, v:x, m:x, i:b
v3 42 66 l1 : vmpsadbw r:ymm, v:ymm, m:ymm, i:b
v3 44 66 l0 : vpclmulqdq r:x, v:x, m:x, i:b
v3 44 66 l1 : vpclmulqdq r:ymm, v:ymm, m:ymm, i:b
v3 46 66 w0 l1 : vperm2i128 r:ymm, v:ymm, m:ymm, i:b
v3 48 66 w0 l0 : vpermil2ps r:x, v:x, m:x, 4:x, i:b
v3 48 66 w0 l1 : vpermil2ps r:ymm, v:ymm, m:ymm, 4:ymm, i:b
v3 48 66 w1 l0 : vpermil2ps r:x, v:x, 4:x, m:x, i:b
v3 48 66 w1 l1 : vpermil2ps r:ymm, v:ymm, 4:ymm, m:ymm, i:b
v3 49 66 w0 l0 : vpermil2pd r:x, v:x, m:x, 4:x, i:b
v3 49 66 w0 l1 : vpermil2pd r:ymm, v:ymm, m:ymm, 4:ymm, i:b
v3 49 66 w1 l0 : vpermil2pd r:x, v:x, 4:x, m:x, i:b
v3 49 66 w1 l1 : vpermil2pd r:ymm, v:ymm, 4:ymm, m:ymm, i:b
v3 4a 66 w0 l0 : vblendvps r:x, v:x, m:x, 4:x
v3 4a 66 w0 l1 : vblendvps r:ymm, v:ymm, m:ymm, 4:ymm
v3 4b 66 w0 l0 : vblendvpd r:x, v:x, m:x, 4:x
v3 4b 66 w0 l1 : vblendvpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 4c 66 w0 l0 : vpblendvb r:x, v:x, m:x, 4:x
v3 4c 66 w0 l1 : vpblendvb r:ymm, v:ymm, m:ymm, 4:ymm
v3 5c 66 w0 l0 : vfmaddsubps r:x, v:x, m:x, 4:x
v3 5c 66 w0 l1 : vfmaddsubps r:ymm, v:ymm, m:ymm, 4:ymm
v3 5c 66 w1 l0 : vfmaddsubps r:x, v:x, 4:x, m:x
v3 5c 66 w1 l1 : vfmaddsubps r:ymm, v:ymm, 4:ymm, m:ymm
v3 5d 66 w0 l0 : vfmaddsubpd r:x, v:x, m:x, 4:x
v3 5d 66 w0 l1 : vfmaddsubpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 5d 66 w1 l0 : vfmaddsubpd r:x, v:x, 4:x, m:x
v3 5d 66 w1 l1 : vfmaddsubpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 5e 66 w0 l0 : vfmsubaddps r:x, v:x, m:x, 4:x
v3 5e 66 w0 l1 : vfmsubaddps r:ymm, v:ymm, m:ymm, 4:ymm
v3 5e 66 w1 l0 : vfmsubaddps r:x, v:x, 4:x, m:x
v3 5e 66 w1 l1 : vfmsubaddps r:ymm, v:ymm, 4:ymm, m:ymm
v3 5f 66 w0 l0 : vfmsubaddpd r:x, v:x, m:x, 4:x
v3 5f 66 w0 l1 : vfmsubaddpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 5f 66 w1 l0 : vfmsubaddpd r:x, v:x, 4:x, m:x
v3 5f 66 w1 l1 : vfmsubaddpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 60 66 w0 l0 : vpcmpestrm r:x, m:x, i:b ; novvvv
v3 61 66 w0 l0 : vpcmpestri r:x, m:x, i:b ; novvvv
v3 62 66 w0 l0 : vpcmpistrm r:x, m:x, i:b ; novvvv
v3 63 66 w0 l0 : vpcmpistri r:x, m:x, i:b ; novvvv
v3 68 66 w0 l0 : vfmaddps r:x, v:x, m:x, 4:x
v3 68 66 w0 l1 : vfmaddps r:ymm, v:ymm, m:ymm, 4:ymm
v3 68 66 w1 l0 : vfmaddps r:x, v:x, 4:x, m:x
v3 68 66 w1 l1 : vfmaddps r:ymm, v:ymm, 4:ymm, m:ymm
v3 69 66 w0 l0 : vfmaddpd r:x, v:x, m:x, 4:x
v3 69 66 w0 l1 : vfmaddpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 69 66 w1 l0 : vfmaddpd r:x, v:x, 4:x, m:x
v3 69 66 w1 l1 : vfmaddpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 6a 66 w0 : vfmaddss r:x, v:x, m:x/d, 4:x
v3 6a 66 w1 : vfmaddss r:x, v:x, 4:x, m:x/d
v3 6b 66 w0 : vfmaddsd r:x, v:x, m:x/q, 4:x
v3 6b 66 w1 : vfmaddsd r:x, v:x, 4:x, m:x/q
v3 6c 66 w0 l0 : vfmsubps r:x, v:x, m:x, 4:x
v3 6c 66 w0 l1 : vfmsubps r:ymm, v:ymm, m:ymm, 4:ymm
v3 6c 66 w1 l0 : vfmsubps r:x, v:x, 4:x, m:x
v3 6c 66 w1 l1 : vfmsubps r:ymm, v:ymm, 4:ymm, m:ymm
v3 6d 66 w0 l0 : vfmsubpd r:x, v:x, m:x, 4:x
v3 6d 66 w0 l1 : vfmsubpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 6d 66 w1 l0 : vfmsubpd r:x, v:x, 4:x, m:x
v3 6d 66 w1 l1 : vfmsubpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 6e 66 w0 : vfmsubss r:x, v:x, m:x/d, 4:x
v3 6e 66 w1 : vfmsubss r:x, v:x, 4:x, m:x/d
v3 6f 66 w0 : vfmsubsd r:x, v:x, m:x/q, 4:x
v3 6f 66 w1 : vfmsubsd r:x, v:x, 4:x, m:x/q
v3 78 66 w0 l0 : vfnmaddps r:x, v:x, m:x, 4:x
v3 78 66 w0 l1 : vfnmaddps r:ymm, v:ymm, m:ymm, 4:ymm
v3 78 66 w1 l0 : vfnmaddps r:x, v:x, 4:x, m:x
v3 78 66 w1 l1 : vfnmaddps r:ymm, v:ymm, 4:ymm, m:ymm
v3 79 66 w0 l0 : vfnmaddpd r:x, v:x, m:x, 4:x
v3 79 66 w0 l1 : vfnmaddpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 79 66 w1 l0 : vfnmaddpd r:x, v:x, 4:x, m:x
v3 79 66 w1 l1 : vfnmaddpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 7a 66 w0 : vfnmaddss r:x, v:x, m:x/d, 4:x
v3 7a 66 w1 : vfnmaddss r:x, v:x, 4:x, m:x/d
v3 7b 66 w0 : vfnmaddsd r:x, v:x, m:x/q, 4:x
v3 7b 66 w1 : vfnmaddsd r:x, v:x, 4:x, m:x/q
v3 7c 66 w0 l0 : vfnmsubps r:x, v:x, m:x, 4:x
v3 7c 66 w0 l1 : vfnmsubps r:ymm, v:ymm, m:ymm, 4:ymm
v3 7c 66 w1 l0 : vfnmsubps r:x, v:x, 4:x, m:x
v3 7c 66 w1 l1 : vfnmsubps r:ymm, v:ymm, 4:ymm, m:ymm
v3 7d 66 w0 l0 : vfnmsubpd r:x, v:x, m:x, 4:x
v3 7d 66 w0 l1 : vfnmsubpd r:ymm, v:ymm, m:ymm, 4:ymm
v3 7d 66 w1 l0 : vfnmsubpd r:x, v:x, 4:x, m:x
v3 7d 66 w1 l1 : vfnmsubpd r:ymm, v:ymm, 4:ymm, m:ymm
v3 7e 66 w0 : vfnmsubss r:x, v:x, m:x/d, 4:x
v3 7e 66 w1 : vfnmsubss r:x, v:x, 4:x, m:x/d
v3 7f 66 w0 : vfnmsubsd r:x, v:x, m:x/q, 4:x
v3 7f 66 w1 : vfnmsubsd r:x, v:x, 4:x, m:x/q
v3 ce 66 w1 l0 : vgf2p8affineqb r:x, v:x, m:x, i:b
v3 ce 66 w1 l1 : vgf2p8affineqb r:ymm, v:ymm, m:ymm, i:b
v3 cf 66 w1 l0 : vgf2p8affineinvqb r:x, v:x, m:x, i:b
v3 cf 66 w1 l1 : vgf2p8affineinvqb r:ymm, v:ymm, m:ymm, i:b
v3 df 66 l0 : vaeskeygenassist r:x, m:x, i:b ; novvvv
v3 f0 f2 mode32 l0 : rorx r:d, m:d, i:b ; novvvv
v3 f0 f2 mode64 w0 l0 : rorx r:d, m:d, i:b ; novvvv
v3 f0 f2 mode64 w1 l0 : rorx r:q, m:q, i:b ; novvvv
"#;
