#!/usr/bin/env python3
"""Generates src/plugins/pyreqs.rs: every python plugin's full requirement list (the CLI-visible
options and the hidden ones: kernel module, translation layers, symbol tables, version
dependencies), in python's get_requirements() order. rsvol uses it to write what python's
`build_configuration()` records (--save-config, timeliner --record-config).

Run with:  /home/user/rs-vol/bench/venv/bin/python bench/scripts/gen_pyreqs.py
(imports the framework only, no memory image is opened)

Encoding of one requirement, `<kind>:<name>`:
  K  ModuleRequirement            (recorded as the module's configuration tree)
  P  TranslationLayerRequirement  (the layer's configuration tree)
  S  SymbolTableRequirement
  v  VersionRequirement / PluginRequirement (recorded as `false`)
  b  BooleanRequirement           (always recorded: its value or default)
  i s u c y  Int / String / URI / Choice / Bytes requirement (recorded when it has a value)
  l  ListRequirement              (its value, `[]` when neither given nor defaulted)
  ?  anything else
"""
import os
import sys

sys.path.insert(0, "/home/user/rs-vol/volatility3")

import volatility3.framework as framework  # noqa: E402
import volatility3.plugins as vplugins  # noqa: E402
from volatility3.framework.configuration import requirements as R  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def kind(req):
    order = [
        (R.ModuleRequirement, "K"),
        (R.TranslationLayerRequirement, "P"),
        (R.SymbolTableRequirement, "S"),
        (R.VersionRequirement, "v"),
        (R.BooleanRequirement, "b"),
        (R.IntRequirement, "i"),
        (R.URIRequirement, "u"),
        (R.StringRequirement, "s"),
        (R.BytesRequirement, "y"),
        (R.ChoiceRequirement, "c"),
        (R.ListRequirement, "l"),
    ]
    for cls, k in order:
        if isinstance(req, cls):
            return k
    return "?"


def main():
    framework.require_interface_version(2, 0, 0)
    framework.import_files(vplugins, True)
    plugins = framework.list_plugins()
    lines = []
    for name in sorted(plugins):
        reqs = []
        for req in plugins[name].get_requirements():
            reqs.append(f'"{kind(req)}:{req.name}"')
        lines.append(f'    ("{name}", &[{", ".join(reqs)}]),')
    out = f"""//! Every python plugin's requirement list in `get_requirements()` order, generated by
//! `bench/scripts/gen_pyreqs.py` from volatility3 2.28.2 (do not edit): what python's
//! `build_configuration()` walks for `--save-config` and `timeliner --record-config`.
//!
//! Derived from Volatility 3 (Volatility Software License 1.0).
//!
//! `<kind>:<name>`: K module, P translation layer, S symbol table, v version dependency,
//! b bool, i int, s string, u URI, y bytes, c choice, l list, ? other.

pub const PY_REQS: [(&str, &[&str]); {len(lines)}] = [
{chr(10).join(lines)}
];

/// The python requirement list of a plugin (full dotted name), if python has the plugin.
pub fn py_reqs(plugin: &str) -> Option<&'static [&'static str]> {{
    PY_REQS.binary_search_by(|(n, _)| n.cmp(&plugin)).ok().map(|i| PY_REQS[i].1)
}}
"""
    path = os.path.join(ROOT, "src", "plugins", "pyreqs.rs")
    open(path, "w").write(out)
    print(f"wrote {path}: {len(lines)} plugins")


if __name__ == "__main__":
    main()
