#!/usr/bin/env python3
"""Learn / refine the AArch64 instruction-class spec by probing capstone (see arm_learn.py for
the model and arm_driver.py for the commands: learn / explore / check / emit / stats / explain).

  gen_arm64_spec.py learn SPEC.json [--rand N] [--words FILE] [--seed S]
  gen_arm64_spec.py explore SPEC.json [--rounds R]
  gen_arm64_spec.py emit SPEC.json src/disasm/arm64/spec_data.rs
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arm_driver  # noqa: E402
from arm_learn import HANDLERS, fmt_num  # noqa: E402


# ----------------------------------------------------------------------------------------------
# hand-written handlers (value-comparison aliases); mirrored in src/disasm/arm64/mod.rs

def _gpr(sf, n):
    if sf:
        return "xzr" if n == 31 else "x%d" % n
    return "wzr" if n == 31 else "w%d" % n


def _imm32(v):
    return "#" + fmt_num(v, "S32")


def h_bitfield(w, addr):
    """SBFM / BFM / UBFM and their aliases (asr lsl lsr sxt* uxt* sbfiz sbfx ubfiz ubfx bfc bfi
    bfxil), selected by comparing immr / imms (ARM ARM alias conditions)."""
    sf = w >> 31
    opc = (w >> 29) & 3
    n = (w >> 22) & 1
    immr = (w >> 16) & 63
    imms = (w >> 10) & 63
    rn = (w >> 5) & 31
    rd = w & 31
    if opc == 3 or sf != n or (not sf and (immr >= 32 or imms >= 32)):
        return None
    width = 64 if sf else 32
    d, s = _gpr(sf, rd), _gpr(sf, rn)
    if opc == 1:
        if rn == 31 and (immr == 0 or imms < immr):
            return "bfc\t%s, %s, %s" % (d, _imm32((width - immr) % width), _imm32(imms + 1))
        if imms < immr:
            return "bfi\t%s, %s, %s, %s" % (d, s, _imm32((width - immr) % width), _imm32(imms + 1))
        return "bfxil\t%s, %s, %s, %s" % (d, s, _imm32(immr), _imm32(imms - immr + 1))
    signed = opc == 0
    if immr == 0:
        m = None
        if imms == 7:
            m = "sxtb" if signed else (None if sf else "uxtb")
        elif imms == 15:
            m = "sxth" if signed else (None if sf else "uxth")
        elif imms == 31:
            m = "sxtw" if signed and sf else None
        if m:
            return "%s\t%s, %s" % (m, d, _gpr(0, rn))
    if not signed and imms != width - 1 and imms + 1 == immr:
        return "lsl\t%s, %s, %s" % (d, s, _imm32(width - 1 - imms))
    if imms == width - 1:
        return "%s\t%s, %s, %s" % ("asr" if signed else "lsr", d, s, _imm32(immr))
    if immr > imms:
        return "%s\t%s, %s, %s, %s" % ("sbfiz" if signed else "ubfiz", d, s, _imm32(width - immr),
                                       _imm32(imms + 1))
    return "%s\t%s, %s, %s, %s" % ("sbfx" if signed else "ubfx", d, s, _imm32(immr), _imm32(imms - immr + 1))


HANDLERS["bitfield"] = h_bitfield
HANDLERS["invalid"] = lambda w, addr: None


class Arm64(arm_driver.ArchConfig):
    name = "arm64"
    handler_classes = [("bitfield", 0x1F800000, 0x13000000)]
    reg_fields = (0, 5, 10, 16)
    rw = 5
    rust_header = """//! AArch64 instruction spec (generated by bench/scripts/gen_arm64_spec.py from probing the
//! capstone 5 oracle; grammar in bench/scripts/arm_spec.py). DO NOT EDIT BY HAND.

pub(crate) const SPEC: &str = r#\""""


if __name__ == "__main__":
    arm_driver.main(Arm64(), sys.argv)
