#!/usr/bin/env python3
"""Dump every python volatility3 plugin's requirement list (`get_requirements()`, python order)
as the data table rsvol builds `--save-config` / `timeliner --record-config` from:

    bench/venv/bin/python bench/scripts/py_plugin_reqs.py > src/plugins/pyreqs.tsv

One line per top-level requirement, TAB separated:

    plugin  name  kind  optional  default  extra  description

  plugin    registry name, e.g. windows.pslist.PsList
  name      requirement name (the config key under plugins.<Class>.)
  kind      Bool Int String URI Bytes List Choice Version Module Layer Symbols Multi ComplexList
            (Version = VersionRequirement / PluginRequirement; Module = ModuleRequirement;
            Layer = TranslationLayerRequirement; Symbols = SymbolTableRequirement; None = the
            plugin has no requirements: one row with an empty name)
  optional  0 / 1
  default   json.dumps(requirement.default) (bytes as {"bytes": hex})
  extra     List: element type (int / str / ...); Module / Layer: architectures joined by ','
            (Layer: then ';' and the oses); Choice: the choices as a JSON list; else empty
  description  json.dumps(requirement.description) (python's "Unsatisfied requirement" text)

Only data python itself holds; rsvol's semantics (which values land in the saved configuration)
live in src/plugins/pyreqs.rs.
"""
import json
import sys

sys.path.insert(0, "/home/user/rs-vol/volatility3")

from volatility3 import framework, plugins  # noqa: E402
from volatility3.framework import interfaces  # noqa: E402
from volatility3.framework.configuration import requirements as R  # noqa: E402

framework.require_interface_version(2, 0, 0)
failures = framework.import_files(plugins, True)


def default_json(v):
    if isinstance(v, bytes):
        return json.dumps({"bytes": v.hex()})
    try:
        return json.dumps(v, sort_keys=True)
    except TypeError:
        return json.dumps(repr(v))


def kind_of(r):
    # most specific first (URI is a String, Plugin is a Version, LayerList is a ComplexList)
    for cls, k in [
        (R.URIRequirement, "URI"),
        (R.BooleanRequirement, "Bool"),
        (R.IntRequirement, "Int"),
        (R.StringRequirement, "String"),
        (R.BytesRequirement, "Bytes"),
        (R.ListRequirement, "List"),
        (R.ChoiceRequirement, "Choice"),
        (R.VersionRequirement, "Version"),
        (R.ModuleRequirement, "Module"),
        (R.TranslationLayerRequirement, "Layer"),
        (R.SymbolTableRequirement, "Symbols"),
        (R.ComplexListRequirement, "ComplexList"),
        (R.MultiRequirement, "Multi"),
    ]:
        if isinstance(r, cls):
            return k
    return type(r).__name__


def extra_of(r, k):
    if k == "List":
        return r.element_type.__name__
    if k == "Module":
        return ",".join(r.requirements["layer_name"].architectures or [])
    if k == "Layer":
        return ",".join(r.architectures or []) + ";" + ",".join(r.oses or [])
    if k == "Choice":
        return json.dumps(r.choices)
    return ""


plugin_list = framework.list_plugins()
out = []
for name in sorted(plugin_list):
    cls = plugin_list[name]
    reqs = cls.get_requirements()
    if not reqs:
        # a plugin without requirements still gets a row (kind None) so the table lists it
        out.append("\t".join([name, "", "None", "1", "null", "", "null"]))
    for r in reqs:
        k = kind_of(r)
        row = [name, r.name, k, "1" if r.optional else "0", default_json(r.default), extra_of(r, k),
               json.dumps(r.description)]
        for f in row:
            if "\t" in f or "\n" in f:
                raise SystemExit(f"field with a tab/newline: {row}")
        out.append("\t".join(row))

sys.stdout.write("# generated by bench/scripts/py_plugin_reqs.py from python volatility3 "
                 + framework.constants.PACKAGE_VERSION + "; do not edit\n")
sys.stdout.write("# plugin\tname\tkind\toptional\tdefault\textra\tdescription\n")
sys.stdout.write("\n".join(out) + "\n")
