//! windows plugins.

use crate::plugins::Plugin;

pub mod bigpools;
pub mod callbacks;
pub mod cmdline;
pub mod cmdscan;
pub mod consoles;
pub mod crashinfo;
pub mod debugregisters;
pub mod deskscan;
pub mod desktops;
pub mod devicetree;
pub mod dlllist;
pub mod driverirp;
pub mod drivermodule;
pub mod driverscan;
pub mod dumpfiles;
pub mod envars;
pub mod etwpatch;
pub mod filescan;
pub mod getservicesids;
pub mod getsids;
pub mod handles;
pub mod iat;
pub mod info;
pub mod joblinks;
pub mod kpcrs;
pub mod malware;
pub mod mbrscan;
pub mod memmap;
pub mod mftscan;
pub mod modscan;
pub mod modules;
pub mod mutantscan;
pub mod netscan;
pub mod netstat;
pub mod orphan_kernel_threads;
pub mod pe_symbols;
pub mod pedump;
pub mod poolscanner;
pub mod privileges;
pub mod pslist;
pub mod psscan;
pub mod pstree;
pub mod registry;
pub mod sessions;
pub mod shimcachemem;
pub mod sids;
pub mod ssdt;
pub mod statistics;
pub mod strings;
pub mod suspended_threads;
pub mod symlinkscan;
pub mod thrdscan;
pub mod threads;
pub mod timers;
pub mod truecrypt;
pub mod unloadedmodules;
pub mod vadinfo;
pub mod vadwalk;
pub mod verinfo;
pub mod virtmap;
pub mod windows;
pub mod windowstations;

pub fn register(v: &mut Vec<&'static dyn Plugin>) {
    v.push(&bigpools::BigPools);
    v.push(&callbacks::Callbacks);
    v.push(&cmdline::CmdLine);
    v.push(&cmdscan::CmdScan);
    v.push(&consoles::Consoles);
    v.push(&crashinfo::Crashinfo);
    v.push(&debugregisters::DebugRegisters);
    v.push(&deskscan::DeskScan);
    v.push(&desktops::Desktops);
    v.push(&devicetree::DeviceTree);
    v.push(&dlllist::DllList);
    v.push(&driverirp::DriverIrp);
    v.push(&drivermodule::DriverModule);
    v.push(&driverscan::DriverScan);
    v.push(&dumpfiles::DumpFiles);
    v.push(&envars::Envars);
    v.push(&etwpatch::EtwPatch);
    v.push(&filescan::FileScan);
    v.push(&getservicesids::GetServiceSIDs);
    v.push(&getsids::GetSIDs);
    v.push(&handles::Handles);
    v.push(&iat::IAT);
    v.push(&info::Info);
    v.push(&joblinks::JobLinks);
    v.push(&kpcrs::KPCRs);
    v.push(&malware::drivermodule::DriverModule);
    v.push(&mbrscan::MBRScan);
    v.push(&memmap::Memmap);
    v.push(&mftscan::MFTScan);
    v.push(&mftscan::ADS);
    v.push(&mftscan::ResidentData);
    v.push(&modscan::ModScan);
    v.push(&modules::Modules);
    v.push(&mutantscan::MutantScan);
    v.push(&netscan::NetScan);
    v.push(&netstat::NetStat);
    v.push(&orphan_kernel_threads::Threads);
    v.push(&pe_symbols::PESymbols);
    v.push(&pedump::PEDump);
    v.push(&poolscanner::PoolScanner);
    v.push(&privileges::Privs);
    v.push(&pslist::PsList);
    v.push(&psscan::PsScan);
    v.push(&pstree::PsTree);
    v.push(&sessions::Sessions);
    v.push(&shimcachemem::ShimcacheMem);
    v.push(&ssdt::Ssdt);
    v.push(&statistics::Statistics);
    v.push(&strings::Strings);
    v.push(&suspended_threads::SuspendedThreads);
    v.push(&symlinkscan::SymlinkScan);
    v.push(&thrdscan::ThrdScan);
    v.push(&threads::Threads);
    v.push(&timers::Timers);
    v.push(&truecrypt::Passphrase);
    v.push(&unloadedmodules::UnloadedModules);
    v.push(&vadinfo::VadInfo);
    v.push(&vadwalk::VadWalk);
    v.push(&verinfo::VerInfo);
    v.push(&virtmap::VirtMap);
    v.push(&windows::Windows);
    v.push(&windowstations::WindowStations);
    registry::register(v);
}
