//! windows plugins.

use crate::plugins::Plugin;

pub mod bigpools;
pub mod callbacks;
pub mod cmdline;
pub mod debugregisters;
pub mod devicetree;
pub mod dlllist;
pub mod driverirp;
pub mod drivermodule;
pub mod driverscan;
pub mod envars;
pub mod filescan;
pub mod getservicesids;
pub mod getsids;
pub mod handles;
pub mod hollowprocesses;
pub mod info;
pub mod joblinks;
pub mod kpcrs;
pub mod ldrmodules;
pub mod malfind;
pub mod malware;
pub mod memmap;
pub mod modscan;
pub mod modules;
pub mod mutantscan;
pub mod orphan_kernel_threads;
pub mod poolscanner;
pub mod privileges;
pub mod processghosting;
pub mod pslist;
pub mod psscan;
pub mod pstree;
pub mod psxview;
pub mod registry;
pub mod sessions;
pub mod shimcachemem;
pub mod sids;
pub mod ssdt;
pub mod statistics;
pub mod strings;
pub mod suspended_threads;
pub mod suspicious_threads;
pub mod svcdiff;
pub mod svclist;
pub mod svcscan;
pub mod symlinkscan;
pub mod thrdscan;
pub mod thread_pe_symbols;
pub mod threads;
pub mod timers;
pub mod unloadedmodules;
pub mod vadinfo;
pub mod vadwalk;
pub mod virtmap;

pub fn register(v: &mut Vec<&'static dyn Plugin>) {
    v.push(&bigpools::BigPools);
    v.push(&callbacks::Callbacks);
    v.push(&cmdline::CmdLine);
    v.push(&debugregisters::DebugRegisters);
    v.push(&devicetree::DeviceTree);
    v.push(&dlllist::DllList);
    v.push(&driverirp::DriverIrp);
    v.push(&drivermodule::DriverModule);
    v.push(&driverscan::DriverScan);
    v.push(&envars::Envars);
    v.push(&filescan::FileScan);
    v.push(&getservicesids::GetServiceSIDs);
    v.push(&getsids::GetSIDs);
    v.push(&handles::Handles);
    v.push(&hollowprocesses::HollowProcesses);
    v.push(&info::Info);
    v.push(&joblinks::JobLinks);
    v.push(&kpcrs::KPCRs);
    v.push(&ldrmodules::LdrModules);
    v.push(&malfind::Malfind);
    v.push(&malware::drivermodule::DriverModule);
    v.push(&memmap::Memmap);
    v.push(&modscan::ModScan);
    v.push(&modules::Modules);
    v.push(&mutantscan::MutantScan);
    v.push(&orphan_kernel_threads::Threads);
    v.push(&poolscanner::PoolScanner);
    v.push(&privileges::Privs);
    v.push(&processghosting::ProcessGhosting);
    v.push(&pslist::PsList);
    v.push(&psscan::PsScan);
    v.push(&pstree::PsTree);
    v.push(&psxview::PsXView);
    v.push(&sessions::Sessions);
    v.push(&shimcachemem::ShimcacheMem);
    v.push(&ssdt::Ssdt);
    v.push(&statistics::Statistics);
    v.push(&strings::Strings);
    v.push(&suspended_threads::SuspendedThreads);
    v.push(&suspicious_threads::SuspiciousThreads);
    v.push(&svcdiff::SvcDiff);
    v.push(&svclist::SvcList);
    v.push(&svcscan::SvcScan);
    v.push(&symlinkscan::SymlinkScan);
    v.push(&thrdscan::ThrdScan);
    v.push(&threads::Threads);
    v.push(&timers::Timers);
    v.push(&unloadedmodules::UnloadedModules);
    v.push(&vadinfo::VadInfo);
    v.push(&vadwalk::VadWalk);
    v.push(&virtmap::VirtMap);
    malware::register(v);
    registry::register(v);
}
