//! Differential tests of the CLI against python volatility3 (fixtures generated by
//! `bench/scripts/cli_fixtures.py`): every python plugin is recreated as a fake plugin with the
//! same name, docstring and CLI-visible requirements; each recorded argv is replayed through
//! `cli::run` and stdout / stderr / exit status are compared.

use super::*;
use crate::renderers::{Column, RowSink};
use std::sync::OnceLock;

struct Fake {
    name: &'static str,
    doc: &'static str,
    reqs: Vec<Requirement>,
}

impl Plugin for Fake {
    fn name(&self) -> &'static str {
        self.name
    }
    fn description(&self) -> &'static str {
        self.doc
    }
    fn requirements(&self) -> Vec<Requirement> {
        self.reqs.clone()
    }
    fn run(&self, _ctx: &Context, _cfg: &Config, out: &mut dyn RowSink) -> crate::error::Result<()> {
        out.begin(vec![Column::new("A", crate::renderers::ColType::Int)])
    }
}

fn leak(s: &str) -> &'static str {
    Box::leak(s.to_string().into_boxed_str())
}

fn fixture(name: &str) -> Json {
    let p = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    json::parse(&std::fs::read_to_string(&p).unwrap()).unwrap()
}

fn default_value(j: &Json) -> Option<ConfigValue> {
    match j {
        Json::Null => None,
        Json::Obj(_) => {
            let h = j.get("bytes").unwrap().as_str().unwrap();
            Some(ConfigValue::Bytes((0..h.len()).step_by(2).map(|i| u8::from_str_radix(&h[i..i + 2], 16).unwrap()).collect()))
        }
        other => json_to_cv(other),
    }
}

struct Fixtures {
    plugins: Vec<&'static dyn Plugin>,
    meta: Json,
}

fn fixtures() -> &'static Fixtures {
    static F: OnceLock<Fixtures> = OnceLock::new();
    F.get_or_init(|| {
        let meta = fixture("cli_plugins.json");
        let mut plugins: Vec<&'static dyn Plugin> = Vec::new();
        for p in meta.get("plugins").unwrap().as_arr() {
            let reqs = p
                .get("requirements")
                .unwrap()
                .as_arr()
                .iter()
                .map(|r| {
                    let kind = match r.get("kind").unwrap().as_str().unwrap() {
                        "bool" => ReqKind::Bool,
                        "int" => ReqKind::Int,
                        "str" => ReqKind::Str,
                        "uri" => ReqKind::Uri,
                        "bytes" => ReqKind::Bytes,
                        "list_int" => ReqKind::ListInt,
                        "list_str" => ReqKind::ListStr,
                        "choice" => ReqKind::Choice(
                            r.get("choices").unwrap().as_arr().iter().map(|c| leak(c.as_str().unwrap())).collect(),
                        ),
                        k => panic!("{k}"),
                    };
                    Requirement {
                        name: leak(r.get("name").unwrap().as_str().unwrap()),
                        description: leak(r.get("description").and_then(|d| d.as_str()).unwrap_or("")),
                        kind,
                        default: default_value(r.get("default").unwrap()),
                        optional: r.get("optional") == Some(&Json::Bool(true)),
                    }
                })
                .collect();
            let fake = Fake {
                name: leak(p.get("name").unwrap().as_str().unwrap()),
                doc: leak(p.get("doc").and_then(|d| d.as_str()).unwrap_or("")),
                reqs,
            };
            plugins.push(Box::leak(Box::new(fake)));
        }
        Fixtures { plugins, meta }
    })
}

fn settings(base: &str, columns: usize) -> Settings {
    Settings {
        dump_args: true,
        no_system_defaults: true,
        cache_path: Some(format!("{base}/cache/volatility3")),
        cwd: Some(base.to_string()),
        columns: Some(columns),
        color: Some(false),
        interactive: Some(false),
    }
}

fn run_case(argv: &[&str], base: &str, columns: usize) -> (String, String, i32) {
    let mut full = vec!["vol.py".to_string()];
    full.extend(argv.iter().map(|s| s.to_string()));
    let mut out = Vec::new();
    let mut err = Vec::new();
    let code = run(&full, &fixtures().plugins, &mut out, &mut err, &settings(base, columns));
    (String::from_utf8(out).unwrap(), String::from_utf8(err).unwrap(), code)
}

fn prepare_sandbox(cases: &Json) -> String {
    let base = cases.get("base").unwrap().as_str().unwrap().to_string();
    std::fs::create_dir_all(format!("{base}/home")).unwrap();
    std::fs::create_dir_all(format!("{base}/cache/volatility3")).unwrap();
    if let Some(Json::Obj(files)) = cases.get("files") {
        for (path, content) in files {
            std::fs::write(path, content.as_str().unwrap()).unwrap();
        }
    }
    base
}

/// python-only noise we do not reproduce on stderr (logging, tracebacks)
fn stderr_comparable(e: &str) -> bool {
    !(e.contains("INFO ") || e.contains("DEBUG") || e.contains("WARNING") || e.contains("Traceback") || e.contains("DETAIL"))
}

#[test]
fn python_cli_cases_match() {
    let cases = fixture("cli_cases.json");
    let base = prepare_sandbox(&cases);
    let mut bad = Vec::new();
    let all = cases.get("cases").unwrap().as_arr();
    for c in all {
        let argv: Vec<&str> = c.get("argv").unwrap().as_arr().iter().map(|a| a.as_str().unwrap()).collect();
        let columns = match c.get("columns") {
            Some(Json::Int(i)) => *i as usize,
            _ => 80,
        };
        let want_out = c.get("out").unwrap().as_str().unwrap();
        let want_err = c.get("err").unwrap().as_str().unwrap();
        let want_code = match c.get("code") {
            Some(Json::Int(i)) => *i as i32,
            _ => panic!(),
        };
        let (out, err, code) = run_case(&argv, &base, columns);
        let err_ok = !stderr_comparable(want_err) || err == want_err;
        if out != want_out || code != want_code || !err_ok {
            bad.push(format!(
                "argv={argv:?} columns={columns}\n  code want {want_code} got {code}\n--- stdout want\n{want_out}--- stdout got\n{out}--- stderr want\n{want_err}--- stderr got\n{err}"
            ));
        }
    }
    assert!(bad.is_empty(), "{} of {} cli cases differ:\n{}", bad.len(), all.len(), bad.join("\n==========\n"));
}

#[test]
fn python_plugin_help_matches() {
    let f = fixtures();
    let cases = fixture("cli_cases.json");
    let base = prepare_sandbox(&cases);
    let mut bad = Vec::new();
    let plugins = f.meta.get("plugins").unwrap().as_arr();
    for p in plugins {
        let name = p.get("name").unwrap().as_str().unwrap();
        let help = p.get("help").unwrap();
        let has_required =
            p.get("requirements").unwrap().as_arr().iter().any(|r| r.get("optional") == Some(&Json::Bool(false)));
        if has_required {
            // the real CLI errors before `-h` is seen (python too, see cli_cases); compare the
            // subparser's help text itself
            help::set_overrides(Some(80), Some(false));
            let mut parser = base_parser("vol.py", &base, &format!("{base}/cache/volatility3"));
            add_late_arguments(&mut parser, "vol.py", &f.plugins);
            let sub = (parser.sub_factory.as_ref().unwrap())(name);
            let got = sub.format_help();
            help::set_overrides(None, None);
            if got != help.get("out").unwrap().as_str().unwrap() {
                bad.push(format!("{name}\n--- want\n{}--- got\n{got}", help.get("out").unwrap().as_str().unwrap()));
            }
            continue;
        }
        let (out, err, code) = run_case(&[name, "-h"], &base, 80);
        let want = format!("{}\n{}", crate::VERSION_BANNER, help.get("out").unwrap().as_str().unwrap());
        let want_code = match help.get("code") {
            Some(Json::Int(i)) => *i as i32,
            _ => 0,
        };
        if out != want || code != want_code || err != help.get("err").unwrap().as_str().unwrap() {
            bad.push(format!("{name}\n--- want\n{want}--- got\n{out}{err}"));
        }
    }
    assert!(bad.is_empty(), "{} of {} plugin helps differ:\n{}", bad.len(), plugins.len(), bad.join("\n==========\n"));
}

/// In-process cost of the CLI with all 197 python plugins registered (no exec / dynamic loading):
///   cargo test --profile fast bench_cli -- --ignored --nocapture
#[test]
#[ignore]
fn bench_cli() {
    let cases = fixture("cli_cases.json");
    let base = prepare_sandbox(&cases);
    let img = format!("{base}/image.raw");
    let runs: [(&str, Vec<&str>); 4] = [
        ("parse -f IMG windows.pslist --pid 4 --dump", vec!["-q", "-f", &img, "windows.pslist", "--pid", "4", "--dump"]),
        ("-h (197 plugins)", vec!["-h"]),
        ("windows.pslist -h", vec!["windows.pslist", "-h"]),
        ("error: pslist ambiguous", vec!["pslist"]),
    ];
    for (label, argv) in runs {
        let n = 2000;
        let start = std::time::Instant::now();
        for _ in 0..n {
            let _ = run_case(&argv, &base, 80);
        }
        let dt = start.elapsed();
        println!("{label:>45}: {:>7.1} us/run", dt.as_secs_f64() * 1e6 / n as f64);
    }
}

#[test]
#[ignore]
fn bench_cli_phases() {
    let cases = fixture("cli_cases.json");
    let base = prepare_sandbox(&cases);
    let img = format!("{base}/image.raw");
    let plugins = &fixtures().plugins;
    let n = 5000;
    let t = std::time::Instant::now();
    for _ in 0..n {
        let mut p = base_parser("vol.py", &base, "/c");
        add_late_arguments(&mut p, "vol.py", plugins);
        std::hint::black_box(&p);
    }
    println!("build parsers: {:.2} us", t.elapsed().as_secs_f64() * 1e6 / n as f64);
    let mut p = base_parser("vol.py", &base, "/c");
    add_late_arguments(&mut p, "vol.py", plugins);
    let args: Vec<String> = ["-q", "-f", img.as_str(), "windows.pslist", "--pid", "4", "--dump"].iter().map(|s| s.to_string()).collect();
    let t = std::time::Instant::now();
    for _ in 0..n {
        std::hint::black_box(p.parse_known_args(&args).ok());
    }
    println!("one full parse: {:.2} us", t.elapsed().as_secs_f64() * 1e6 / n as f64);
    let bp = base_parser("vol.py", &base, "/c");
    let t = std::time::Instant::now();
    for _ in 0..n {
        std::hint::black_box(bp.parse_known_args(&args).ok());
    }
    println!("base parse: {:.2} us", t.elapsed().as_secs_f64() * 1e6 / n as f64);
    let t = std::time::Instant::now();
    for _ in 0..n {
        std::hint::black_box(current_dir());
        std::hint::black_box(path_exists(&img));
    }
    println!("cwd+stat: {:.2} us", t.elapsed().as_secs_f64() * 1e6 / n as f64);
}
