#!/bin/sh
# Linker wrapper (see .cargo/config.toml): links exactly like rustc's default `cc` invocation, plus
# hot-text ordering for the release `vol` binary.
#
# .cargo/symbol-order.txt lists the functions a warm run executes (demangled, so without the
# crate hashes that change with every toolchain, version or profile tweak), hottest first. It is
# generated by bench/scripts/gen-symbol-order.sh. Here the names are translated to the mangled
# symbols of the object being linked and handed to lld (--symbol-ordering-file), which then
# places those functions at the start of .text: ~1 MB of hot code instead of pages spread over
# the whole 10 MB text, i.e. fewer page faults and iTLB misses on every run.
#
# The ordering only moves functions around, so it can never change behaviour: a stale list,
# a missing file, a missing `nm` or any failure here just links without it (a bit slower).
# RSVOL_SYMBOL_ORDER=0 turns it off; RSVOL_SYMBOL_ORDER=<file> uses another list.
CC=${RSVOL_LINK_CC:-cc}

# only for the fat-LTO `vol` executable (a single Rust object, not in a response file)
out= objs= nobj=0 prev=
for a in "$@"; do
    case $a in
        @*) exec "$CC" "$@" ;;
        *.rcgu.o) objs=$a; nobj=$((nobj + 1)) ;;
    esac
    [ "$prev" = "-o" ] && out=$a
    prev=$a
done
case ${out##*/} in
    vol | vol-*) ;;
    *) exec "$CC" "$@" ;;
esac
order=${RSVOL_SYMBOL_ORDER:-$(dirname "$0")/symbol-order.txt}
if [ "$order" = 0 ] || [ "$nobj" != 1 ] || [ ! -s "$order" ] || ! command -v nm > /dev/null 2>&1; then
    exec "$CC" "$@"
fi

tmp=$out.symorder
# mangled and demangled names of the object's defined symbols, in the same (symbol table) order
if nm -p --defined-only "$objs" 2> /dev/null | cut -d' ' -f3- > "$tmp.m" &&
    nm -p --defined-only -C "$objs" 2> /dev/null | cut -d' ' -f3- > "$tmp.d" &&
    [ -s "$tmp.m" ] &&
    paste "$tmp.d" "$tmp.m" |
    awk -F '\t' 'NR == FNR { if (NF == 2) { m[$1] = ($1 in m) ? m[$1] "\n" $2 : $2 } next }
                 /^#/ || $0 == "" || ($0 in seen) { next }
                 { seen[$0] = 1; print(($0 in m) ? m[$0] : $0) }' - "$order" > "$tmp" 2> /dev/null &&
    [ -s "$tmp" ]; then
    "$CC" "$@" -Wl,--symbol-ordering-file="$tmp" -Wl,--no-warn-symbol-ordering
    st=$?
    if [ $st != 0 ]; then
        # never fail a build because of the ordering
        "$CC" "$@"
        st=$?
    fi
else
    "$CC" "$@"
    st=$?
fi
rm -f "$tmp" "$tmp.m" "$tmp.d"
exit $st
