//! 32-bit ARM instruction spec (generated by bench/scripts/gen_arm32_spec.py from probing the
//! capstone 5 oracle; grammar in bench/scripts/arm_spec.py). DO NOT EDIT BY HAND.

pub(crate) const SPEC: &str = r#"
F	cond
"#;
