//! Differential tests against Python `hashlib` / pycryptodome (`Crypto.Cipher`).
//!
//! `vectors.rs` is generated by `gen_vectors.py` (kept alongside this file) and
//! embeds a few hundred small (key, iv, data) -> expected-output vectors, hex
//! encoded, produced by the same `bench/venv` Python interpreter used to
//! generate volatility3's reference outputs. This file only
//! decodes hex and asserts equality; it never talks to Python at test time.
//!
//! Regenerate after any algorithmic change with:
//! `bench/venv/bin/python3 src/crypto/gen_vectors.py > src/crypto/vectors.rs`

use super::vectors::*;
use super::{aes::Aes, des::Des, hmac, md5, rc4, sha1, sha256};

fn unhex(s: &str) -> Vec<u8> {
    if s.is_empty() {
        return Vec::new();
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

#[test]
fn md5_matches_hashlib() {
    for (input, expect) in MD5_VECTORS {
        assert_eq!(hex(&md5::digest(&unhex(input))), *expect, "input={input}");
    }
}

#[test]
fn sha1_matches_hashlib() {
    for (input, expect) in SHA1_VECTORS {
        assert_eq!(hex(&sha1::digest(&unhex(input))), *expect, "input={input}");
    }
}

#[test]
fn sha256_matches_hashlib() {
    for (input, expect) in SHA256_VECTORS {
        assert_eq!(
            hex(&sha256::digest(&unhex(input))),
            *expect,
            "input={input}"
        );
    }
}

#[test]
fn hmac_md5_matches_pycryptodome() {
    for (key, msg, expect) in HMAC_MD5_VECTORS {
        assert_eq!(hex(&hmac::hmac_md5(&unhex(key), &unhex(msg))), *expect);
    }
}

#[test]
fn hmac_sha1_matches_python_hmac() {
    for (key, msg, expect) in HMAC_SHA1_VECTORS {
        assert_eq!(hex(&hmac::hmac_sha1(&unhex(key), &unhex(msg))), *expect);
    }
}

#[test]
fn hmac_sha256_matches_python_hmac() {
    for (key, msg, expect) in HMAC_SHA256_VECTORS {
        assert_eq!(hex(&hmac::hmac_sha256(&unhex(key), &unhex(msg))), *expect);
    }
}

#[test]
fn rc4_matches_pycryptodome() {
    for (key, data, expect) in RC4_VECTORS {
        assert_eq!(hex(&rc4::rc4(&unhex(key), &unhex(data))), *expect);
    }
}

#[test]
fn des_single_block_matches_pycryptodome() {
    for (key, pt, expect) in DES_VECTORS {
        let key: [u8; 8] = unhex(key).try_into().unwrap();
        let mut block: [u8; 8] = unhex(pt).try_into().unwrap();
        let des = Des::new(&key);
        des.encrypt_block(&mut block);
        assert_eq!(hex(&block), *expect);
        // And decrypting the ciphertext must round-trip.
        des.decrypt_block(&mut block);
        assert_eq!(hex(&block), *pt);
    }
}

#[test]
fn des_ecb_multiblock_matches_pycryptodome() {
    for (key, pt, expect) in DES_ECB_MULTIBLOCK_VECTORS {
        let key: [u8; 8] = unhex(key).try_into().unwrap();
        let des = Des::new(&key);
        let ct = des.ecb_encrypt(&unhex(pt)).unwrap();
        assert_eq!(hex(&ct), *expect);
        let back = des.ecb_decrypt(&ct).unwrap();
        assert_eq!(hex(&back), *pt);
    }
}

#[test]
fn des_key_expansion_matches_reference_algorithm() {
    for (s, expect) in DES_KEY_EXPANSION_VECTORS {
        let s: [u8; 7] = unhex(s).try_into().unwrap();
        assert_eq!(hex(&super::des::key_from_7_bytes(&s)), *expect);
    }
}

#[test]
fn aes_ecb_matches_pycryptodome() {
    for (key, pt, expect) in AES_ECB_VECTORS {
        let key = unhex(key);
        let aes = Aes::new(&key).unwrap();
        let ct = aes.ecb_decrypt_with_iv(&[0u8; 16], &unhex(expect)); // decrypt path
        assert_eq!(hex(&ct), *pt);

        // Also check the block-level encrypt path block by block.
        let pt_bytes = unhex(pt);
        let mut out = Vec::new();
        for chunk in pt_bytes.chunks(16) {
            let mut block = [0u8; 16];
            block.copy_from_slice(chunk);
            aes.encrypt_block(&mut block);
            out.extend_from_slice(&block);
        }
        assert_eq!(hex(&out), *expect);
    }
}

#[test]
fn aes_cbc_matches_pycryptodome() {
    for (key, iv, ct, pt) in AES_CBC_VECTORS {
        let key = unhex(key);
        let iv: [u8; 16] = unhex(iv).try_into().unwrap();
        let aes = Aes::new(&key).unwrap();
        let decrypted = aes.cbc_decrypt(&iv, &unhex(ct)).unwrap();
        assert_eq!(hex(&decrypted), *pt);
        let encrypted = aes.cbc_encrypt(&iv, &unhex(pt)).unwrap();
        assert_eq!(hex(&encrypted), *ct);
    }
}

#[test]
fn aes_chunked_fixed_iv_matches_lsadump_pattern() {
    // lsadump.py's decrypt_aes: a fresh cipher object per 16-byte chunk, so the
    // IV never advances. NOT the pattern cachedump.py uses (see below).
    for (key, iv, ct, pt) in AES_CHUNKED_FIXED_IV_VECTORS {
        let key = unhex(key);
        let iv: [u8; 16] = unhex(iv).try_into().unwrap();
        let aes = Aes::new(&key).unwrap();
        let decrypted = aes.ecb_decrypt_with_iv(&iv, &unhex(ct));
        assert_eq!(hex(&decrypted), *pt);
    }
}

#[test]
fn aes_cbc_matches_cachedump_reused_cipher_pattern() {
    // cachedump.py's decrypt_hash (non-XP): ONE cipher object reused across
    // chunks via repeated .decrypt() calls -> pycryptodome keeps CBC chaining
    // state across those calls, so this is real chained CBC over the whole
    // buffer, not the lsadump.py fixed-IV-per-chunk pattern above. Using
    // `ecb_decrypt_with_iv` here would be wrong.
    for (key, iv, ct, pt) in AES_CACHEDUMP_REUSED_CIPHER_VECTORS {
        let key = unhex(key);
        let iv: [u8; 16] = unhex(iv).try_into().unwrap();
        let aes = Aes::new(&key).unwrap();
        let decrypted = aes.cbc_decrypt(&iv, &unhex(ct)).unwrap();
        assert_eq!(hex(&decrypted), *pt);
    }
}
