#!/usr/bin/env python3
"""Generates differential test vectors against pycryptodome/hashlib for fastvol's
crypto module, as a small embedded Rust source file (hex-encoded tuples)."""
import hashlib
import hmac
import random

from Crypto.Cipher import AES, DES, ARC4

random.seed(1234567891)


def rb(n):
    return bytes(random.randrange(256) for _ in range(n))


def h(b):
    return b.hex()


lines = []
lines.append(
    "// Generated by gen_vectors.py against Python hashlib/pycryptodome. Do not hand-edit."
)
lines.append(
    "// Regenerate with: bench/venv/bin/python3 src/crypto/gen_vectors.py > src/crypto/vectors.rs"
)
lines.append("#![allow(clippy::all)]")
lines.append("")

# --- MD5 / SHA1 / SHA256: (input_hex, digest_hex) ---
for name, algo in (("MD5", hashlib.md5), ("SHA1", hashlib.sha1), ("SHA256", hashlib.sha256)):
    lines.append(f"pub const {name}_VECTORS: &[(&str, &str)] = &[")
    for n in [0, 1, 2, 5, 15, 16, 17, 55, 56, 63, 64, 65, 100, 137]:
        data = rb(n)
        lines.append(f'    ("{h(data)}", "{algo(data).hexdigest()}"),')
    lines.append("];")
    lines.append("")

# --- HMAC: (key_hex, msg_hex, mac_hex) ---
for name, algo in (("MD5", hashlib.md5), ("SHA1", hashlib.sha1), ("SHA256", hashlib.sha256)):
    lines.append(f"pub const HMAC_{name}_VECTORS: &[(&str, &str, &str)] = &[")
    for _ in range(15):
        klen = random.choice([0, 1, 8, 16, 20, 32, 64, 65, 100])
        mlen = random.choice([0, 1, 13, 55, 64, 65, 130])
        key = rb(klen)
        msg = rb(mlen)
        mac = hmac.new(key, msg, algo).hexdigest()
        lines.append(f'    ("{h(key)}", "{h(msg)}", "{mac}"),')
    lines.append("];")
    lines.append("")

# --- RC4: (key_hex, plaintext_hex, ciphertext_hex) ---
lines.append("pub const RC4_VECTORS: &[(&str, &str, &str)] = &[")
for _ in range(20):
    klen = random.choice([1, 5, 8, 16, 20, 32, 64, 100])
    dlen = random.choice([0, 1, 7, 8, 15, 16, 17, 31, 100])
    key = rb(klen)
    data = rb(dlen)
    ct = ARC4.new(key).encrypt(data)
    lines.append(f'    ("{h(key)}", "{h(data)}", "{h(ct)}"),')
lines.append("];")
lines.append("")

# --- DES: (key8_hex, plaintext8_hex, ciphertext8_hex) single-block ECB ---
lines.append("pub const DES_VECTORS: &[(&str, &str, &str)] = &[")
for _ in range(30):
    key = rb(8)
    pt = rb(8)
    ct = DES.new(key, DES.MODE_ECB).encrypt(pt)
    lines.append(f'    ("{h(key)}", "{h(pt)}", "{h(ct)}"),')
lines.append("];")
lines.append("")

# --- DES multi-block ECB: (key8_hex, plaintext_hex (multiple of 8), ciphertext_hex) ---
lines.append("pub const DES_ECB_MULTIBLOCK_VECTORS: &[(&str, &str, &str)] = &[")
for _ in range(10):
    key = rb(8)
    nblocks = random.choice([1, 2, 3, 5])
    pt = rb(8 * nblocks)
    ct = DES.new(key, DES.MODE_ECB).encrypt(pt)
    lines.append(f'    ("{h(key)}", "{h(pt)}", "{h(ct)}"),')
lines.append("];")
lines.append("")

# --- DES key expansion (SystemFunction005 / sidbytes_to_key): (7-byte-hex, 8-byte-key-hex) ---
# Mirrors volatility3's Hashdump.sidbytes_to_key exactly (odd_parity table + shifts),
# reimplemented here in Python from the same spec (independent from the Rust port) as
# an extra cross-check that key_from_7_bytes matches the documented algorithm.
ODD_PARITY_FORMULA = lambda b: (b | 1) if (bin(b >> 1).count("1") % 2 == 0) else (b & ~1)


def sidbytes_to_key(s: bytes) -> bytes:
    key = [
        s[0] >> 1,
        ((s[0] & 0x01) << 6) | (s[1] >> 2),
        ((s[1] & 0x03) << 5) | (s[2] >> 3),
        ((s[2] & 0x07) << 4) | (s[3] >> 4),
        ((s[3] & 0x0F) << 3) | (s[4] >> 5),
        ((s[4] & 0x1F) << 2) | (s[5] >> 6),
        ((s[5] & 0x3F) << 1) | (s[6] >> 7),
        s[6] & 0x7F,
    ]
    return bytes(ODD_PARITY_FORMULA(k << 1) for k in key)


lines.append("pub const DES_KEY_EXPANSION_VECTORS: &[(&str, &str)] = &[")
for _ in range(20):
    s = rb(7)
    lines.append(f'    ("{h(s)}", "{h(sidbytes_to_key(s))}"),')
lines.append("];")
lines.append("")

# --- AES ECB single/multi-block (all 3 key sizes): (key_hex, pt_hex, ct_hex) ---
lines.append("pub const AES_ECB_VECTORS: &[(&str, &str, &str)] = &[")
for _ in range(20):
    klen = random.choice([16, 24, 32])
    nblocks = random.choice([1, 1, 2, 3])
    key = rb(klen)
    pt = rb(16 * nblocks)
    ct = AES.new(key, AES.MODE_ECB).encrypt(pt)
    lines.append(f'    ("{h(key)}", "{h(pt)}", "{h(ct)}"),')
lines.append("];")
lines.append("")

# --- AES CBC (real chaining, single decrypt() call over the whole buffer):
# (key_hex, iv_hex, ciphertext_hex, plaintext_hex) ---
lines.append("pub const AES_CBC_VECTORS: &[(&str, &str, &str, &str)] = &[")
for _ in range(20):
    klen = random.choice([16, 24, 32])
    nblocks = random.choice([1, 1, 2, 3, 4])
    key = rb(klen)
    iv = rb(16)
    pt = rb(16 * nblocks)
    ct = AES.new(key, AES.MODE_CBC, iv).encrypt(pt)
    lines.append(f'    ("{h(key)}", "{h(iv)}", "{h(ct)}", "{h(pt)}"),')
lines.append("];")
lines.append("")


# --- AES "fresh cipher object created INSIDE the loop, once per 16-byte chunk,
# always with the SAME fixed IV" pattern. This is exactly (and *only*)
# lsadump.py's `decrypt_aes`:
#
#     for i in range(60, len(secret), 16):
#         aes = AES.new(aeskey, AES.MODE_CBC, b"\x00" * 16)   # <- re-created every iteration
#         data += aes.decrypt(buf)
#
# Because the cipher object is discarded and re-created every iteration, pycryptodome
# never advances its internal IV -- this is mathematically identical to plain ECB
# (verified empirically against pycryptodome below; with iv=0 the XOR is a no-op
# either way). (key_hex, iv_hex, ciphertext_hex, plaintext_hex); ciphertext may
# include a short zero-padded-by-the-plugin final chunk.
#
# IMPORTANT: cachedump.py's `decrypt_hash` (non-XP branch) looks superficially
# similar but is NOT this pattern -- it creates ONE `AES.new(...)` object *outside*
# the loop and calls `.decrypt()` on that *same* object once per chunk. pycryptodome
# keeps CBC state across repeated `.decrypt()` calls on one object, so that is real
# chained CBC over the whole buffer, equivalent to a single `cbc_decrypt` call -- see
# AES_CACHEDUMP_REUSED_CIPHER_VECTORS below, which reproduces cachedump.py's exact
# object-reuse loop and confirms it matches one-shot CBC.
def chunked_fixed_iv_decrypt(key, iv, data):
    out = b""
    for i in range(0, len(data), 16):
        buf = data[i : i + 16]
        if len(buf) < 16:
            buf = buf + b"\x00" * (16 - len(buf))
        out += AES.new(key, AES.MODE_CBC, iv).decrypt(buf)  # fresh object every iteration
    return out


lines.append("pub const AES_CHUNKED_FIXED_IV_VECTORS: &[(&str, &str, &str, &str)] = &[")
for _ in range(15):
    klen = random.choice([16, 24, 32])
    key = rb(klen)
    iv = random.choice([b"\x00" * 16, rb(16)])
    total_len = random.choice([16, 32, 48, 60])  # some not multiples of 16
    # Build "ciphertext" as random bytes (this models arbitrary encrypted secret
    # material read from the registry; we only need decrypt() to match).
    ct = rb(total_len)
    pt = chunked_fixed_iv_decrypt(key, iv, ct)
    lines.append(f'    ("{h(key)}", "{h(iv)}", "{h(ct)}", "{h(pt)}"),')
lines.append("];")
lines.append("")

# --- cachedump.py's ACTUAL pattern: ONE cipher object created before the loop,
# `.decrypt()` called once per 16-byte chunk on that SAME object. This is real
# chained CBC over the whole buffer -- confirmed by comparing against a single
# one-shot decrypt() call below. (key_hex, iv_hex, ciphertext_hex, plaintext_hex) ---
def cachedump_reused_cipher_decrypt(key, iv, data):
    aes = AES.new(key, AES.MODE_CBC, iv)  # created ONCE, outside the loop
    out = b""
    for i in range(0, len(data), 16):
        buf = data[i : i + 16]
        if len(buf) < 16:
            buf = buf + b"\x00" * (16 - len(buf))
        out += aes.decrypt(buf)  # same object every iteration -> IV advances
    return out


lines.append("pub const AES_CACHEDUMP_REUSED_CIPHER_VECTORS: &[(&str, &str, &str, &str)] = &[")
for _ in range(15):
    klen = random.choice([16, 24, 32])
    key = rb(klen)
    iv = rb(16)
    nblocks = random.choice([1, 2, 3, 4])
    ct = rb(16 * nblocks)  # block-aligned, as real registry cache entries are
    reused = cachedump_reused_cipher_decrypt(key, iv, ct)
    oneshot = AES.new(key, AES.MODE_CBC, iv).decrypt(ct)
    assert reused == oneshot, "cachedump reused-cipher pattern must equal one-shot CBC"
    lines.append(f'    ("{h(key)}", "{h(iv)}", "{h(ct)}", "{h(oneshot)}"),')
lines.append("];")
lines.append("")

print("\n".join(lines))
