#!/usr/bin/env python3
"""Build the README artwork in docs/assets from its sources.

Hand-written sources (edit these):
  mascot.svg     the ferret mark: a flat, frontal masked face; square, transparent, 32 px and up
  favicon.svg    the same face redrawn on a 32-unit pixel grid for 16 to 48 px
  wordmark.svg   the "fastvol" lettering for light backgrounds

Generated by this script (do not edit by hand):
  wordmark-dark.svg              the wordmark for dark backgrounds
  logo.svg, logo-dark.svg        mascot + wordmark, horizontal lockups
  benchmark.svg, benchmark-dark.svg
                                 the README's headline chart; every number is parsed from the
                                 headline tables of bench/vm/BENCHMARKS.md
  badges/*.svg                   static README badges (no external badge service)
  png/*.png                      previews, only with --png (needs a chromium on PATH)

Usage: python3 docs/assets/build.py [--png]

Standard library only. The mascot is the one source of the ferret; the wordmark is kept apart
from it so that the name can change without touching the mascot.
"""

import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
BENCHMARKS = os.path.join(ROOT, "bench", "vm", "BENCHMARKS.md")

COPPER = "#e0662b"
INK_LIGHT = "#1f2328"   # GitHub's light-theme text colour
INK_DARK = "#f0f6fc"    # GitHub's dark-theme text colour

FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif"


def read(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return f.read()


def write(name, text):
    path = os.path.join(HERE, name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def svg_body(text):
    """The markup inside the root <svg> element, without comments."""
    inner = re.search(r"<svg[^>]*>(.*)</svg>", text, re.S).group(1)
    inner = re.sub(r"<!--.*?-->", "", inner, flags=re.S)
    return "\n".join(line for line in inner.splitlines() if line.strip())


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# --------------------------------------------------------------------------------------------
# Wordmark and logo lockups

GENERATED = "<!-- Generated by docs/assets/build.py from mascot.svg and wordmark.svg. Do not edit. -->"


def build_logos():
    wordmark = read("wordmark.svg")
    dark = wordmark.replace(INK_LIGHT, INK_DARK)
    dark = dark.replace("Hand-written source for light backgrounds", "Dark-background variant, generated from wordmark.svg")
    write("wordmark-dark.svg", dark)

    mascot = svg_body(read("mascot.svg"))
    for name, ink in (("logo.svg", INK_LIGHT), ("logo-dark.svg", INK_DARK)):
        words = svg_body(wordmark.replace(INK_LIGHT, ink))
        # The mark (box x 11..117, y 16..112) at 0.74 is centred on the wordmark's ascender-to-
        # baseline span (y 37..100), 16 units of air before the "f" crossbar, 8 of margin all round.
        write(name, f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="-8 25 367 87" role="img" aria-label="fastvol">
{GENERATED}
<g id="mascot" transform="translate(-8.14 21.2) scale(.74)">
{mascot}
</g>
<g id="wordmark" transform="translate(100 0)">
{words}
</g>
</svg>
''')


# --------------------------------------------------------------------------------------------
# Headline benchmark chart


def parse_benchmarks():
    """{"Windows": (plugins, {row label: {column: cell}}), "Linux": ...} from the headline tables."""
    lines = open(BENCHMARKS, encoding="utf-8").read().splitlines()
    tables = {}
    for i, line in enumerate(lines):
        m = re.match(r"\| (Windows|Linux) \((\d+) plugins\) \|", line)
        if not m or m.group(1) in tables:
            continue
        header = [c.strip() for c in line.strip().strip("|").split("|")]
        rows = {}
        j = i + 2
        while j < len(lines) and lines[j].startswith("|"):
            cells = [c.strip() for c in lines[j].strip().strip("|").split("|")]
            rows[cells[0]] = dict(zip(header[1:], cells[1:]))
            j += 1
        tables[m.group(1)] = (int(m.group(2)), rows)
    for os_name in ("Windows", "Linux"):
        if os_name not in tables:
            sys.exit(f"build.py: no '| {os_name} (N plugins) |' headline table in {BENCHMARKS}")
    return tables


def seconds(cell):
    m = re.fullmatch(r"([\d,.]+) (s|ms)", cell.strip())
    if not m:
        sys.exit(f"build.py: cannot read a time from {cell!r}")
    v = float(m.group(1).replace(",", ""))
    return v / 1000 if m.group(2) == "ms" else v


def fmt_seconds(v):
    if v >= 1000:
        return f"{v:,.0f} s"
    if v >= 10:
        return f"{v:.1f} s"
    return f"{v:.2f} s"


def speedup(cell, which):
    """'463x / 69.2x' -> '463x' (which=0, total) or '69.2x' (which=1, geo-mean)."""
    return cell.split("/")[which].strip()


CHART_THEMES = {
    "light": dict(bg="#ffffff", border="#d1d9e0", text=INK_LIGHT, text2="#59636e", muted="#6e7781",
                  grid="#e6eaef", accent=COPPER, accent_soft="#f0a47c", other="#8c959f",
                  other_soft="#c5ccd4"),
    "dark": dict(bg="#0d1117", border="#30363d", text=INK_DARK, text2="#9198a1", muted="#7d8590",
                 grid="#21262d", accent=COPPER, accent_soft="#9c4a26", other="#848d97",
                 other_soft="#454c56"),
}

PANELS = (
    ("Windows", "Windows 11 x64, 5 GiB raw image"),
    ("Linux", "Ubuntu 24.04, Linux 6.8, 3 GiB ELF core"),
)


def build_chart():
    tables = parse_benchmarks()
    W = 840
    X_TOOL, X_RUN, X0, DECADE = 28, 164, 256, 112.0   # bars: 1 s at X0, 10x per DECADE px
    DECADES = 4                                     # 1 s .. 10,000 s
    ROW, BAR, GROUP_GAP = 22, 12, 8

    def x_of(v):
        return X0 + math.log10(v) * DECADE

    panels = []
    for os_name, image in PANELS:
        plugins, rows = tables[os_name]
        total = rows["total wall (sum of per-plugin best)"]
        speed = rows["speedup vs python: total / geo-mean"]
        py = seconds(total["python"])
        panels.append(dict(
            title=f"{image} · {plugins} plugins",
            tools=[
                ("python volatility3", "other", [("repeat run", py, f"{fmt_seconds(py)}  ({py / 60:.0f} min)", None)]),
                ("vol-rs", "other", [
                    ("first run", seconds(total["vol-rs cold"]), None, None),
                    ("repeat run", seconds(total["vol-rs warm"]), None, None)]),
                ("fastvol", "accent", [
                    ("first run", seconds(total["rsvol cold"]), None, speedup(speed["rsvol cold"], 0)),
                    ("repeat run", seconds(total["rsvol warm"]), None, speedup(speed["rsvol warm"], 0))]),
            ]))

    def render(theme):
        t = CHART_THEMES[theme]
        out = []
        y = 104
        desc = []
        grid_ticks = [10 ** k for k in range(DECADES + 1)]
        for p in panels:
            out.append(f'<text x="{X_TOOL}" y="{y}" class="h">{esc(p["title"])}</text>')
            top = y + 12
            ry = top
            rows_svg = []
            for tool, kind, runs in p["tools"]:
                for k, (run, v, label, factor) in enumerate(runs):
                    cy = ry + ROW / 2
                    if k == 0:
                        cls = "tool b" if kind == "accent" else "tool"
                        ty = ry + len(runs) * ROW / 2
                        rows_svg.append(f'<text x="{X_TOOL}" y="{ty + 4.5:.1f}" class="{cls}">{tool}</text>')
                    rows_svg.append(f'<text x="{X_RUN}" y="{cy + 4.5:.1f}" class="run">{run}</text>')
                    soft = run == "first run"
                    fill = t[kind + ("_soft" if soft else "")]
                    x1 = x_of(v)
                    r = 4
                    yb = cy - BAR / 2
                    rows_svg.append(
                        f'<path fill="{fill}" d="M{X0} {yb:.1f}H{x1 - r:.1f}A{r} {r} 0 0 1 {x1:.1f} {yb + r:.1f}'
                        f'V{yb + BAR - r:.1f}A{r} {r} 0 0 1 {x1 - r:.1f} {yb + BAR:.1f}H{X0}Z"/>')
                    text = label or fmt_seconds(v)
                    vcls = "val b" if kind == "accent" else "val"
                    extra = f'<tspan class="note" dx="8">{factor} faster than python</tspan>' if factor else ""
                    rows_svg.append(f'<text x="{x1 + 7:.1f}" y="{cy + 4.5:.1f}" class="{vcls}">{esc(text)}{extra}</text>')
                    desc.append(f"{p['title']}: {tool} {run} {fmt_seconds(v)}")
                    ry += ROW
                ry += GROUP_GAP
            bottom = ry - GROUP_GAP
            for tick in grid_ticks:
                gx = x_of(tick)
                out.append(f'<path d="M{gx:.1f} {top - 2}V{bottom + 2}" class="grid"/>')
            out.extend(rows_svg)
            y = bottom + 40
        axis_y = y - 18
        for tick in grid_ticks:
            out.append(f'<text x="{x_of(tick):.1f}" y="{axis_y}" class="tick" text-anchor="middle">{tick:,} s</text>')
        foot_y = axis_y + 34
        foot = [
            "Sum of the best wall-clock time of each plugin (5 runs; python 1 or 2), one process per plugin, image in the page cache.",
            "First run: the tool's caches emptied before every run. Repeat run: caches as the previous run left them. Source: bench/vm/BENCHMARKS.md",
        ]
        for k, line in enumerate(foot):
            out.append(f'<text x="{X_TOOL}" y="{foot_y + k * 17}" class="foot">{esc(line)}</text>')
        H = foot_y + 17 + 22
        title = "Total time to run the benchmark suite"
        head = [
            f'<rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="12" fill="{t["bg"]}" stroke="{t["border"]}"/>',
            f'<text x="{X_TOOL}" y="42" class="title">{title}</text>',
            f'<text x="{X_TOOL}" y="64" class="sub">Each plugin run once as its own process, and the times added up. Log scale: each gridline is 10x. Shorter is faster.</text>',
        ]
        style = f"""<style>
text{{font-family:{FONT};fill:{t['text']}}}
.title{{font-size:17px;font-weight:600}}
.sub{{font-size:12.5px;fill:{t['text2']}}}
.h{{font-size:13px;font-weight:600}}
.tool{{font-size:13px;fill:{t['text2']}}}
.run{{font-size:12px;fill:{t['muted']}}}
.val{{font-size:12px;fill:{t['text2']};paint-order:stroke;stroke:{t['bg']};stroke-width:5px;stroke-linejoin:round}}
.b{{font-weight:600;fill:{t['text']}}}
.note{{font-weight:400;fill:{t['muted']}}}
.tick{{font-size:11px;fill:{t['muted']}}}
.foot{{font-size:11px;fill:{t['muted']}}}
.grid{{stroke:{t['grid']};stroke-width:1;fill:none}}
</style>"""
        return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-labelledby="t d">\n'
                f"<!-- Generated by docs/assets/build.py from bench/vm/BENCHMARKS.md. Do not edit. -->\n"
                f'<title id="t">{title}</title>\n<desc id="d">{esc("; ".join(desc))}. Source: bench/vm/BENCHMARKS.md.</desc>\n'
                + style + "\n" + "\n".join(head + out) + "\n</svg>\n")

    write("benchmark.svg", render("light"))
    write("benchmark-dark.svg", render("dark"))


# --------------------------------------------------------------------------------------------
# Badges

# Advance widths (em) of Liberation Sans, which has Arial's metrics, for ASCII 32..126 and "·".
_CHARS = "".join(chr(c) for c in range(32, 127)) + "·"
_WIDTHS = [float(w) for w in (
    "0.278,0.278,0.355,0.556,0.556,0.889,0.667,0.191,0.333,0.333,0.389,0.584,0.278,0.333,0.278,0.278,"
    "0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.278,0.278,0.584,0.584,0.584,0.556,"
    "1.015,0.667,0.667,0.722,0.722,0.667,0.611,0.778,0.722,0.278,0.500,0.667,0.556,0.833,0.722,0.778,"
    "0.667,0.778,0.722,0.667,0.611,0.722,0.667,0.944,0.667,0.667,0.611,0.278,0.278,0.278,0.469,0.556,"
    "0.333,0.556,0.556,0.500,0.556,0.556,0.278,0.556,0.556,0.222,0.222,0.500,0.222,0.833,0.556,0.556,"
    "0.556,0.556,0.333,0.500,0.278,0.556,0.500,0.722,0.500,0.500,0.500,0.334,0.260,0.334,0.584,0.333"
).split(",")]
_WIDTH = dict(zip(_CHARS, _WIDTHS))


def text_width(s, size):
    return sum(_WIDTH.get(ch, 0.6) for ch in s) * size


BADGES = (
    ("volatility3", "volatility3", "2.28.2"),
    ("plugins", "plugins", "197"),
    ("parity", "parity", "1975/1975"),
    ("dependencies", "dependencies", "0"),
    ("images", "images", "windows · linux · macos"),
    ("license", "license", "VSL 1.0"),
)


def build_badges():
    size, h, pad = 11, 20, 7
    for name, label, value in BADGES:
        lw = round(text_width(label, size)) + 2 * pad
        vw = round(text_width(value, size)) + 2 * pad
        w = lw + vw
        tl = round(text_width(label, size), 1)
        tv = round(text_width(value, size), 1)
        write(f"badges/{name}.svg", f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{esc(label)}: {esc(value)}">
<title>{esc(label)}: {esc(value)}</title>
<clipPath id="r"><rect width="{w}" height="{h}" rx="4"/></clipPath>
<g clip-path="url(#r)">
<rect width="{lw}" height="{h}" fill="#30363d"/>
<rect x="{lw}" width="{vw}" height="{h}" fill="#b4491c"/>
</g>
<g fill="#fff" font-family="Helvetica Neue, Helvetica, Arial, Liberation Sans, sans-serif" font-size="{size}">
<text x="{pad}" y="14" textLength="{tl}" lengthAdjust="spacingAndGlyphs">{esc(label)}</text>
<text x="{lw + pad}" y="14" textLength="{tv}" lengthAdjust="spacingAndGlyphs">{esc(value)}</text>
</g>
</svg>
''')


# --------------------------------------------------------------------------------------------
# PNG previews


def render_pngs():
    chromium = shutil.which("chromium") or shutil.which("chromium-browser") or shutil.which("google-chrome")
    if not chromium:
        sys.exit("build.py: --png needs chromium on PATH")
    jobs = (
        # (output, svg, css width, css height, background, device scale)
        ("png/mascot-512.png", "mascot.svg", 512, 512, "transparent", 1),
        ("png/favicon-16.png", "favicon.svg", 16, 16, "transparent", 1),
        ("png/favicon-32.png", "favicon.svg", 32, 32, "transparent", 1),
        ("png/favicon-48.png", "favicon.svg", 48, 48, "transparent", 1),
        ("png/logo.png", "logo.svg", 734, 174, "#ffffff", 2),
        ("png/logo-dark.png", "logo-dark.svg", 734, 174, "#0d1117", 2),
        ("png/benchmark.png", "benchmark.svg", None, None, "transparent", 2),
        ("png/benchmark-dark.png", "benchmark-dark.svg", None, None, "transparent", 2),
    )
    with tempfile.TemporaryDirectory() as tmp:
        for out, svg, w, h, bg, scale in jobs:
            if w is None:
                m = re.search(r'width="(\d+)" height="(\d+)"', read(svg))
                w, h = int(m.group(1)), int(m.group(2))
            page = os.path.join(tmp, "page.html")
            with open(page, "w") as f:
                f.write(f'<!doctype html><html><head><style>html,body{{margin:0;background:{bg}}}'
                        f'img{{display:block;width:{w}px;height:{h}px}}</style></head>'
                        f'<body><img src="file://{os.path.join(HERE, svg)}"></body></html>')
            target = os.path.join(HERE, out)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            subprocess.run([chromium, "--headless=new", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
                            "--default-background-color=00000000", f"--force-device-scale-factor={scale}",
                            f"--window-size={w},{h}", f"--screenshot={target}", f"file://{page}"],
                           check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("wrote", os.path.relpath(target, ROOT))


def main():
    build_logos()
    build_chart()
    build_badges()
    if "--png" in sys.argv[1:]:
        render_pngs()


if __name__ == "__main__":
    main()
