#!/usr/bin/env python3
"""Build the README artwork in docs/assets from its sources.

Hand-written sources (edit these):
  mark.txt       the fastvol mark: the pixel "fv" on its tile, 24x16 ('#' glyph, '+' tile,
                 '.' transparent). The row count stays even: `fvol --version` prints the same
                 grid in a terminal with half blocks, two pixel rows per line (src/cli/banner.rs
                 includes this file).
  favicon.txt    the mark squeezed onto a 16x16 tile for favicons
  WORDMARK below the pixel-italic "fastvol" lettering (12 rows)

Generated by this script (do not edit by hand):
  mark.svg, favicon.svg          the grids as crisp SVG paths
  wordmark.svg, wordmark-dark.svg
                                 the lettering for light and dark backgrounds
  logo.svg, logo-dark.svg        mark + wordmark, horizontal lockups (a 16-row pixel grid: show them at
                                 whole multiples, 6x = the width/height the SVG declares, as in the README)
  benchmark.svg, benchmark-dark.svg
                                 the README's headline chart; every number is parsed from the
                                 headline tables of bench/vm/BENCHMARKS.md
  badges/*.svg                   static README badges (no external badge service)
  png/*.png                      previews, only with --png (needs a chromium on PATH)

Usage: python3 docs/assets/build.py [--png]

Standard library only.
"""

import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
BENCHMARKS = os.path.join(ROOT, "bench", "vm", "BENCHMARKS.md")

GLYPH = "#46e67a"       # phosphor green: the fv, and fastvol's colour on dark backgrounds
TILE = "#123020"        # the mark's tile
GREEN = "#1f9e57"       # the glyph green darkened for light backgrounds (3.4:1 on white)
GREEN_BADGE = "#178344" # badge values: white text at 4.8:1
INK_LIGHT = "#1f2328"   # GitHub's light-theme text colour
INK_DARK = "#f0f6fc"    # GitHub's dark-theme text colour

FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif"


def read(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return f.read()


def write(name, text):
    path = os.path.join(HERE, name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# --------------------------------------------------------------------------------------------
# Wordmark and logo lockups

GENERATED = "<!-- Generated by docs/assets/build.py from mark.txt / favicon.txt / WORDMARK. Do not edit. -->"

# The pixel-italic wordmark: one list of rows per letter, 12 rows, baseline = last row; each row
# is sheared right by 1 px per SHEAR rows above the baseline, letters TRACK px apart.
WORDMARK = {
    "f": ["..####", ".#####", ".##...", ".##...", "######", "######",
          ".##...", ".##...", ".##...", ".##...", ".##...", ".##..."],
    "a": ["", "", "", "", "######.", "#######", ".....##", ".######",
          "#######", "##...##", "#######", ".######"],
    "s": ["", "", "", "", ".######", "#######", "##.....", "######.",
          ".######", ".....##", "#######", "######."],
    "t": ["", ".##...", ".##...", ".##...", "######", "######",
          ".##...", ".##...", ".##...", ".##...", ".#####", "..####"],
    "v": ["", "", "", "", "##...##", "##...##", "##...##", "##...##",
          ".##.##.", ".##.##.", "..###..", "..###.."],
    "o": ["", "", "", "", ".#####.", "#######", "##...##", "##...##",
          "##...##", "##...##", "#######", ".#####."],
    "l": ["##"] * 12,
}
SHEAR = 4
TRACK = 2
GAP = 6  # between the mark and the wordmark


def read_grid(name):
    rows = [r.rstrip("\n") for r in read(name).splitlines() if r.strip()]
    if len({len(r) for r in rows}) != 1:
        sys.exit(f"build.py: {name}: rows of different lengths")
    if len(rows) % 2:
        sys.exit(f"build.py: {name}: the row count must be even (two pixel rows per terminal line)")
    return rows


def cells_of(rows, chars):
    return {(x, y) for y, r in enumerate(rows) for x, c in enumerate(r) if c in chars}


def pixel_path(cells, ox=0, oy=0):
    """Rectangles covering `cells`: horizontal runs, stacked where the next rows repeat them."""
    runs = {}
    for x, y in sorted(cells, key=lambda c: (c[1], c[0])):
        row = runs.setdefault(y, [])
        if row and row[-1][0] + row[-1][1] == x:
            row[-1][1] += 1
        else:
            row.append([x, 1])
    done, d = set(), []
    for y in sorted(runs):
        for x, w in runs[y]:
            if (x, w, y) in done:
                continue
            h = 1
            while [x, w] in runs.get(y + h, []):
                done.add((x, w, y + h))
                h += 1
            d.append(f"M{x + ox} {y + oy}h{w}v{h}h-{w}z")
    return "".join(d)


def pixel_svg(w, h, scale, body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w * scale}" '
            f'height="{h * scale}" role="img" aria-label="fastvol" shape-rendering="crispEdges">\n'
            f"{GENERATED}\n{body}</svg>\n")


def mark_body(rows, ox=0):
    return (f'<path fill="{TILE}" d="{pixel_path(cells_of(rows, "#+"), ox)}"/>\n'
            f'<path fill="{GLYPH}" d="{pixel_path(cells_of(rows, "#"), ox)}"/>\n')


def wordmark_cells():
    cells, x0, n = set(), 0, 12
    for ch in "fastvol":
        glyph = WORDMARK[ch]
        w = max(len(r) for r in glyph)
        for y, r in enumerate(glyph):
            for x, c in enumerate(r):
                if c == "#":
                    cells.add((x0 + x + (n - 1 - y) // SHEAR, y))
        x0 += w + TRACK
    return cells


def build_logos():
    mark, fav = read_grid("mark.txt"), read_grid("favicon.txt")
    mw, mh = len(mark[0]), len(mark)
    write("mark.svg", pixel_svg(mw, mh, 4, mark_body(mark)))
    write("favicon.svg", pixel_svg(len(fav[0]), len(fav), 2, mark_body(fav)))
    word = wordmark_cells()
    ww = max(x for x, _ in word) + 1
    for name, ink in (("wordmark.svg", INK_LIGHT), ("wordmark-dark.svg", INK_DARK)):
        write(name, pixel_svg(ww, 12, 4, f'<path fill="{ink}" d="{pixel_path(word)}"/>\n'))
    # the wordmark spans the f's rows: ascender (its first row) to baseline
    top = next(y for y, r in enumerate(mark) if "#" in r)
    lw = mw + GAP + ww
    for name, ink in (("logo.svg", INK_LIGHT), ("logo-dark.svg", INK_DARK)):
        body = mark_body(mark) + f'<path fill="{ink}" d="{pixel_path(word, mw + GAP, top)}"/>\n'
        write(name, pixel_svg(lw, mh, 6, body))


# --------------------------------------------------------------------------------------------
# Headline benchmark chart


def parse_benchmarks():
    """{"Windows": (plugins, {row label: {column: cell}}), "Linux": ...} from the headline tables."""
    lines = open(BENCHMARKS, encoding="utf-8").read().splitlines()
    tables = {}
    for i, line in enumerate(lines):
        m = re.match(r"\| (Windows|Linux) \((\d+) plugins\) \|", line)
        if not m or m.group(1) in tables:
            continue
        header = [c.strip() for c in line.strip().strip("|").split("|")]
        rows = {}
        j = i + 2
        while j < len(lines) and lines[j].startswith("|"):
            cells = [c.strip() for c in lines[j].strip().strip("|").split("|")]
            rows[cells[0]] = dict(zip(header[1:], cells[1:]))
            j += 1
        tables[m.group(1)] = (int(m.group(2)), rows)
    for os_name in ("Windows", "Linux"):
        if os_name not in tables:
            sys.exit(f"build.py: no '| {os_name} (N plugins) |' headline table in {BENCHMARKS}")
    return tables


def seconds(cell):
    m = re.fullmatch(r"([\d,.]+) (s|ms)", cell.strip())
    if not m:
        sys.exit(f"build.py: cannot read a time from {cell!r}")
    v = float(m.group(1).replace(",", ""))
    return v / 1000 if m.group(2) == "ms" else v


def fmt_seconds(v):
    if v >= 1000:
        return f"{v:,.0f} s"
    if v >= 10:
        return f"{v:.1f} s"
    return f"{v:.2f} s"


def speedup(cell, which):
    """'463x / 69.2x' -> '463x' (which=0, total) or '69.2x' (which=1, geo-mean)."""
    return cell.split("/")[which].strip()


CHART_THEMES = {
    "light": dict(bg="#ffffff", border="#d1d9e0", text=INK_LIGHT, text2="#59636e", muted="#6e7781",
                  grid="#e6eaef", accent=GREEN, accent_soft="#8fd9a8", other="#8c959f",
                  other_soft="#c5ccd4"),
    "dark": dict(bg="#0d1117", border="#30363d", text=INK_DARK, text2="#9198a1", muted="#7d8590",
                 grid="#21262d", accent=GLYPH, accent_soft="#2a7a48", other="#848d97",
                 other_soft="#454c56"),
}

PANELS = (
    ("Windows", "Windows 11 x64, 5 GiB raw image"),
    ("Linux", "Ubuntu 24.04, Linux 6.8, 3 GiB ELF core"),
)


def build_chart():
    tables = parse_benchmarks()
    W = 840
    X_TOOL, X_RUN, X0, DECADE = 28, 164, 256, 112.0   # bars: 1 s at X0, 10x per DECADE px
    DECADES = 4                                     # 1 s .. 10,000 s
    ROW, BAR, GROUP_GAP = 22, 12, 8

    def x_of(v):
        return X0 + math.log10(v) * DECADE

    panels = []
    for os_name, image in PANELS:
        plugins, rows = tables[os_name]
        total = rows["total wall (sum of per-plugin best)"]
        speed = rows["speedup vs python: total / geo-mean"]
        py = seconds(total["python"])
        panels.append(dict(
            title=f"{image} · {plugins} plugins",
            tools=[
                ("python volatility3", "other", [("repeat run", py, f"{fmt_seconds(py)}  ({py / 60:.0f} min)", None)]),
                ("vol-rs", "other", [
                    ("first run", seconds(total["vol-rs cold"]), None, None),
                    ("repeat run", seconds(total["vol-rs warm"]), None, None)]),
                ("fastvol", "accent", [
                    ("first run", seconds(total["fastvol cold"]), None, speedup(speed["fastvol cold"], 0)),
                    ("repeat run", seconds(total["fastvol warm"]), None, speedup(speed["fastvol warm"], 0))]),
            ]))

    def render(theme):
        t = CHART_THEMES[theme]
        out = []
        y = 104
        desc = []
        grid_ticks = [10 ** k for k in range(DECADES + 1)]
        for p in panels:
            out.append(f'<text x="{X_TOOL}" y="{y}" class="h">{esc(p["title"])}</text>')
            top = y + 12
            ry = top
            rows_svg = []
            for tool, kind, runs in p["tools"]:
                for k, (run, v, label, factor) in enumerate(runs):
                    cy = ry + ROW / 2
                    if k == 0:
                        cls = "tool b" if kind == "accent" else "tool"
                        ty = ry + len(runs) * ROW / 2
                        rows_svg.append(f'<text x="{X_TOOL}" y="{ty + 4.5:.1f}" class="{cls}">{tool}</text>')
                    rows_svg.append(f'<text x="{X_RUN}" y="{cy + 4.5:.1f}" class="run">{run}</text>')
                    soft = run == "first run"
                    fill = t[kind + ("_soft" if soft else "")]
                    x1 = x_of(v)
                    r = 4
                    yb = cy - BAR / 2
                    rows_svg.append(
                        f'<path fill="{fill}" d="M{X0} {yb:.1f}H{x1 - r:.1f}A{r} {r} 0 0 1 {x1:.1f} {yb + r:.1f}'
                        f'V{yb + BAR - r:.1f}A{r} {r} 0 0 1 {x1 - r:.1f} {yb + BAR:.1f}H{X0}Z"/>')
                    text = label or fmt_seconds(v)
                    vcls = "val b" if kind == "accent" else "val"
                    extra = f'<tspan class="note" dx="8">{factor} faster than python</tspan>' if factor else ""
                    rows_svg.append(f'<text x="{x1 + 7:.1f}" y="{cy + 4.5:.1f}" class="{vcls}">{esc(text)}{extra}</text>')
                    desc.append(f"{p['title']}: {tool} {run} {fmt_seconds(v)}")
                    ry += ROW
                ry += GROUP_GAP
            bottom = ry - GROUP_GAP
            for tick in grid_ticks:
                gx = x_of(tick)
                out.append(f'<path d="M{gx:.1f} {top - 2}V{bottom + 2}" class="grid"/>')
            out.extend(rows_svg)
            y = bottom + 40
        axis_y = y - 18
        for tick in grid_ticks:
            out.append(f'<text x="{x_of(tick):.1f}" y="{axis_y}" class="tick" text-anchor="middle">{tick:,} s</text>')
        foot_y = axis_y + 34
        foot = [
            "Sum of the best wall-clock time of each plugin (5 runs; python 1 or 2), one process per plugin, image in the page cache.",
            "First run: the tool's caches emptied before every run. Repeat run: caches as the previous run left them. Source: bench/vm/BENCHMARKS.md",
        ]
        for k, line in enumerate(foot):
            out.append(f'<text x="{X_TOOL}" y="{foot_y + k * 17}" class="foot">{esc(line)}</text>')
        H = foot_y + 17 + 22
        title = "Total time to run the benchmark suite"
        head = [
            f'<rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="12" fill="{t["bg"]}" stroke="{t["border"]}"/>',
            f'<text x="{X_TOOL}" y="42" class="title">{title}</text>',
            f'<text x="{X_TOOL}" y="64" class="sub">Each plugin run once as its own process, and the times added up. Log scale: each gridline is 10x. Shorter is faster.</text>',
        ]
        style = f"""<style>
text{{font-family:{FONT};fill:{t['text']}}}
.title{{font-size:17px;font-weight:600}}
.sub{{font-size:12.5px;fill:{t['text2']}}}
.h{{font-size:13px;font-weight:600}}
.tool{{font-size:13px;fill:{t['text2']}}}
.run{{font-size:12px;fill:{t['muted']}}}
.val{{font-size:12px;fill:{t['text2']};paint-order:stroke;stroke:{t['bg']};stroke-width:5px;stroke-linejoin:round}}
.b{{font-weight:600;fill:{t['text']}}}
.note{{font-weight:400;fill:{t['muted']}}}
.tick{{font-size:11px;fill:{t['muted']}}}
.foot{{font-size:11px;fill:{t['muted']}}}
.grid{{stroke:{t['grid']};stroke-width:1;fill:none}}
</style>"""
        return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-labelledby="t d">\n'
                f"<!-- Generated by docs/assets/build.py from bench/vm/BENCHMARKS.md. Do not edit. -->\n"
                f'<title id="t">{title}</title>\n<desc id="d">{esc("; ".join(desc))}. Source: bench/vm/BENCHMARKS.md.</desc>\n'
                + style + "\n" + "\n".join(head + out) + "\n</svg>\n")

    write("benchmark.svg", render("light"))
    write("benchmark-dark.svg", render("dark"))


# --------------------------------------------------------------------------------------------
# Badges

# Advance widths (em) of Liberation Sans, which has Arial's metrics, for ASCII 32..126 and "·".
_CHARS = "".join(chr(c) for c in range(32, 127)) + "·"
_WIDTHS = [float(w) for w in (
    "0.278,0.278,0.355,0.556,0.556,0.889,0.667,0.191,0.333,0.333,0.389,0.584,0.278,0.333,0.278,0.278,"
    "0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.278,0.278,0.584,0.584,0.584,0.556,"
    "1.015,0.667,0.667,0.722,0.722,0.667,0.611,0.778,0.722,0.278,0.500,0.667,0.556,0.833,0.722,0.778,"
    "0.667,0.778,0.722,0.667,0.611,0.722,0.667,0.944,0.667,0.667,0.611,0.278,0.278,0.278,0.469,0.556,"
    "0.333,0.556,0.556,0.500,0.556,0.556,0.278,0.556,0.556,0.222,0.222,0.500,0.222,0.833,0.556,0.556,"
    "0.556,0.556,0.333,0.500,0.278,0.556,0.500,0.722,0.500,0.500,0.500,0.334,0.260,0.334,0.584,0.333"
).split(",")]
_WIDTH = dict(zip(_CHARS, _WIDTHS))


def text_width(s, size):
    return sum(_WIDTH.get(ch, 0.6) for ch in s) * size


BADGES = (
    ("volatility3", "volatility3", "2.28.2"),
    ("plugins", "plugins", "197"),
    ("parity", "parity", "1975/1975"),
    ("dependencies", "dependencies", "0"),
    ("images", "images", "windows · linux · macos"),
    ("license", "license", "VSL 1.0"),
)


def build_badges():
    size, h, pad = 11, 20, 7
    for name, label, value in BADGES:
        lw = round(text_width(label, size)) + 2 * pad
        vw = round(text_width(value, size)) + 2 * pad
        w = lw + vw
        tl = round(text_width(label, size), 1)
        tv = round(text_width(value, size), 1)
        write(f"badges/{name}.svg", f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{esc(label)}: {esc(value)}">
<title>{esc(label)}: {esc(value)}</title>
<clipPath id="r"><rect width="{w}" height="{h}" rx="4"/></clipPath>
<g clip-path="url(#r)">
<rect width="{lw}" height="{h}" fill="#30363d"/>
<rect x="{lw}" width="{vw}" height="{h}" fill="{GREEN_BADGE}"/>
</g>
<g fill="#fff" font-family="Helvetica Neue, Helvetica, Arial, Liberation Sans, sans-serif" font-size="{size}">
<text x="{pad}" y="14" textLength="{tl}" lengthAdjust="spacingAndGlyphs">{esc(label)}</text>
<text x="{lw + pad}" y="14" textLength="{tv}" lengthAdjust="spacingAndGlyphs">{esc(value)}</text>
</g>
</svg>
''')


# --------------------------------------------------------------------------------------------
# PNG previews


def render_pngs():
    chromium = shutil.which("chromium") or shutil.which("chromium-browser") or shutil.which("google-chrome")
    if not chromium:
        sys.exit("build.py: --png needs chromium on PATH")
    jobs = (
        # (output, svg, css width, css height, background, device scale)
        ("png/mark-384.png", "mark.svg", 384, 256, "transparent", 1),
        ("png/favicon-16.png", "favicon.svg", 16, 16, "transparent", 1),
        ("png/favicon-32.png", "favicon.svg", 32, 32, "transparent", 1),
        ("png/favicon-48.png", "favicon.svg", 48, 48, "transparent", 1),
        ("png/favicon-64.png", "favicon.svg", 64, 64, "transparent", 1),
        ("png/logo.png", "logo.svg", None, None, "#ffffff", 2),
        ("png/logo-dark.png", "logo-dark.svg", None, None, "#0d1117", 2),
        ("png/benchmark.png", "benchmark.svg", None, None, "transparent", 2),
        ("png/benchmark-dark.png", "benchmark-dark.svg", None, None, "transparent", 2),
    )
    with tempfile.TemporaryDirectory() as tmp:
        for out, svg, w, h, bg, scale in jobs:
            if w is None:
                m = re.search(r'width="(\d+)" height="(\d+)"', read(svg))
                w, h = int(m.group(1)), int(m.group(2))
            page = os.path.join(tmp, "page.html")
            with open(page, "w") as f:
                f.write(f'<!doctype html><html><head><style>html,body{{margin:0;background:{bg}}}'
                        f'img{{display:block;width:{w}px;height:{h}px}}</style></head>'
                        f'<body><img src="file://{os.path.join(HERE, svg)}"></body></html>')
            target = os.path.join(HERE, out)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            subprocess.run([chromium, "--headless=new", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
                            "--default-background-color=00000000", f"--force-device-scale-factor={scale}",
                            f"--window-size={w},{h}", f"--screenshot={target}", f"file://{page}"],
                           check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("wrote", os.path.relpath(target, ROOT))


def main():
    build_logos()
    build_chart()
    build_badges()
    if "--png" in sys.argv[1:]:
        render_pngs()


if __name__ == "__main__":
    main()
