#!/usr/bin/env python3
"""Build the README artwork in docs/assets from its sources.

Hand-written sources (edit these):
  mark.txt       the fastvol mark: the pixel "fv" on its tile, 24x16 ('#' glyph, '+' tile,
                 '.' transparent). The row count stays even: `fvol --version` prints the same
                 grid in a terminal with half blocks, two pixel rows per line (src/cli/banner.rs
                 includes this file).
  favicon.txt    the mark squeezed onto a 16x16 tile for favicons
  WORDMARK below the pixel-italic "fastvol" lettering (12 rows)

Generated by this script (do not edit by hand):
  mark.svg, favicon.svg          the grids as crisp SVG paths
  wordmark.svg, wordmark-dark.svg
                                 the lettering for light and dark backgrounds
  logo.svg, logo-dark.svg        mark + wordmark, horizontal lockups (a 16-row pixel grid: show them at
                                 whole multiples, 6x = the width/height the SVG declares, as in the README)
  benchmark.svg, benchmark-dark.svg
                                 the README's headline chart, from bench/local/summary.json
                                 (bench/scripts/bench_local_report.py)
  badges/*.svg                   the README's rust, release and license badges, from Cargo.toml
                                 (the CI status badge next to them is GitHub's own)
  png/*.png                      previews, only with --png (needs a chromium on PATH)

Usage: python3 docs/assets/build.py [--png]

Standard library only.
"""

import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
SUMMARY = os.environ.get("FASTVOL_BENCH_SUMMARY", os.path.join(ROOT, "bench", "local", "summary.json"))

GLYPH = "#46e67a"       # phosphor green: the fv, and fastvol's colour on dark backgrounds
TILE = "#123020"        # the mark's tile
GREEN = "#1f9e57"       # the glyph green darkened for light backgrounds (3.4:1 on white)
INK_LIGHT = "#1f2328"   # GitHub's light-theme text colour
INK_DARK = "#f0f6fc"    # GitHub's dark-theme text colour

FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif"


def read(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return f.read()


def write(name, text):
    path = os.path.join(HERE, name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# --------------------------------------------------------------------------------------------
# Wordmark and logo lockups

GENERATED = "<!-- Generated by docs/assets/build.py from mark.txt / favicon.txt / WORDMARK. Do not edit. -->"

# The pixel-italic wordmark: one list of rows per letter, 12 rows, baseline = last row; each row
# is sheared right by 1 px per SHEAR rows above the baseline, letters TRACK px apart.
WORDMARK = {
    "f": ["..####", ".#####", ".##...", ".##...", "######", "######",
          ".##...", ".##...", ".##...", ".##...", ".##...", ".##..."],
    "a": ["", "", "", "", "######.", "#######", ".....##", ".######",
          "#######", "##...##", "#######", ".######"],
    "s": ["", "", "", "", ".######", "#######", "##.....", "######.",
          ".######", ".....##", "#######", "######."],
    "t": ["", ".##...", ".##...", ".##...", "######", "######",
          ".##...", ".##...", ".##...", ".##...", ".#####", "..####"],
    "v": ["", "", "", "", "##...##", "##...##", "##...##", "##...##",
          ".##.##.", ".##.##.", "..###..", "..###.."],
    "o": ["", "", "", "", ".#####.", "#######", "##...##", "##...##",
          "##...##", "##...##", "#######", ".#####."],
    "l": ["##"] * 12,
}
SHEAR = 4
TRACK = 2
GAP = 6  # between the mark and the wordmark


def read_grid(name):
    rows = [r.rstrip("\n") for r in read(name).splitlines() if r.strip()]
    if len({len(r) for r in rows}) != 1:
        sys.exit(f"build.py: {name}: rows of different lengths")
    if len(rows) % 2:
        sys.exit(f"build.py: {name}: the row count must be even (two pixel rows per terminal line)")
    return rows


def cells_of(rows, chars):
    return {(x, y) for y, r in enumerate(rows) for x, c in enumerate(r) if c in chars}


def pixel_path(cells, ox=0, oy=0):
    """Rectangles covering `cells`: horizontal runs, stacked where the next rows repeat them."""
    runs = {}
    for x, y in sorted(cells, key=lambda c: (c[1], c[0])):
        row = runs.setdefault(y, [])
        if row and row[-1][0] + row[-1][1] == x:
            row[-1][1] += 1
        else:
            row.append([x, 1])
    done, d = set(), []
    for y in sorted(runs):
        for x, w in runs[y]:
            if (x, w, y) in done:
                continue
            h = 1
            while [x, w] in runs.get(y + h, []):
                done.add((x, w, y + h))
                h += 1
            d.append(f"M{x + ox} {y + oy}h{w}v{h}h-{w}z")
    return "".join(d)


def pixel_svg(w, h, scale, body):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w * scale}" '
            f'height="{h * scale}" role="img" aria-label="fastvol" shape-rendering="crispEdges">\n'
            f"{GENERATED}\n{body}</svg>\n")


def mark_body(rows, ox=0):
    return (f'<path fill="{TILE}" d="{pixel_path(cells_of(rows, "#+"), ox)}"/>\n'
            f'<path fill="{GLYPH}" d="{pixel_path(cells_of(rows, "#"), ox)}"/>\n')


def wordmark_cells():
    cells, x0, n = set(), 0, 12
    for ch in "fastvol":
        glyph = WORDMARK[ch]
        w = max(len(r) for r in glyph)
        for y, r in enumerate(glyph):
            for x, c in enumerate(r):
                if c == "#":
                    cells.add((x0 + x + (n - 1 - y) // SHEAR, y))
        x0 += w + TRACK
    return cells


def build_logos():
    mark, fav = read_grid("mark.txt"), read_grid("favicon.txt")
    mw, mh = len(mark[0]), len(mark)
    write("mark.svg", pixel_svg(mw, mh, 4, mark_body(mark)))
    write("favicon.svg", pixel_svg(len(fav[0]), len(fav), 2, mark_body(fav)))
    word = wordmark_cells()
    ww = max(x for x, _ in word) + 1
    for name, ink in (("wordmark.svg", INK_LIGHT), ("wordmark-dark.svg", INK_DARK)):
        write(name, pixel_svg(ww, 12, 4, f'<path fill="{ink}" d="{pixel_path(word)}"/>\n'))
    # the wordmark spans the f's rows: ascender (its first row) to baseline
    top = next(y for y, r in enumerate(mark) if "#" in r)
    lw = mw + GAP + ww
    for name, ink in (("logo.svg", INK_LIGHT), ("logo-dark.svg", INK_DARK)):
        body = mark_body(mark) + f'<path fill="{ink}" d="{pixel_path(word, mw + GAP, top)}"/>\n'
        write(name, pixel_svg(lw, mh, 6, body))


# --------------------------------------------------------------------------------------------
# Headline benchmark chart


def load_summary():
    """bench/local/summary.json (bench/scripts/bench_local_report.py)."""
    with open(SUMMARY, encoding="utf-8") as f:
        return json.load(f)


def fmt_seconds(v):
    if v >= 100:
        return f"{v:,.0f} s"
    if v >= 10:
        return f"{v:.1f} s"
    if v >= 1:
        return f"{v:.2f} s"
    return f"{v * 1e3:.0f} ms" if v >= 0.1 else f"{v * 1e3:.1f} ms"


def fmt_factor(r):
    return f"{r:,.0f}x" if r >= 100 else f"{r:.1f}x" if r >= 10 else f"{r:.2f}x"


CHART_THEMES = {
    "light": dict(bg="#ffffff", border="#d1d9e0", text=INK_LIGHT, text2="#59636e", muted="#6e7781",
                  grid="#e6eaef", accent=GREEN, accent_soft="#8fd9a8", other="#8c959f",
                  other_soft="#c5ccd4"),
    "dark": dict(bg="#0d1117", border="#30363d", text=INK_DARK, text2="#9198a1", muted="#7d8590",
                 grid="#21262d", accent=GLYPH, accent_soft="#2a7a48", other="#848d97",
                 other_soft="#454c56"),
}

PANELS = (
    ("windows", "Windows 11 x64", "5 GiB raw image"),
    ("linux", "Ubuntu 24.04, Linux 6.8", "3 GiB ELF core"),
)

# (name, summary key, colour) in plot order
CHART_TOOLS = (("python volatility3", "py", "other"), ("vol-rs", "vr", "other"), ("fastvol", "fv", "accent"))


def cpu_name(m):
    return re.sub(r"\s+", " ", re.sub(r"^\d+th Gen |\(R\)|\(TM\)", "", m["cpu"])).strip()


def machine_line(m):
    return (f"Measured on a desktop: {cpu_name(m)} ({m['cores']} cores, {m['cpus']} threads), {round(m['mem_gib'] / 8) * 8} GB RAM, "
            f"NVMe SSD, Linux {m['kernel'].split('-')[0]}.")


def build_chart():
    S = load_summary()
    W, X_PAD, PANEL_GAP = 840, 28, 24
    PANEL_W = (W - 2 * X_PAD - PANEL_GAP) / 2  # the two systems side by side
    Y_LABELS = 50                              # tick-label column left of each plot
    COL, PAIR = 24, 50                         # column width; first-to-repeat centre distance
    INSET_L, INSET_R = 8, 20                   # plot insets; the right one leaves room for fastvol's labels
    DECADE = 64                                # log scale: px per power of ten
    panels, values = [], []
    for os_name, system, image in PANELS:
        tr = S["triage"].get(os_name, {})
        c = tr.get("cached", {})
        if not c.get("first") or not c.get("second"):
            continue
        tools = []
        for name, key, kind in CHART_TOOLS:
            runs = []
            for run, r in (("first", "first"), ("repeat", "second")):
                v = c[r][key]["total"]
                runs.append((run, v, c[r]["py"]["total"] / v if key == "fv" else None))
                values.append(v)
            tools.append((name, kind, runs))
        panels.append(dict(system=system, image=f"{image} · {tr.get('plugins', 0)} plugins in a row", tools=tools))
    if not panels:
        sys.exit(f"build.py: no triage results in {SUMMARY}")
    # one axis for both systems, whole decades around every value
    LO, HI = math.floor(math.log10(min(values))), math.ceil(math.log10(max(values)))

    def tick_label(k):
        v = 10.0 ** k
        return f"{v:g} s" if v >= 1 else f"{v * 1e3:g} ms"

    def render(theme):
        t = CHART_THEMES[theme]
        out, desc = [], []
        top = 156                              # the HI gridline
        base = top + (HI - LO) * DECADE        # the LO gridline, where the columns stand

        def y_of(v):
            return base - (math.log10(v) - LO) * DECADE

        for i, p in enumerate(panels):
            x0 = X_PAD + i * (PANEL_W + PANEL_GAP)
            px0, px1 = x0 + Y_LABELS, x0 + PANEL_W
            c0 = px0 + INSET_L + COL / 2
            group = (px1 - INSET_R - COL / 2 - c0 - PAIR) / (len(p["tools"]) - 1)
            out.append(f'<text x="{x0}" y="102" class="h">{esc(p["system"])}</text>')
            out.append(f'<text x="{x0}" y="120" class="sub">{esc(p["image"])}</text>')
            for k in range(LO, HI + 1):
                gy = y_of(10.0 ** k)
                out.append(f'<path d="M{px0} {gy:.1f}H{px1}" class="{"axis" if k == LO else "grid"}"/>')
                out.append(f'<text x="{px0 - 8}" y="{gy + 4:.1f}" class="tick" text-anchor="end">{tick_label(k)}</text>')
            for g, (tool, kind, runs) in enumerate(p["tools"]):
                gc = c0 + g * group + PAIR / 2
                out.append(f'<text x="{gc:.1f}" y="{base + 36}" class="{"tool b" if kind == "accent" else "tool"}" '
                           f'text-anchor="middle">{tool}</text>')
                for k, (run, v, factor) in enumerate(runs):
                    cx = c0 + g * group + k * PAIR
                    x, ty = cx - COL / 2, y_of(v)
                    r = min(4, (base - ty) / 2)
                    fill = t[kind + ("_soft" if run == "first" else "")]
                    out.append(
                        f'<path fill="{fill}" d="M{x:.1f} {base}V{ty + r:.1f}A{r} {r} 0 0 1 {x + r:.1f} {ty:.1f}'
                        f'H{x + COL - r:.1f}A{r} {r} 0 0 1 {x + COL:.1f} {ty + r:.1f}V{base}Z">'
                        f'<title>{esc(f"{tool}, {run} session: {fmt_seconds(v)}")}</title></path>')
                    vcls = "val b" if kind == "accent" else "val"
                    out.append(f'<text x="{cx:.1f}" y="{ty - 8:.1f}" class="{vcls}" text-anchor="middle">{fmt_seconds(v)}</text>')
                    if factor:
                        out.append(f'<text x="{cx:.1f}" y="{ty - 23:.1f}" class="note" text-anchor="middle">'
                                   f'{fmt_factor(factor)} faster</text>')
                    out.append(f'<text x="{cx:.1f}" y="{base + 17}" class="run" text-anchor="middle">{run}</text>')
                    desc.append(f"{p['system']}: {tool} {run} session {fmt_seconds(v)}")
        H = base + 60
        title = "Time for a triage session"
        head = [
            f'<rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="12" fill="{t["bg"]}" stroke="{t["border"]}"/>',
            f'<text x="{X_PAD}" y="42" class="title">{title}</text>',
            f'<text x="{X_PAD}" y="64" class="sub">Benchmarked on an {esc(cpu_name(S["machine"]))}</text>',
        ]
        halo = f"paint-order:stroke;stroke:{t['bg']};stroke-width:5px;stroke-linejoin:round"
        style = f"""<style>
text{{font-family:{FONT};fill:{t['text']}}}
.title{{font-size:17px;font-weight:600}}
.sub{{font-size:12.5px;fill:{t['text2']}}}
.h{{font-size:13px;font-weight:600}}
.tool{{font-size:13px;fill:{t['text2']}}}
.run{{font-size:11.5px;fill:{t['muted']}}}
.val{{font-size:12px;fill:{t['text2']};{halo}}}
.b{{font-weight:600;fill:{t['text']}}}
.note{{font-size:11px;fill:{t['muted']};{halo}}}
.tick{{font-size:11px;fill:{t['muted']}}}
.grid{{stroke:{t['grid']};stroke-width:1;fill:none}}
.axis{{stroke:{t['border']};stroke-width:1;fill:none}}
</style>"""
        return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-labelledby="t d">\n'
                f"<!-- Generated by docs/assets/build.py from bench/local/summary.json. Do not edit. -->\n"
                f'<title id="t">{title}</title>\n<desc id="d">{esc("; ".join(desc))}. {esc(machine_line(S["machine"]))} Source: bench/local/BENCHMARKS.md.</desc>\n'
                + style + "\n" + "\n".join(head + out) + "\n</svg>\n")

    write("benchmark.svg", render("light"))
    write("benchmark-dark.svg", render("dark"))


# --------------------------------------------------------------------------------------------
# Badges

# Advance widths (em) of Liberation Sans, which has Arial's metrics, for ASCII 32..126 and "·".
_CHARS = "".join(chr(c) for c in range(32, 127)) + "·"
_WIDTHS = [float(w) for w in (
    "0.278,0.278,0.355,0.556,0.556,0.889,0.667,0.191,0.333,0.333,0.389,0.584,0.278,0.333,0.278,0.278,"
    "0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.556,0.278,0.278,0.584,0.584,0.584,0.556,"
    "1.015,0.667,0.667,0.722,0.722,0.667,0.611,0.778,0.722,0.278,0.500,0.667,0.556,0.833,0.722,0.778,"
    "0.667,0.778,0.722,0.667,0.611,0.722,0.667,0.944,0.667,0.667,0.611,0.278,0.278,0.278,0.469,0.556,"
    "0.333,0.556,0.556,0.500,0.556,0.556,0.278,0.556,0.556,0.222,0.222,0.500,0.222,0.833,0.556,0.556,"
    "0.556,0.556,0.333,0.500,0.278,0.556,0.500,0.722,0.500,0.500,0.500,0.334,0.260,0.334,0.584,0.333"
).split(",")]
_WIDTH = dict(zip(_CHARS, _WIDTHS))


def text_width(s, size):
    return sum(_WIDTH.get(ch, 0.6) for ch in s) * size


def badges():
    """(file, label, value, value colour): white text at 5:1 or more on each colour. The shape
    (20 px high, 3 px radius, #30363d label) matches the CI status badge GitHub draws."""
    with open(os.path.join(ROOT, "Cargo.toml"), "rb") as f:
        pkg = tomllib.load(f)["package"]
    return (
        ("rust", "rust", f"{pkg['rust-version']}+", "#b7410e"),
        ("release", "release", f"v{pkg['version']}", "#0969da"),
        ("license", "license", "VSL 1.0", "#8250df"),
    )


def build_badges():
    size, h, pad = 11, 20, 7
    for name, label, value, colour in badges():
        lw = round(text_width(label, size)) + 2 * pad
        vw = round(text_width(value, size)) + 2 * pad
        w = lw + vw
        tl = round(text_width(label, size), 1)
        tv = round(text_width(value, size), 1)
        write(f"badges/{name}.svg", f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="{esc(label)}: {esc(value)}">
<title>{esc(label)}: {esc(value)}</title>
<clipPath id="r"><rect width="{w}" height="{h}" rx="3"/></clipPath>
<g clip-path="url(#r)">
<rect width="{lw}" height="{h}" fill="#30363d"/>
<rect x="{lw}" width="{vw}" height="{h}" fill="{colour}"/>
</g>
<g fill="#fff" font-family="Helvetica Neue, Helvetica, Arial, Liberation Sans, sans-serif" font-size="{size}">
<text x="{pad}" y="14" textLength="{tl}" lengthAdjust="spacingAndGlyphs">{esc(label)}</text>
<text x="{lw + pad}" y="14" textLength="{tv}" lengthAdjust="spacingAndGlyphs">{esc(value)}</text>
</g>
</svg>
''')


# --------------------------------------------------------------------------------------------
# PNG previews


def render_pngs():
    chromium = shutil.which("chromium") or shutil.which("chromium-browser") or shutil.which("google-chrome")
    if not chromium:
        sys.exit("build.py: --png needs chromium on PATH")
    jobs = (
        # (output, svg, css width, css height, background, device scale)
        ("png/mark-384.png", "mark.svg", 384, 256, "transparent", 1),
        ("png/favicon-16.png", "favicon.svg", 16, 16, "transparent", 1),
        ("png/favicon-32.png", "favicon.svg", 32, 32, "transparent", 1),
        ("png/favicon-48.png", "favicon.svg", 48, 48, "transparent", 1),
        ("png/favicon-64.png", "favicon.svg", 64, 64, "transparent", 1),
        ("png/logo.png", "logo.svg", None, None, "#ffffff", 2),
        ("png/logo-dark.png", "logo-dark.svg", None, None, "#0d1117", 2),
        ("png/benchmark.png", "benchmark.svg", None, None, "transparent", 2),
        ("png/benchmark-dark.png", "benchmark-dark.svg", None, None, "transparent", 2),
    )
    with tempfile.TemporaryDirectory() as tmp:
        for out, svg, w, h, bg, scale in jobs:
            if w is None:
                m = re.search(r'width="(\d+)" height="(\d+)"', read(svg))
                w, h = int(m.group(1)), int(m.group(2))
            page = os.path.join(tmp, "page.html")
            with open(page, "w") as f:
                f.write(f'<!doctype html><html><head><style>html,body{{margin:0;background:{bg}}}'
                        f'img{{display:block;width:{w}px;height:{h}px}}</style></head>'
                        f'<body><img src="file://{os.path.join(HERE, svg)}"></body></html>')
            target = os.path.join(HERE, out)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            subprocess.run([chromium, "--headless=new", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
                            "--default-background-color=00000000", f"--force-device-scale-factor={scale}",
                            f"--window-size={w},{h}", f"--screenshot={target}", f"file://{page}"],
                           check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("wrote", os.path.relpath(target, ROOT))


def main():
    build_logos()
    build_chart()
    build_badges()
    if "--png" in sys.argv[1:]:
        render_pngs()


if __name__ == "__main__":
    main()
